// GENERATED from barrier-pro-model.mjs. barrier-pro-r0.3
// Source SHA256 909035cdb92b3871c92d82414fea6f989db8a07e72e4566b7fe9d64d298f77a2. Run node tools/build-shader.mjs; DO NOT edit this file.
struct Envelope { kind:f32,r:f32,eventOn:f32,visible:f32,load:f32,angle:f32,residue:f32,core:f32, };
struct Point { x:f32,y:f32,z:f32, };
struct Field { r:f32,g:f32,b:f32,a:f32,coverage:f32,core:f32,emissionY:f32,normalX:f32,normalY:f32,normalZ:f32,stress:f32,pane:f32, };
fn sat(x:f32)->f32 {
  return clamp(x,0.0,1.0);
}
fn sq(x:f32)->f32 {
  return x*x;
}
fn ramp(a:f32,b:f32,x:f32)->f32 {
  return sat((x-a)/(b-a));
}
fn softBoundary(a:f32,b:f32,x:f32)->f32 {
  let s=ramp(a,b,x);
  return s*s*(3.0-2.0*s);
}
fn gauss(x:f32)->f32 {
  return exp(-x*x);
}
fn duration(kind:f32)->f32 {
  return select(650.0,480.0,kind>=2.0);
}
fn cornerX(i:f32)->f32 {
  return select(select(select(select(select(select(select(select(0.0,0.88,i==1.0),1.04,i==2.0),0.67,i==3.0),0.0,i==4.0),-0.67,i==5.0),-1.01,i==6.0),-0.96,i==7.0),0.0,i>=8.0);
}
fn cornerY(i:f32)->f32 {
  return select(select(select(select(select(select(select(select(-0.86,-0.67,i==1.0),0.37,i==2.0),0.80,i==3.0),0.92,i==4.0),0.72,i==5.0),0.40,i==6.0),-0.63,i==7.0),-0.86,i>=8.0);
}
fn envelope(requested:f32,age:f32,authority:f32)->Envelope {
  let on=select(0.0,1.0,requested>=0.0 && requested<=3.0 && age>=0.0 && age<duration(requested));
  let kind=select(-1.0,requested,on>0.5);
  let r=sat(age/duration(requested));
  let visible=select(0.0,1.0,on>0.5 || authority>0.5);
  let load=0.16+0.84*exp(-3.2*r);
  let angle=select(select(0.0,(38.0-32.0*r)*0.0174532925199433,kind==0.0),(20.0+38.0*r)*0.0174532925199433,kind==3.0);
  let residue=select(select(1.0,1.0-0.65*r,kind==3.0),1.0-0.70*r,kind==2.0);
  let core=select(select(select(0.0,0.50+0.28*sin(3.141592653589793*r),kind==0.0),0.16+0.68*exp(-3.2*r),kind==1.0),0.60*exp(-5.0*r),kind==2.0);
  return Envelope(kind,r,on,visible,load,angle,residue,core);
}
fn frontPoint(ex:f32,ey:f32,radial:f32,sector:f32,requested:f32,age:f32,authority:f32)->Point {
  let e=envelope(requested,age,authority);
  let side=select(-1.0,1.0,sector<4.0);
  let x0=ex*radial;
  let y0=ey*mix(0.72,1.0,ramp(0.60,1.0,radial));
  let centerY=ey*radial*1.20;
  let y=select(y0,centerY,radial<0.60);
  let z0=0.62-0.06*sat(radial/0.60)-0.37*ramp(0.60,1.0,radial);
  let stress=gauss((x0-0.05)/0.65)*gauss((y-0.08)/0.45);
  let dent=select(0.0,0.31*e.load*stress,e.kind==1.0);
  let pinch=select(0.0,0.20*e.load*gauss(y/0.38)*ramp(0.35,0.8,abs(x0)),e.kind==1.0);
  let x=x0-side*pinch;
  let z=z0-dent;
  let theta=side*e.angle;
  let hinge=side*1.0;
  let dx=x-hinge;
  let dz=z-0.19;
  let rx=hinge+cos(theta)*dx+sin(theta)*dz;
  let rz=0.19-sin(theta)*dx+cos(theta)*dz;
  return Point(rx,y,rz);
}
fn rearPoint(ex:f32,ey:f32,radial:f32)->Point {
  let x=ex*radial;
  let y=ey*radial*1.10;
  let z=-0.62+0.07*sat(radial/0.70)+0.27*ramp(0.70,1.0,radial);
  return Point(x,y,z);
}
fn geometry(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32)->Point {
  let e=envelope(requested,age,authority);
  let ex=mix(cornerX(sector),cornerX(sector+1.0),u);
  let ey=mix(cornerY(sector),cornerY(sector+1.0),u);
  let radial=select(select(select(select(0.70*v,0.70+0.30*v,band==1.0),1.0,band==2.0),0.60+0.40*v,band==3.0),0.60*v,band==4.0);
  let f=frontPoint(ex,ey,radial,sector,requested,age,authority);
  let b=rearPoint(ex,ey,radial);
  let frontWeight=select(select(0.0,v,band==2.0),1.0,band>=3.0);
  let x0=mix(b.x,f.x,frontWeight);
  let y0=mix(b.y,f.y,frontWeight);
  let z0=mix(b.z,f.z,frontWeight);
  let broken=select(0.0,1.0,e.kind==2.0);
  let fold=0.10*e.r*sin(4.0*y0+2.0*x0)*broken;
  let releaseSide=select(-1.0,1.0,sector<4.0);
  let releaseShift=select(0.0,releaseSide*(0.12+0.38*e.r),e.kind==3.0);
  let x=x0*(1.0-broken*(0.06+0.16*e.r))+releaseShift;
  let y=y0*(1.0-broken*(0.04+0.10*e.r))*select(1.0,1.0-0.12*e.r,e.kind==3.0);
  let z=z0*(1.0-broken*(0.10+0.35*e.r))+fold;
  return Point(x,y,z);
}
fn material(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32,hPx:f32,coreOn:f32,yaw:f32,pitch:f32)->Field {
  let e=envelope(requested,age,authority);
  let g=geometry(u,v,sector,band,requested,age,authority);
  let up=geometry(min(0.9999,u+0.001),v,sector,band,requested,age,authority);
  let um=geometry(max(0.0001,u-0.001),v,sector,band,requested,age,authority);
  let vp=geometry(u,min(0.9999,v+0.001),sector,band,requested,age,authority);
  let vm=geometry(u,max(0.0001,v-0.001),sector,band,requested,age,authority);
  let tx=up.x-um.x;
  let ty=up.y-um.y;
  let tz=up.z-um.z;
  let ux=vp.x-vm.x;
  let uy=vp.y-vm.y;
  let uz=vp.z-vm.z;
  let cx=ty*uz-tz*uy;
  let cy=tz*ux-tx*uz;
  let cz=tx*uy-ty*ux;
  let nn=max(0.000000001,sqrt(cx*cx+cy*cy+cz*cz));
  let outward=select(1.0,-1.0,band>=3.0);
  let nx=outward*cx/nn;
  let ny=outward*cy/nn;
  let nz=outward*cz/nn;
  let face=clamp(0.50+0.31*abs(nx)+0.22*ny+0.18*nz,0.16,0.98);
  let front=select(0.0,1.0,band>=3.0);
  let pane=select(0.0,1.0,band==0.0 || band==4.0);
  let aa=0.70/hPx;
  let crack=g.y-(0.12+0.36*g.x+0.07*sin(9.0*g.x)+0.11*g.z);
  let fork=g.x-(-0.26+0.20*g.y+0.035*sin(18.0*g.y));
  let gap=0.022+0.092*e.r;
  let fractureMask=softBoundary(gap-aa,gap+aa,abs(crack))*(1.0-softBoundary(0.18,0.40,g.y)*(1.0-softBoundary(gap*0.55-aa,gap*0.55+aa,abs(fork))));
  let coverage=e.visible*select(1.0,fractureMask,e.kind==2.0);
  let stress=gauss((g.x-0.05)/0.70)*gauss((g.y-0.08)/0.46);
  let tauBase=select(select(select(select(0.019,0.38,band==1.0),0.48,band==2.0),0.49,band==3.0),0.026,band==4.0);
  let tauLoad=select(0.0,front*(0.044*pane+0.08*(1.0-pane))*e.load*stress,e.kind==1.0);
  let tauBust=select(0.0,0.28*front*pane,e.kind==3.0);
  let bustRear=select(1.0,select(0.90-0.70*e.r,1.0,front>0.5),e.kind==3.0);
  let tau=(tauBase+tauLoad+tauBust)*(0.82+0.24*face)*e.residue*bustRear;
  let alpha=coverage*(1.0-exp(-tau));
  let baseR=mix(0.07,0.022,front);
  let baseG=mix(0.11,0.20+0.06*face,front);
  let baseB=mix(0.30,0.34,front);
  let broad=(0.64+0.36*face)*(1.0-pane);
  let ER0=mix(0.026,0.012,front)*broad+pane*mix(0.0003+0.001*v*v,0.0012+0.0025*v*v,front);
  let EG0=mix(0.050,0.130,front)*broad+pane*mix(0.0008+0.003*v*v,0.0128+0.022*v*v,front);
  let EB0=mix(0.150,0.190,front)*broad+pane*mix(0.0020+0.008*v*v,0.0228+0.034*v*v,front);
  let loadBand=select(0.0,front*(1.0-pane)*e.load*gauss((g.y-0.10)/0.23),e.kind==1.0);
  let bustPane=select(0.0,front*pane,e.kind==3.0);
  let paneLoad=select(0.0,front*pane*e.load*stress,e.kind==1.0);
  let createFacing=select(1.0,0.86+0.14*e.r,e.kind==0.0);
  let gain=e.residue*bustRear*createFacing;
  let core=coreOn*e.core*front*(1.0-pane)*gauss((g.x-0.78)/0.024)*gauss((g.y-0.37)/0.038);
  let er=coverage*((ER0+0.012*bustPane+0.018*loadBand+0.004*paneLoad)*gain+1.05*core);
  let eg=coverage*((EG0+0.066*bustPane+0.14*loadBand+0.040*paneLoad)*gain+1.0*core);
  let eb=coverage*((EB0+0.085*bustPane+0.10*loadBand+0.052*paneLoad)*gain+0.94*core);
  return Field(alpha*baseR+er,alpha*baseG+eg,alpha*baseB+eb,alpha,coverage,core*coverage,0.2126*er+0.7152*eg+0.0722*eb,nx,ny,nz,stress,pane);
}
// 64-byte ABI. No background, caster, character UV, or baked vertex color in field model.
struct Params { viewport:vec4f,event:vec4f,pose:vec4f,options:vec4f };
@group(0) @binding(0) var<uniform> p:Params;
@group(1) @binding(0) var previousDepth:texture_depth_2d;
@group(1) @binding(1) var<uniform> peel:vec4u;
struct RV { @builtin(position) position:vec4f,@location(0) uv:vec2f,
 @location(1) @interpolate(flat) sector:f32,@location(2) @interpolate(flat) band:f32 };
fn rotatePoint(g:Point)->vec3f{
 let cy=cos(p.pose.z);let sy=sin(p.pose.z);let cp=cos(p.pose.w);let sp=sin(p.pose.w);
 let x=cy*g.x+sy*g.z;let z=-sy*g.x+cy*g.z;return vec3f(x,cp*g.y-sp*z,sp*g.y+cp*z);
}
@vertex fn vs(@location(0) a:vec4f)->RV{
 let g=geometry(a.x,a.y,a.z,a.w,p.event.x,p.viewport.w,p.event.y);let pos=rotatePoint(g);
 let pix=p.pose.xy+vec2f(pos.x,-pos.y)*p.viewport.z;
 var o:RV;o.position=vec4f(2.0*pix.x/p.viewport.x-1.0,1.0-2.0*pix.y/p.viewport.y,0.5-0.15*pos.z,1.0);
 o.uv=a.xy;o.sector=a.z;o.band=a.w;return o;
}
struct Out { @location(0) rgba:vec4f,@location(1) depth:f32 };
@fragment fn fs(a:RV)->Out{
 if((u32(p.options.z)&(1u<<u32(a.band)))==0u){discard;}
 if(peel.x>0u){let old=textureLoad(previousDepth,vec2i(a.position.xy),0);if(a.position.z<=old+0.000002){discard;}}
 let f=material(a.uv.x,a.uv.y,a.sector,a.band,p.event.x,p.viewport.w,p.event.y,p.viewport.z,p.options.x,p.pose.z,p.pose.w);
 if(f.coverage<=0.00001){discard;}
 var c=vec4f(f.r,f.g,f.b,f.a);
 if(p.options.y==1.0){c=vec4f(vec3f(f.a),f.a);}
 if(p.options.y==2.0){c=vec4f(vec3f(f.emissionY),f.a);}
 if(p.options.y==3.0){c=vec4f((vec3f(f.normalX,f.normalY,f.normalZ)*0.5+0.5)*0.85,1.0);}
 if(p.options.y==4.0){c=vec4f(vec3f(0.08+0.15*a.band,0.7-0.11*a.band,0.18+0.09*a.sector)*0.75,0.75);}
 return Out(c,a.position.z);
}
// Compute parity is separate from visibility, peeling, and rasterization quality.
struct Probe { config:vec4f,parametric:vec4f,settings:vec4f };
struct ProbeOut { point:vec4f,rgba:vec4f,diagnosis:vec4f };
@group(2) @binding(0) var<storage,read> probes:array<Probe>;
@group(2) @binding(1) var<storage,read_write> outputs:array<ProbeOut>;
@compute @workgroup_size(64) fn parity(@builtin(global_invocation_id) id:vec3u){
 if(id.x>=arrayLength(&probes)){return;}
 let a=probes[id.x];let g=geometry(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z);
 let f=material(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z,a.config.w,a.settings.x,a.settings.y,a.settings.z);
 outputs[id.x]=ProbeOut(vec4f(g.x,g.y,g.z,f.coverage),vec4f(f.r,f.g,f.b,f.a),vec4f(f.core,f.emissionY,f.normalX,f.normalY));
}
