import test from 'node:test';import assert from 'node:assert/strict';import {synthesizeMana,encodeWav,soundEnvelope} from '../src/synth.js';import {VoiceMixer} from '../src/audio-core.js';
const pcm=synthesizeMana({sampleRate:24000});const energy=a=>Math.sqrt(a.reduce((s,x)=>s+x*x,0)/Math.max(1,a.length));
test('stereo PCM is finite, deterministic and non-clipping',()=>{const other=synthesizeMana({sampleRate:24000});assert.deepEqual(pcm.left,other.left);assert.equal(pcm.left.length,36000);assert.ok([...pcm.left,...pcm.right].every(x=>Number.isFinite(x)&&Math.abs(x)<1));assert.ok(energy(pcm.left)>0.05);});
test('tail is genuinely low amplitude, ending at zero',()=>{assert.ok(energy(pcm.left.slice(34200))<energy(pcm.left.slice(15000,18000))*0.06);assert.ok(Math.abs(pcm.left.at(-1))<1e-6);});
test('envelope spans acquisition and settlement without extra onset trigger',()=>{for(const p of [0.1,0.3,0.5,0.7,0.9])assert.ok(soundEnvelope(p)>0);assert.equal(soundEnvelope(0),0);assert.equal(soundEnvelope(1),0);});
for(const rate of [1,2])test(`mixer ends after 1500/${rate} wall-ms`,()=>{const m=new VoiceMixer();m.begin({id:'e',pcm,rate,at:0});const l=new Float32Array(24000*2),r=new Float32Array(l.length);m.render(l,r,0,24000);assert.equal(m.stats.starts,1);assert.equal(m.voices.size,0);assert.ok(l.subarray(Math.ceil(36000/rate)+1).every(x=>x===0));});
test('nearby three causes yield three voices and bounded mix',()=>{const m=new VoiceMixer();for(let i=0;i<3;i++)m.begin({id:`e${i}`,pcm,ageMs:-160*i,rate:1,at:0});assert.equal(m.stats.starts,1); // negative age rejected; schedule via begin at the cause time instead
const n=new VoiceMixer();const l=new Float32Array(256),r=new Float32Array(256);for(let i=0;i<3;i++){n.begin({id:`e${i}`,pcm,at:i*0.16});n.render(l,r,i*0.16,24000);}assert.equal(n.stats.starts,3);assert.equal(n.stats.maxConcurrent,3);assert.ok([...l,...r].every(x=>Math.abs(x)<1));});
test('duplicate active cause cannot allocate a fourth voice',()=>{const m=new VoiceMixer();assert.equal(m.begin({id:'e',pcm}),true);assert.equal(m.begin({id:'e',pcm}),false);assert.equal(m.stats.starts,1);});
test('actor pause produces zero samples rather than DC',()=>{const m=new VoiceMixer();m.begin({id:'e',pcm,ageMs:500,rate:0});const l=new Float32Array(512),r=new Float32Array(512);m.render(l,r,0,24000);assert.ok(l.every(x=>x===0));assert.equal(m.voices.size,1);});
test('sync changes rate without re-onset or new voice',()=>{const m=new VoiceMixer();m.begin({id:'e',pcm});m.sync({id:'e',ageMs:300,rate:2,at:0.3});assert.equal(m.stats.starts,1);assert.equal(m.age(m.voices.get('e'),0.5),700);});
test('cancel release is at most 4ms',()=>{const m=new VoiceMixer();m.begin({id:'e',pcm,ageMs:400});m.cancel('e',0.01);const l=new Float32Array(1000),r=new Float32Array(1000);m.render(l,r,0,24000);assert.ok(l.subarray(340).every(x=>x===0));assert.equal(m.voices.size,0);});
test('reset removes every voice immediately',()=>{const m=new VoiceMixer();m.begin({id:'e',pcm});m.reset();assert.equal(m.voices.size,0);});
test('WAV has expected stereo PCM16 header',()=>{const wav=encodeWav(pcm),v=new DataView(wav.buffer);assert.equal(new TextDecoder().decode(wav.slice(0,4)),'RIFF');assert.equal(v.getUint16(22,true),2);assert.equal(v.getUint32(24,true),24000);assert.equal(v.getUint32(40,true),pcm.left.length*4);});
