import test from 'node:test';import assert from 'node:assert/strict';import {ManaAcquireSystem} from '../src/state.js';
function setup(options={}){const clock={timeMs:1000,rate:1},body={x:0,y:0,heightPx:64,alive:true,present:true,inVent:false,invisible:false},calls=[];const audio={begin:v=>{calls.push(['begin',v]);return true;},sync:v=>calls.push(['sync',v]),cancel:(...v)=>calls.push(['cancel',...v]),reset:()=>calls.push(['reset'])};const s=new ManaAcquireSystem({sessionId:'s',getActorClock:()=>clock,getBeneficiary:()=>body,audio,...options});const e={sessionId:'s',eventId:'e',beneficiaryPlayerId:'b',actorPlayerId:'a',manaDelta:4,committed:true};return {s,clock,body,calls,e};}
test('default ownership, duration and radius',()=>{const {s,e}=setup();assert.equal(s.onManaCommitted(e).status,'accepted');assert.equal(s.snapshot()[0].durationMs,1500);assert.equal(s.snapshot()[0].radiusPx,82);assert.equal(s.snapshot()[0].beneficiaryPlayerId,'b');assert.equal(s.snapshot()[0].actorPlayerId,'a');});
for(const delta of [0,-1,NaN,Infinity,-Infinity,'1',null])test(`reject nonpositive or invalid mana ${delta}`,()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,manaDelta:delta}).status,'rejected');assert.equal(s.snapshot().length,0);});
for(const flag of [false,undefined,1,'true'])test(`authority must be true (${flag})`,()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,committed:flag}).status,'rejected');});
test('DESIRE private refinement excluded',()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,route:'desire-refinement'}).status,'rejected');});
test('other routes share the same effect contract',()=>{const {s,e}=setup();for(const route of ['item','reward','skill',undefined])assert.equal(s.onManaCommitted({...e,eventId:String(route),route}).status,'accepted');assert.equal(s.snapshot().length,4);});
for(const durationMs of [1,500,899])test(`minimum 900 actor ms from ${durationMs}`,()=>{const {s,e}=setup();const r=s.onManaCommitted({...e,durationMs});assert.equal(r.durationMs,900);assert.equal(r.clampedDuration,true);});
for(const durationMs of [0,-2,NaN,Infinity])test(`invalid duration ${durationMs}`,()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,durationMs}).status,'rejected');});
test('expire exactly at lifetime and never replay',()=>{const {s,e,clock,calls}=setup();s.onManaCommitted(e);clock.timeMs=2499.99;s.advance();assert.equal(s.snapshot().length,1);clock.timeMs=2500;s.advance();assert.equal(s.snapshot().length,0);assert.equal(s.onManaCommitted(e).status,'duplicate');assert.equal(calls.filter(x=>x[0]==='begin').length,1);});
for(const rate of [1,2])test(`actor phase ${rate}x with no double multiplication`,()=>{const {s,e,clock}=setup();s.onManaCommitted(e);clock.rate=rate;clock.timeMs+=530*rate;s.advance();assert.equal(s.snapshot()[0].ageMs,530*rate);clock.timeMs=2500;s.advance();assert.equal(s.snapshot().length,0);});
test('rate change preserves accumulated age',()=>{const {s,e,clock}=setup();s.onManaCommitted(e);clock.timeMs=1200;clock.rate=2;s.advance();assert.equal(s.snapshot()[0].ageMs,200);clock.timeMs=1400;s.advance();assert.equal(s.snapshot()[0].ageMs,400);clock.rate=0;s.advance();assert.equal(s.snapshot()[0].ageMs,400);});
for(const [field,value,reason] of [['alive',false,'dead'],['present',false,'departed'],['inVent',true,'vent'],['invisible',true,'invisible']]){
 test(`active cleanup ${reason}`,()=>{const {s,e,body,calls}=setup();s.onManaCommitted(e);body[field]=value;s.advance();assert.equal(s.snapshot().length,0);assert.equal(calls.filter(c=>c[0]==='cancel').length,1);body[field]=!value;assert.equal(s.onManaCommitted(e).status,'duplicate');});
 test(`initial suppression ${reason} consumes event`,()=>{const {s,e,body}=setup();body[field]=value;assert.equal(s.onManaCommitted(e).status,'suppressed');body[field]=!value;assert.equal(s.onManaCommitted(e).status,'duplicate');});
}
test('missing body suppresses with no audio',()=>{const {s,e,calls}=setup({getBeneficiary:()=>null});assert.equal(s.onManaCommitted(e).status,'suppressed');assert.equal(calls.length,0);});
test('shared cause has one sound for multiple beneficiaries',()=>{const {s,e,calls}=setup();s.onManaCommitted(e);s.onManaCommitted({...e,beneficiaryPlayerId:'b2'});assert.equal(s.snapshot().length,2);assert.equal(calls.filter(c=>c[0]==='begin').length,1);s.invalidateBeneficiary('b');assert.equal(calls.filter(c=>c[0]==='cancel').length,0);s.invalidateBeneficiary('b2');assert.equal(calls.filter(c=>c[0]==='cancel').length,1);});
test('one audio sync per cause, not per body',()=>{const {s,e,calls}=setup();s.onManaCommitted(e);s.onManaCommitted({...e,beneficiaryPlayerId:'b2'});s.advance();assert.equal(calls.filter(c=>c[0]==='sync').length,1);});
test('three distinct nearby causes: three starts, no dedupe collision',()=>{const {s,e,clock,calls}=setup();for(let i=0;i<3;i++){clock.timeMs=1000+i*160;s.onManaCommitted({...e,eventId:`event${i}`});}assert.equal(s.snapshot().length,3);assert.equal(calls.filter(c=>c[0]==='begin').length,3);for(let i=0;i<3;i++)assert.equal(s.onManaCommitted({...e,eventId:`event${i}`}).status,'duplicate');});
for(const field of ['actorPlayerId','durationMs','startedAtActorMs'])test(`shared cause cannot change ${field}`,()=>{const {s,e}=setup();s.onManaCommitted(e);const value={actorPlayerId:'different',durationMs:900,startedAtActorMs:900}[field];assert.equal(s.onManaCommitted({...e,beneficiaryPlayerId:'other',[field]:value}).reason,'cause-contract-conflict');});
test('future onset rejects',()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,startedAtActorMs:1001}).status,'rejected');});
test('stale cause is consumed, not restarted',()=>{const {s,e,clock}=setup();clock.timeMs=3000;assert.equal(s.onManaCommitted({...e,startedAtActorMs:1000}).reason,'already-expired');assert.equal(s.onManaCommitted({...e,startedAtActorMs:1000}).status,'duplicate');});
test('skipped audio is never retried when unlocked later',()=>{let enabled=false,n=0;const {s,e}=setup({audio:{begin:()=>{n++;return enabled;},sync:()=>{}}});assert.equal(s.onManaCommitted(e).sfx,'skipped');enabled=true;s.advance();s.onManaCommitted({...e,beneficiaryPlayerId:'b2'});assert.equal(n,1);});
test('session switch clears and rejects old session',()=>{const {s,e}=setup();s.onManaCommitted(e);s.setSession('next');assert.equal(s.snapshot().length,0);assert.equal(s.onManaCommitted(e).reason,'wrong-session');assert.equal(s.onManaCommitted({...e,sessionId:'next'}).status,'accepted');});
test('clock rewind removes all actor-owned effects',()=>{const {s,e,clock}=setup();s.onManaCommitted(e);s.onManaCommitted({...e,eventId:'e2'});clock.timeMs=999;s.advance();assert.equal(s.snapshot().length,0);});
for(const rate of [-1,NaN,Infinity,9])test(`invalid actor rate ${rate}`,()=>{const {s,e,clock}=setup();s.onManaCommitted(e);clock.rate=rate;s.advance();assert.equal(s.snapshot().length,0);});
test('actor identity is not replaced by beneficiary identity',()=>{const ids=[];const {s,e}=setup({getActorClock:id=>{ids.push(id);return {timeMs:1000,rate:1};}});s.onManaCommitted(e);s.advance();assert.deepEqual([...new Set(ids)],['a']);});
test('body transform follows beneficiary',()=>{const {s,e,body}=setup();s.onManaCommitted(e);body.x=53;body.y=92;s.advance();assert.equal(s.snapshot()[0].body.x,53);assert.equal(s.snapshot()[0].body.y,92);});
test('snapshots do not mutate internal or host state',()=>{const {s,e,body}=setup();s.onManaCommitted(e);s.snapshot()[0].body.x=800;assert.equal(body.x,0);assert.equal(s.snapshot()[0].body.x,0);});
test('dedupe capacity fails closed instead of evicting history',()=>{const {s,e}=setup({maxSessionEvents:1});s.onManaCommitted(e);assert.equal(s.onManaCommitted({...e,eventId:'new'}).reason,'session-dedupe-capacity');assert.equal(s.onManaCommitted(e).status,'duplicate');});
test('active-capacity suppression still consumes the recipient',()=>{const {s,e}=setup({maxActive:1});s.onManaCommitted(e);const r={...e,eventId:'overflow'};assert.equal(s.onManaCommitted(r).reason,'active-capacity');s.invalidateBeneficiary('b');assert.equal(s.onManaCommitted(r).status,'duplicate');});
test('callback exception is contained and suppresses',()=>{const {s,e}=setup({getBeneficiary:()=>{throw Error('host');}});assert.equal(s.onManaCommitted(e).status,'suppressed');});
test('explicit actor invalidation removes dependent bodies',()=>{const {s,e}=setup();s.onManaCommitted(e);s.invalidateActor('a');assert.equal(s.snapshot().length,0);});
test('disposed system cannot accept a new cause',()=>{const {s,e}=setup();s.dispose();s.dispose();assert.equal(s.onManaCommitted(e).reason,'disposed');});
test('tuple ID encoding avoids separator collision',()=>{const {s,e}=setup();s.onManaCommitted({...e,eventId:'a|b',beneficiaryPlayerId:'c'});s.onManaCommitted({...e,eventId:'a',beneficiaryPlayerId:'b|c'});assert.equal(s.snapshot().length,2);});
test('explicit null start is invalid rather than silently received-now',()=>{const {s,e}=setup();assert.equal(s.onManaCommitted({...e,startedAtActorMs:null}).reason,'invalid-start');});
