import test from 'node:test';import assert from 'node:assert/strict';import {HeartSFX,synthesizeHeartPCM} from '../src/sfx.mjs';
function audioMock(){const state={made:0,starts:0,stops:0,closed:0,gains:[]};const context={sampleRate:48000,currentTime:0,state:'suspended',destination:{},createBuffer:()=>({copyToChannel(){}}),createBufferSource:()=>({connect(){},disconnect(){},start(){state.starts++;},stop(){state.stops++;},onended:null}),createGain(){const node={connect(){},disconnect(){},gain:{cancelScheduledValues(){},cancelAndHoldAtTime(){},setValueAtTime(v){state.gains.push(v);},setTargetAtTime(v){state.gains.push(v);}}};return node;},async resume(){this.state='running';},async close(){this.state='closed';state.closed++;}};return {state,context,factory:()=>{state.made++;return context;}};}
const gesture={type:'click',isTrusted:true};
for(const rate of [8000,44100,48000,96000])test(`PCM: finite mono, bounded level and endpoints at ${rate} Hz`,()=>{const pcm=synthesizeHeartPCM(rate);assert.equal(pcm.length,rate*1.8);assert.equal(pcm[0],0);assert.equal(pcm.at(-1),0);let energy=0,peak=0;for(const s of pcm){assert(Number.isFinite(s));energy+=s*s;peak=Math.max(peak,Math.abs(s));}assert(peak<0.7);assert(energy>1);});
test('PCM: prepare/action/tail have distinct envelopes',()=>{const pcm=synthesizeHeartPCM();const energy=(a,b)=>{const s=pcm.slice(a*48000,b*48000);return s.reduce((v,x)=>v+x*x,0)/s.length;};assert(energy(.48,.63)>energy(.12,.25));assert(energy(1.5,1.7)<energy(.8,1));});
test('verify: no context or source even after gesture',async()=>{const m=audioMock(),s=new HeartSFX({verify:true,contextFactory:m.factory,isUserActive:()=>true});assert.equal(await s.unlockFromGesture(gesture),false);assert.equal(s.playOnce({id:'1'}),false);await s.dispose();assert.equal(m.state.made,0);assert.equal(m.state.starts,0);});
test('audio gesture: synthetic click cannot unlock',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>true});assert.equal(await s.unlockFromGesture({type:'click',isTrusted:false}),false);assert.equal(m.state.made,0);});
test('audio gesture: no user activation cannot unlock',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>false});assert.equal(await s.unlockFromGesture(gesture),false);assert.equal(m.state.made,0);});
test('one-shot: old silent ID never replays after unlock',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>true});assert.equal(s.playOnce({id:'old'}),false);await s.unlockFromGesture(gesture);assert.equal(s.playOnce({id:'old'}),false);assert.equal(s.playOnce({id:'new'}),true);assert.equal(s.playOnce({id:'new'}),false);assert.equal(m.state.starts,1);await s.dispose();});
test('audio: lifetime offset and expired start',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>true});await s.unlockFromGesture(gesture);assert.equal(s.playOnce({id:'expired',ageMs:1800}),false);assert.equal(s.playOnce({id:'alive',ageMs:300}),true);await s.dispose();});
test('audio: all concurrent sources share bounded master sum',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>true});await s.unlockFromGesture(gesture);for(let i=0;i<8;i++)assert(s.playOnce({id:i}));assert.equal(s.playOnce({id:9}),false);assert.equal(s.stats().voices,8);assert(m.state.gains.slice(-8).every(v=>v===0.05));await s.dispose();assert.equal(m.state.stops,8);assert.equal(m.state.closed,1);assert.equal(s.stats().voices,0);});
test('audio: repeated dispose is idempotent',async()=>{const m=audioMock(),s=new HeartSFX({contextFactory:m.factory,isUserActive:()=>true});await s.unlockFromGesture(gesture);s.playOnce({id:'a'});await s.dispose();await s.dispose();assert.equal(m.state.closed,1);assert.equal(m.state.stops,1);assert.equal(s.playOnce({id:'b'}),false);});
