import test from 'node:test';import assert from 'node:assert/strict';import {HeartGPU} from '../src/gpu.mjs';
globalThis.GPUBufferUsage={UNIFORM:64,COPY_DST:8};globalThis.GPUShaderStage={VERTEX:1,FRAGMENT:2};
function mockGPU(){
 const calls={buffers:0,destroyed:0,submits:0,draws:0,writes:[],formats:[]};
 const pass={setPipeline(){},setScissorRect(...args){calls.scissor=args;},setBindGroup(){},draw(){calls.draws++;},end(){}};
 const device={lost:new Promise(()=>{}),addEventListener(){},removeEventListener(){},pushErrorScope(){},async popErrorScope(){return null;},createShaderModule:()=>({async getCompilationInfo(){return {messages:[]};}}),createBindGroupLayout:x=>x,createPipelineLayout:x=>x,async createRenderPipelineAsync(x){calls.formats.push(x.fragment.targets[0].format);return {};},createBuffer(){calls.buffers++;return {destroy(){calls.destroyed++;}};},createBindGroup:()=>({}),createCommandEncoder:()=>({beginRenderPass:()=>pass,finish:()=>({})}),queue:{writeBuffer(b,o,data){calls.writes.push([...data]);},submit(){calls.submits++;},async onSubmittedWorkDone(){}}};return {calls,device};
}
test('GPU API mock: fixed caster uniforms and finite lifetime filter (not shader compilation)',async()=>{const m=mockGPU(),gpu=await HeartGPU.create(m.device,'rgba8unorm-srgb','test-placeholder');gpu.render({}, {width:64,height:64,items:[{x:32,y:32,h:64,ageMs:670},{x:9,y:9,h:64,ageMs:1800}]});assert.equal(m.calls.draws,1);assert.deepEqual(m.calls.writes[0].slice(0,4),[64,64,32,32]);assert.equal(m.calls.writes[0][6],64);assert.equal(m.calls.formats[0],'rgba8unorm-srgb');gpu.dispose();});
test('GPU API mock: multiple events normalize emission budget',async()=>{const m=mockGPU(),gpu=await HeartGPU.create(m.device,'rgba8unorm-srgb','test-placeholder');gpu.render({}, {width:64,height:64,items:Array.from({length:8},()=>({x:32,y:32,h:64,ageMs:670}))});assert.equal(m.calls.draws,8);for(let i=0;i<8;i++)assert.equal(m.calls.writes[0][i*64+9],1/8);gpu.dispose();});
test('GPU API mock: scissor clamp and disposal are idempotent',async()=>{const m=mockGPU(),gpu=await HeartGPU.create(m.device,'rgba8unorm-srgb','test-placeholder');gpu.render({}, {width:64,height:64,items:[{x:32,y:32,h:64,ageMs:670,clipRect:{x:-10,y:2,width:30,height:200}}]});assert.deepEqual(m.calls.scissor,[0,2,20,62]);gpu.dispose();gpu.dispose();assert.equal(m.calls.destroyed,1);assert.equal(gpu.ready,false);assert.equal(gpu.render({}, {width:64,height:64}),false);});
