// GENERATED from barrier-pro-model.mjs. barrier-pro-r0.4
// Source SHA256 224ee1ccb7b6fb754b04b0ed85788ff9a501e1be9bc3cc735a0c826dd86af8d6. Run node tools/build-shader.mjs; DO NOT edit this file.
struct Envelope { kind:f32,r:f32,eventOn:f32,visible:f32,load:f32,depthScale:f32,seam:f32,residue:f32,core:f32, };
struct Point { x:f32,y:f32,z:f32, };
struct Field { r:f32,g:f32,b:f32,a:f32,coverage:f32,core:f32,emissionY:f32,normalX:f32,normalY:f32,normalZ:f32,stress:f32,pane:f32, };
fn sat(x:f32)->f32 {
  return clamp(x,0.0,1.0);
}
fn sq(x:f32)->f32 {
  return x*x;
}
fn ramp(a:f32,b:f32,x:f32)->f32 {
  return sat((x-a)/(b-a));
}
fn softBoundary(a:f32,b:f32,x:f32)->f32 {
  let s=ramp(a,b,x);
  return s*s*(3.0-2.0*s);
}
fn gauss(x:f32)->f32 {
  return exp(-x*x);
}
fn angular(theta:f32,center:f32,width:f32)->f32 {
  return gauss(2.0*sin((theta-center)*0.5)/width);
}
fn duration(kind:f32)->f32 {
  return select(650.0,480.0,kind>=2.0);
}
fn envelope(requested:f32,age:f32,authority:f32)->Envelope {
  let on=select(0.0,1.0,requested>=0.0 && requested<=3.0 && age>=0.0 && age<duration(requested));
  let kind=select(-1.0,requested,on>0.5);
  let r=sat(age/duration(requested));
  let visible=select(0.0,1.0,on>0.5 || authority>0.5);
  let load=0.20+0.80*exp(-3.4*r);
  let depthScale=select(select(1.0,0.48+0.52*r,kind==0.0),1.0-0.66*r,kind==3.0);
  let seam=select(select(0.0,0.82-0.72*r,kind==0.0),0.08+0.20*r,kind==3.0);
  let residue=select(select(1.0,1.0-0.82*r,kind==3.0),1.0-0.80*r,kind==2.0);
  let core=select(select(select(select(0.0,0.32+0.57*sin(3.141592653589793*r),kind==0.0),0.22+0.88*exp(-3.4*r),kind==1.0),0.12+0.54*exp(-4.0*r),kind==2.0),0.20+0.22*sin(3.141592653589793*r),kind==3.0);
  return Envelope(kind,r,on,visible,load,depthScale,seam,residue,core);
}
fn geometry(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32)->Point {
  let e=envelope(requested,age,authority);
  let theta=(sector+u)*0.7853981633974483;
  let lat=(v-0.5)*3.141592653589793;
  let s=sin(lat);
  let c=cos(lat);
  let thetaTwist=theta+0.20*s;
  let x0=1.16*(0.81+0.19*sin(3.141592653589793*v))*cos(thetaTwist)-0.12*s;
  let y0=1.88*(v-0.5)-0.085*sin(theta)+0.065*cos(theta)+0.055*sin(2.0*theta);
  let z0=0.74*(0.90+0.10*sin(3.141592653589793*v))*sin(thetaTwist)+0.07*s;
  let front=softBoundary(-0.10,0.65,sin(theta));
  let loadPatch=angular(theta,2.47,0.65)*gauss((v-0.55)/0.25);
  let dent=select(0.0,0.42*e.load*front*loadPatch,e.kind==1.0);
  let pinch=select(0.0,0.46*e.load*loadPatch,e.kind==1.0);
  let x1=x0+pinch;
  let y1=y0-0.07*dent;
  let z1=z0*e.depthScale-dent;
  let failure=select(0.0,1.0,e.kind==2.0);
  let breakLine=v-(0.47+0.115*cos(theta)+0.035*sin(5.0*theta));
  let curl=failure*(0.08+0.28*e.r)*gauss(breakLine/0.14)*front;
  let side=select(-1.0,1.0,cos(theta)>0.0);
  let release=select(0.0,0.08+0.26*e.r,e.kind==3.0);
  let releaseBend=select(0.0,0.15*e.r*sq(sin(theta)),e.kind==3.0);
  let x=x1*(1.0-failure*(0.02+0.20*e.r))+side*release*c;
  let y=y1*(1.0-failure*0.12*e.r);
  let z=z1*(1.0-failure*0.40*e.r)-curl+releaseBend*cos(theta);
  return Point(x,y,z);
}
fn material(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32,hPx:f32,coreOn:f32,yaw:f32,pitch:f32)->Field {
  let e=envelope(requested,age,authority);
  let theta=(sector+u)*0.7853981633974483;
  let g=geometry(u,v,sector,band,requested,age,authority);
  let up=geometry(u+0.001,v,sector,band,requested,age,authority);
  let um=geometry(u-0.001,v,sector,band,requested,age,authority);
  let vp=geometry(u,min(0.99999,v+0.001),sector,band,requested,age,authority);
  let vm=geometry(u,max(0.00001,v-0.001),sector,band,requested,age,authority);
  let tx=up.x-um.x;
  let ty=up.y-um.y;
  let tz=up.z-um.z;
  let ux=vp.x-vm.x;
  let uy=vp.y-vm.y;
  let uz=vp.z-vm.z;
  let cx=-(ty*uz-tz*uy);
  let cy=-(tz*ux-tx*uz);
  let cz=-(tx*uy-ty*ux);
  let nn=max(0.000000001,sqrt(cx*cx+cy*cy+cz*cz));
  let nx=cx/nn;
  let ny=cy/nn;
  let nz=cz/nn;
  let front=softBoundary(-0.15,0.50,sin(theta));
  let faceLight=clamp(0.78-0.22*nx+0.12*ny+0.08*nz,0.48,1.08);
  let frontLobe=angular(theta,2.24+0.72*(v-0.5),0.30)*gauss((v-0.61)/0.38);
  let rearLobe=angular(theta,5.54+0.74*(v-0.5),0.37)*gauss((v-0.40)/0.37);
  let poleTaper=0.28+0.72*sq(sin(3.141592653589793*v));
  let phaseLocation=1.10+e.seam+0.08;
  let formation=select(0.0,angular(theta,phaseLocation,0.26)*gauss((v-(0.56+0.32*e.r))/0.10),e.kind==0.0);
  let loadPatch=angular(theta,2.47,0.64)*gauss((v-0.55)/0.24);
  let loadLight=select(0.0,e.load*loadPatch,e.kind==1.0);
  let releaseLight=select(0.0,angular(theta,1.05-0.34*e.r,0.37)*gauss((v-0.58)/0.32),e.kind==3.0);
  let aa=0.58/hPx;
  let createDist=abs(2.0*sin((theta-1.10)*0.5));
  let createMask=softBoundary(e.seam-aa*2.5,e.seam+aa*2.5,createDist);
  let breakLine=v-(0.47+0.115*cos(theta)+0.035*sin(5.0*theta));
  let fork=theta-(2.12+0.18*sin(13.0*v));
  let gap=0.014+0.052*e.r;
  let fractureMask=softBoundary(gap-aa*0.5,gap+aa*0.5,abs(breakLine))*(1.0-softBoundary(0.53,0.62,v)*(1.0-softBoundary(gap*1.4-aa,gap*1.4+aa,abs(fork))));
  let bustMask=softBoundary(e.seam-aa,e.seam+aa,abs(cos(theta)));
  let coverage=e.visible*select(select(select(1.0,createMask,e.kind==0.0),fractureMask,e.kind==2.0),bustMask,e.kind==3.0);
  let breakLip=select(0.0,gauss((abs(breakLine)-gap-0.012)/0.032)*angular(theta,2.35,0.70)*(0.35+0.65*exp(-3.0*e.r)),e.kind==2.0);
  let lobe=max(frontLobe,rearLobe);
  let opticalResidue=select(select(1.0,1.0-0.68*e.r,e.kind==3.0),1.0-0.62*e.r,e.kind==2.0);
  let tau=(0.014+1.12*frontLobe+0.94*rearLobe+0.11*loadLight+0.18*formation)*opticalResidue;
  let alpha=coverage*(1.0-exp(-tau));
  let baseR=mix(0.020,0.012,front);
  let baseG=mix(0.060,0.09,front);
  let baseB=mix(0.16,0.14,front);
  let gain=faceLight*e.residue*poleTaper;
  let er0=0.0006+0.018*frontLobe+0.035*rearLobe+0.025*formation+0.28*loadLight+0.16*breakLip+0.045*releaseLight;
  let eg0=0.0018+0.66*frontLobe+0.33*rearLobe+0.20*formation+0.39*loadLight+0.15*breakLip+0.19*releaseLight;
  let eb0=0.0035+0.64*frontLobe+0.71*rearLobe+0.28*formation+0.12*loadLight+0.045*breakLip+0.24*releaseLight;
  let coreTheta=select(select(select(phaseLocation,2.47,e.kind==1.0),2.36,e.kind==2.0),1.05-0.34*e.r,e.kind==3.0);
  let coreV=select(select(select(0.56+0.32*e.r,0.55,e.kind==1.0),0.47+0.115*cos(2.36)+0.035*sin(5.0*2.36)+gap+0.013,e.kind==2.0),0.59,e.kind==3.0);
  let core=coreOn*e.core*angular(theta,coreTheta,0.035)*gauss((v-coreV)/0.018);
  let er=coverage*(er0*gain+0.86*core);
  let eg=coverage*(eg0*gain+1.02*core);
  let eb=coverage*(eb0*gain+0.75*core);
  return Field(alpha*baseR+er,alpha*baseG+eg,alpha*baseB+eb,alpha,coverage,core*coverage,0.2126*er+0.7152*eg+0.0722*eb,nx,ny,nz,loadLight,1.0-lobe);
}
// 64-byte ABI. No background, caster, character UV, or baked vertex color; four peels and one overflow probe in field model.
struct Params { viewport:vec4f,event:vec4f,pose:vec4f,options:vec4f };
@group(0) @binding(0) var<uniform> p:Params;
@group(1) @binding(0) var previousDepth:texture_depth_2d;
@group(1) @binding(1) var<uniform> peel:vec4u;
struct RV { @builtin(position) position:vec4f,@location(0) uv:vec2f,
 @location(1) @interpolate(flat) sector:f32,@location(2) @interpolate(flat) band:f32 };
fn rotatePoint(g:Point)->vec3f{
 let cy=cos(p.pose.z);let sy=sin(p.pose.z);let cp=cos(p.pose.w);let sp=sin(p.pose.w);
 let x=cy*g.x+sy*g.z;let z=-sy*g.x+cy*g.z;return vec3f(x,cp*g.y-sp*z,sp*g.y+cp*z);
}
@vertex fn vs(@location(0) a:vec4f)->RV{
 let g=geometry(a.x,a.y,a.z,a.w,p.event.x,p.viewport.w,p.event.y);let pos=rotatePoint(g);
 let pix=p.pose.xy+vec2f(pos.x,-pos.y)*p.viewport.z;
 var o:RV;o.position=vec4f(2.0*pix.x/p.viewport.x-1.0,1.0-2.0*pix.y/p.viewport.y,0.5-0.15*pos.z,1.0);
 o.uv=a.xy;o.sector=a.z;o.band=a.w;return o;
}
struct Out { @location(0) rgba:vec4f,@location(1) depth:f32 };
@fragment fn fs(a:RV)->Out{
 if((u32(p.options.z)&(1u<<u32(a.band)))==0u){discard;}
 if(peel.x>0u){let old=textureLoad(previousDepth,vec2i(a.position.xy),0);if(a.position.z<=old+0.000002){discard;}}
 let f=material(a.uv.x,a.uv.y,a.sector,a.band,p.event.x,p.viewport.w,p.event.y,p.viewport.z,p.options.x,p.pose.z,p.pose.w);
 if(f.coverage<=0.00001){discard;}
 let rotatedNormal=rotatePoint(Point(f.normalX,f.normalY,f.normalZ));
 if(p.options.w==1.0 && rotatedNormal.z<=0.0){discard;}
 if(p.options.w==2.0 && rotatedNormal.z>0.0){discard;}
 var c=vec4f(f.r,f.g,f.b,f.a);
 if(p.options.y==1.0){c=vec4f(vec3f(f.a),f.a);}
 if(p.options.y==2.0){c=vec4f(vec3f(f.emissionY),f.a);}
 if(p.options.y==3.0){c=vec4f((vec3f(f.normalX,f.normalY,f.normalZ)*0.5+0.5)*0.85,1.0);}
 if(p.options.y==4.0){c=vec4f(vec3f(0.08+0.15*a.band,0.7-0.11*a.band,0.18+0.09*a.sector)*0.75,0.75);}
 return Out(c,a.position.z);
}
// Compute parity is separate from visibility, peeling, and rasterization quality.
struct Probe { config:vec4f,parametric:vec4f,settings:vec4f };
struct ProbeOut { point:vec4f,rgba:vec4f,diagnosis:vec4f };
@group(2) @binding(0) var<storage,read> probes:array<Probe>;
@group(2) @binding(1) var<storage,read_write> outputs:array<ProbeOut>;
@compute @workgroup_size(64) fn parity(@builtin(global_invocation_id) id:vec3u){
 if(id.x>=arrayLength(&probes)){return;}
 let a=probes[id.x];let g=geometry(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z);
 let f=material(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z,a.config.w,a.settings.x,a.settings.y,a.settings.z);
 outputs[id.x]=ProbeOut(vec4f(g.x,g.y,g.z,f.coverage),vec4f(f.r,f.g,f.b,f.a),vec4f(f.core,f.emissionY,f.normalX,f.normalY));
}
