// Keep the deployed cache contract explicit so old Plicy workers are evicted.
// Previous contract: dva-static-v173-gameplay-polish.
// v468 hotfix keeps Heart Transfer on its dedicated fist-glow route while the
// raster finishes decoding, so the generic teleport ring never takes over.
// v520 adds independent Natural Recovery resources and its persistent marker,
// fixed Renki rewards, background resume repair, wall-default vector attacks,
// and evidence-bound enemy Bot corpse investigation.
const RUNTIME_RELEASE = "webgpu-main-bootstrap-v30";
const CACHE_NAME = "dva-static-webgpu-main-bootstrap-v30";
const RUNTIME_RECOVERY_REVISION = "v591-movement-transport-resilience-1";
const STATIC_ASSETS = [
  "/assets/generated/webgpu-text/atlas.json",
  "/assets/generated/webgpu-text/atlas-00.png",
  "/assets/generated/webgpu-text/atlas-01.png",
  "/assets/generated/webgpu-text/atlas-02.png",
  "/assets/generated/webgpu-text/atlas-03.png",
  "/assets/generated/webgpu-text/atlas-04.png",
  "/assets/generated/acceleration-body-original-v909.png",
  "/assets/generated/overheal-body-original-v913.png",
  "/assets/generated/mana-body-original-v903.png",
  "/assets/generated/philia-taser-switch-front-20260922.png",
  "/assets/generated/philia-taser-switch-back-20260922.png",
  "/assets/generated/philia-taser-switch-left-20260922.png",
  "/assets/generated/philia-taser-switch-right-20260922.png",
  "/assets/generated/sophia-assault-switch-front-20260922.png",
  "/assets/generated/sophia-assault-switch-back-20260922.png",
  "/assets/generated/sophia-assault-switch-left-20260922.png",
  "/assets/generated/sophia-assault-switch-right-20260922.png",
  "/assets/generated/sophia-smg-switch-left-v906.png",
  "/assets/generated/sophia-smg-switch-right-v906.png",
  "/assets/generated/sophia-sniper-switch-front-v907.png",
  "/assets/generated/sophia-sniper-switch-back-v907.png",
  "/assets/generated/sophia-sniper-switch-left-v907.png",
  "/assets/generated/sophia-sniper-switch-right-v907.png",
  "/assets/generated/heal-body-original-v902.png",
  "/assets/generated/stamina-body-original-v897.png",
  "/assets/generated/levitation-support-field-v901.png",
  "/assets/generated/philia-sniper-switch-back-source-v1.png",
  "/assets/generated/philia-sniper-switch-front-source-v1.png",
  "/assets/generated/philia-sniper-switch-left-source-v1.png",
  "/assets/generated/philia-sniper-switch-right-source-v1.png",
  "/assets/generated/sophia-taser-switch-back-v898.png",
  "/assets/generated/sophia-taser-switch-front-v898.png",
  "/assets/generated/sophia-taser-switch-left-v898.png",
  "/assets/generated/sophia-taser-switch-right-v898.png",
  "/assets/generated/philia-smg-moving-lower-left-direct-v898-candidate.png",
  "/assets/generated/philia-smg-moving-lower-right-direct-v898-candidate.png",
  "/assets/generated/taser-fire-male-bot-back-source-v1.png",
  "/assets/generated/taser-fire-male-bot-front-source-v1.png",
  "/assets/generated/taser-fire-male-bot-left-source-v1.png",
  "/assets/generated/taser-fire-male-bot-right-source-v1.png",
  "/assets/generated/taser-reload-male-bot-back-authored-20260915.png",
  "/assets/generated/taser-reload-male-bot-front-authored-20260915.png",
  "/assets/generated/taser-reload-male-bot-left-authored-20260915.png",
  "/assets/generated/taser-reload-male-bot-right-authored-20260915.png",
  "/assets/generated/sophia-sunbeam-front-v896.png",
  "/assets/generated/sophia-sunbeam-left-v896.png",
  "/assets/generated/sophia-sunbeam-right-v896.png",
  "/assets/generated/sophia-sunbeam-back-v896.png",
  "/assets/generated/philia-sunbeam-front-v894.png",
  "/assets/generated/philia-sunbeam-left-v894.png",
  "/assets/generated/philia-sunbeam-right-v894.png",
  "/assets/generated/philia-sunbeam-back-v894.png",
  "/assets/generated/flora-sunbeam-fresh-v892.png",
  "/assets/generated/gunner-weapon-handgun-crop-v892.png",
  "/assets/generated/gunner-weapon-smg-crop-v892.png",
  "/assets/generated/gunner-weapon-assault-crop-v892.png",
  "/assets/generated/gunner-weapon-sniper-crop-v892.png",
  "/assets/generated/tactics-novel-digest-poster-v890.png",
  "/assets/generated/item-frag-grenade-v889.png",
  "/assets/generated/item-stun-grenade-v889.png",
  "/assets/generated/grenade-frag-impact-v889.png",
  "/assets/generated/grenade-stun-impact-v889.png",
  "/assets/generated/bust-charge-v886.png",
  "/assets/generated/bust-fracture-v886.png",
  "/assets/generated/barrier-closed-shell-v886.png",
  "/assets/generated/sophia-handgun-switch-front-source-v1.png",
  "/assets/generated/sophia-handgun-switch-back-source-v1.png",
  "/assets/generated/sophia-handgun-switch-left-source-v1.png",
  "/assets/generated/sophia-handgun-switch-right-source-v1.png",
  "/assets/generated/philia-assault-switch-front-source-v1.png",
  "/assets/generated/philia-assault-switch-back-source-v1.png",
  "/assets/generated/philia-assault-switch-left-source-v1.png",
  "/assets/generated/philia-assault-switch-right-source-v1.png",
  "/assets/generated/sniper-fire-male-bot-front.png",
  "/assets/generated/sniper-fire-male-bot-back.png",
  "/assets/generated/sniper-fire-male-bot-left.png",
  "/assets/generated/sniper-fire-male-bot-right.png",
  "/assets/generated/philia-smg-switch-back-source-v1.png",
  "/assets/generated/philia-smg-switch-front-source-v1.png",
  "/assets/generated/philia-smg-switch-left-source-v1.png",
  "/assets/generated/philia-smg-switch-right-source-v1.png",
  "/assets/generated/assault-fire-male-bot-back.png",
  "/assets/generated/assault-fire-male-bot-front.png",
  "/assets/generated/assault-fire-male-bot-left.png",
  "/assets/generated/assault-fire-male-bot-right.png",
  "/assets/generated/philia-handgun-switch-front-source-v1.png",
  "/assets/generated/philia-handgun-switch-back-source-v1.png",
  "/assets/generated/philia-handgun-switch-left-source-v1.png",
  "/assets/generated/philia-handgun-switch-right-source-v1.png",
  "/assets/generated/sniper-reload-male-bot-front-authored-20260915.png",
  "/assets/generated/sniper-reload-male-bot-back-authored-20260915.png",
  "/assets/generated/sniper-reload-male-bot-left-authored-20260915.png",
  "/assets/generated/sniper-reload-male-bot-right-authored-20260915.png",
  "/assets/generated/assault-reload-male-bot-front-authored-20260915.png",
  "/assets/generated/assault-reload-male-bot-back-authored-20260915.png",
  "/assets/generated/assault-reload-male-bot-left-authored-20260915.png",
  "/assets/generated/assault-reload-male-bot-right-authored-20260915.png",
  "/assets/generated/smartphone-prepared-cell1-source-exact-v874.png",
  "/assets/generated/philia-sniper-fire-front-20260915.png",
  "/assets/generated/philia-sniper-fire-back-20260915.png",
  "/assets/generated/philia-sniper-fire-left-20260915.png",
  "/assets/generated/philia-sniper-fire-right-20260915.png",
  "/assets/generated/philia-taser-fire-front-20260915.png",
  "/assets/generated/philia-taser-fire-back-20260915.png",
  "/assets/generated/philia-taser-fire-left-20260915.png",
  "/assets/generated/philia-taser-fire-right-20260915.png",
  "/assets/generated/smg-fire-male-bot-front.png",
  "/assets/generated/smg-fire-male-bot-back.png",
  "/assets/generated/smg-fire-male-bot-left.png",
  "/assets/generated/smg-fire-male-bot-right.png",
  "/assets/generated/sophia-sniper-fire-front-20260915.png",
  "/assets/generated/sophia-sniper-fire-back-20260915.png",
  "/assets/generated/sophia-sniper-fire-left-20260915.png",
  "/assets/generated/sophia-sniper-fire-right-20260915.png",
  "/assets/generated/sophia-assault-fire-front-20260915.png",
  "/assets/generated/sophia-assault-fire-back-20260915.png",
  "/assets/generated/sophia-assault-fire-left-20260915.png",
  "/assets/generated/sophia-assault-fire-right-20260915.png",
  "/assets/generated/sophia-taser-fire-front-20260915.png",
  "/assets/generated/sophia-taser-fire-back-20260915.png",
  "/assets/generated/sophia-taser-fire-left-20260915.png",
  "/assets/generated/sophia-taser-fire-right-20260915.png",
  "/assets/generated/smg-reload-male-bot-front.png",
  "/assets/generated/smg-reload-male-bot-back.png",
  "/assets/generated/smg-reload-male-bot-left.png",
  "/assets/generated/smg-reload-male-bot-right.png",
  "/assets/generated/sophia-assault-reload-muted-front-20260915.png",
  "/assets/generated/sophia-assault-reload-muted-left-20260915.png",
  "/assets/generated/sophia-assault-reload-muted-right-20260915.png",
  "/assets/generated/sophia-assault-reload-muted-back-20260915.png",
  "/assets/generated/handgun-reload-male-bot-front.png",
  "/assets/generated/handgun-reload-male-bot-back.png",
  "/assets/generated/handgun-reload-male-bot-left.png",
  "/assets/generated/handgun-reload-male-bot-right.png",
  "/assets/generated/philia-assault-fire-back-v867.png",
  "/assets/generated/philia-assault-fire-front-v867.png",
  "/assets/generated/philia-assault-fire-left-v867.png",
  "/assets/generated/philia-assault-fire-right-v867.png",
  "/assets/generated/philia-assault-reload-back-alpha-repair-v867.png",
  "/assets/generated/philia-smg-fire-back-v867.png",
  "/assets/generated/philia-smg-fire-front-v867.png",
  "/assets/generated/philia-smg-fire-left-v867.png",
  "/assets/generated/philia-smg-fire-right-v867.png",
  "/assets/generated/sophia-smg-fire-back-v868.png",
  "/assets/generated/sophia-smg-fire-front-v868.png",
  "/assets/generated/sophia-smg-fire-left-v868.png",
  "/assets/generated/sophia-smg-fire-right-v868.png",
  "/assets/generated/sophia-smg-reload-front-palette-20260915-e585b28d.png",
  "/assets/generated/sophia-smg-reload-back-palette-20260915-ff926a7a.png",
  "/assets/generated/sophia-smg-reload-left-palette-20260915-34f574a2.png",
  "/assets/generated/sophia-smg-reload-right-palette-20260915-81fff2d2.png",
  "/assets/generated/sophia-handgun-reload-muted-back-20260915.png",
  "/assets/generated/sophia-handgun-reload-muted-front-20260915.png",
  "/assets/generated/sophia-handgun-reload-muted-left-20260915.png",
  "/assets/generated/sophia-handgun-reload-muted-right-20260915.png",
  "/assets/generated/handgun-fire-blue-dress-back.png",
  "/assets/generated/handgun-fire-blue-dress-front.png",
  "/assets/generated/handgun-fire-blue-dress-left.png",
  "/assets/generated/handgun-fire-blue-dress-right.png",
  "/assets/generated/handgun-fire-male-bot-back.png",
  "/assets/generated/handgun-fire-male-bot-front.png",
  "/assets/generated/handgun-fire-male-bot-left.png",
  "/assets/generated/handgun-fire-male-bot-right.png",
  "/assets/generated/handgun-fire-white-hood-back.png",
  "/assets/generated/handgun-fire-white-hood-front.png",
  "/assets/generated/handgun-fire-white-hood-left.png",
  "/assets/generated/handgun-fire-white-hood-right.png",
  "/assets/generated/sophia-taser-reload-front-v860-candidate.png",
  "/assets/generated/sophia-taser-reload-back-v860-candidate.png",
  "/assets/generated/sophia-taser-reload-left-v860-candidate.png",
  "/assets/generated/sophia-taser-reload-right-v860-candidate.png",
  "/assets/generated/sophia-sniper-reload-front-candidate.png",
  "/assets/generated/sophia-sniper-reload-back-candidate.png",
  "/assets/generated/sophia-sniper-reload-left-candidate.png",
  "/assets/generated/sophia-sniper-reload-right-candidate.png",
  "/assets/generated/sophia-left-dash-ten.png",
  "/assets/generated/sophia-right-dash-ten.png",
  "/assets/generated/philia-taser-reload-front-v857-candidate.png",
  "/assets/generated/philia-taser-reload-back-v857-candidate.png",
  "/assets/generated/philia-taser-reload-left-v857-candidate.png",
  "/assets/generated/philia-taser-reload-right-v857-candidate.png",
  "/assets/generated/philia-sniper-reload-front-v857-candidate.png",
  "/assets/generated/philia-sniper-reload-back-v857-candidate.png",
  "/assets/generated/philia-sniper-reload-left-v857-candidate.png",
  "/assets/generated/philia-sniper-reload-right-v857-candidate.png",
  "/assets/generated/pair-warning-material-20260915.png",
  "/assets/generated/pair-warning-flow-20260915.png",
  "/assets/generated/philia-left-dash-eight.png",
  "/assets/generated/philia-right-dash-eight.png",
  "/assets/generated/taser-contact-material-20260915.png",
  "/assets/generated/taser-contact-flow-20260915.png",
  "/assets/generated/sophia-assault-reload-front-v853.png",
  "/assets/generated/sophia-assault-reload-back-v853.png",
  "/assets/generated/sophia-assault-reload-left-v853.png",
  "/assets/generated/sophia-assault-reload-right-v853.png",
  "/assets/generated/philia-assault-reload-front-v851.png",
  "/assets/generated/philia-assault-reload-back-v851.png",
  "/assets/generated/philia-assault-reload-left-v851.png",
  "/assets/generated/philia-assault-reload-right-v851.png",
  "/assets/generated/kill-cutin-platinum-frame-v850.png",
  "/assets/generated/mystery-box-registered-material-v848.png",
  "/assets/generated/sophia-smg-reload-front-v847.png",
  "/assets/generated/sophia-smg-reload-back-v847.png",
  "/assets/generated/sophia-smg-reload-left-v847.png",
  "/assets/generated/sophia-smg-reload-right-v847.png",
  "/assets/generated/quantum-electric-material-prepared-v846.png",
  "/assets/generated/quantum-electric-conduction-v846.png",
  "/assets/generated/philia-smg-reload-front-v845.png",
  "/assets/generated/philia-smg-reload-back-v845.png",
  "/assets/generated/philia-smg-reload-left-v845.png",
  "/assets/generated/philia-smg-reload-right-v845.png",
  "/assets/generated/enhance-source-propagation-v844.png",
  "/assets/generated/enhance-hold-material-prepared-v844.png",
  "/assets/generated/sophia-handgun-reload-front-v843.png",
  "/assets/generated/sophia-handgun-reload-back-v843.png",
  "/assets/generated/sophia-handgun-reload-left-v843.png",
  "/assets/generated/sophia-handgun-reload-right-v843.png",
  "/assets/generated/philia-handgun-reload-front-v842.png",
  "/assets/generated/philia-handgun-reload-back-v842.png",
  "/assets/generated/philia-handgun-reload-left-v842.png",
  "/assets/generated/philia-handgun-reload-right-v842.png",
  "/assets/generated/accelerate-time-membrane-v841.png",
  "/assets/generated/accelerate-time-caustics-v841.png",
  "/assets/generated/decelerate-time-membrane-v841.png",
  "/assets/generated/decelerate-time-caustics-v841.png",
  "/assets/generated/credit-initial-metal-reflection-lossless-v840.png",
  "/assets/generated/world-kill-filament-transport-v839.png",
  "/assets/generated/timekeeper-local-caustics-v838.png",
  "/assets/generated/human-kill-cutin-white-hood-five-phase-v837.png",
  "/assets/generated/human-kill-cutin-blue-dress-five-phase-v837.png",
  "/assets/generated/gravity-storm-material-packed-v836.png",
  "/assets/generated/gravity-safeeye-pressure-packed-v836.png",
  "/assets/generated/gravity-safeeye-residue-packed-v836.png",
  "/assets/generated/heart-transfer-pressure-v835.png",
  "/assets/generated/bot-kill-cutin-five-phase-v832.png",
  "/assets/generated/poison-marker-membrane-v833.png",
  "/assets/generated/poison-material-transport-v832.png",
  "/assets/generated/benefit-credit-gold-coin-v831.png",
  "/assets/generated/benefit-credit-gold-coin-sheen-atlas-v831.png",
  "/assets/generated/water-material-transport-v831.png",
  "/assets/generated/fire-material-transport-v830.png",
  "/assets/generated/aroma-scent-transport-atlas-v829.png",
  "/assets/generated/barrier-closed-shell-v827.png",
  "/assets/generated/antidote-purification-material-v824.png",
  "/assets/generated/philia-front-fire-v824.png",
  "/assets/generated/philia-left-fire-v824.png",
  "/assets/generated/philia-right-fire-v824.png",
  "/assets/generated/philia-back-fire-v824.png",
  "/assets/generated/sophia-front-fire-v824.png",
  "/assets/generated/sophia-left-fire-v824.png",
  "/assets/generated/sophia-right-fire-v824.png",
  "/assets/generated/sophia-back-fire-v824.png",
  "/assets/generated/renki-normal-material-v824.png",
  "/assets/generated/renki-tenfold-material-v824.png",
  "/assets/generated/philia-front-dodge-v823.png",
  "/assets/generated/philia-left-dodge-v823.png",
  "/assets/generated/philia-right-dodge-v823.png",
  "/assets/generated/philia-back-dodge-v823.png",
  "/assets/generated/sophia-front-dodge-v823.png",
  "/assets/generated/sophia-left-dodge-v823.png",
  "/assets/generated/sophia-right-dodge-v823.png",
  "/assets/generated/sophia-back-dodge-v823.png",
  "/assets/generated/philia-front-heal-v822.png",
  "/assets/generated/philia-left-heal-v822.png",
  "/assets/generated/philia-right-heal-v822.png",
  "/assets/generated/philia-back-heal-v822.png",
  "/assets/generated/sophia-front-heal-v822.png",
  "/assets/generated/sophia-left-heal-v822.png",
  "/assets/generated/sophia-right-heal-v822.png",
  "/assets/generated/sophia-back-heal-v822.png",
  "/assets/generated/sophia-front-throw-v821.png",
  "/assets/generated/sophia-left-throw-v821.png",
  "/assets/generated/sophia-right-throw-v821.png",
  "/assets/generated/sophia-back-throw-v821.png",
  "/assets/generated/philia-front-throw-v820.png",
  "/assets/generated/philia-left-throw-v820.png",
  "/assets/generated/philia-right-throw-v820.png",
  "/assets/generated/philia-back-throw-v820.png",
  "/assets/generated/benefit-acceleration-stream-v819.png",
  "/assets/generated/benefit-luck-boost-caustic-v819.png",
  "/assets/generated/benefit-status-recovery-cleansing-v819.png",
  "/assets/generated/benefit-cooldown-reduction-release-v819.png",
  "/assets/generated/benefit-credits-transfer-v819.png",
  "/assets/generated/benefit-heal-membrane-v818.png",
  "/assets/generated/benefit-mana-condensation-v818.png",
  "/assets/generated/benefit-overheal-overflow-v818.png",
  "/assets/generated/benefit-stamina-flow-v817.png",
  "/assets/generated/sophia-front-ninjutsu-focus-v814.png",
  "/assets/generated/sophia-left-ninjutsu-focus-v814.png",
  "/assets/generated/sophia-right-ninjutsu-focus-v814.png",
  "/assets/generated/sophia-back-ninjutsu-focus-v814.png",
  "/assets/generated/philia-front-ninjutsu-focus-v813.png",
  "/assets/generated/philia-left-ninjutsu-focus-v813.png",
  "/assets/generated/philia-right-ninjutsu-focus-v813.png",
  "/assets/generated/philia-back-ninjutsu-focus-v813.png",
  "/assets/generated/sophia-front-antidote-v810.png",
  "/assets/generated/sophia-left-antidote-v810.png",
  "/assets/generated/sophia-right-antidote-v810.png",
  "/assets/generated/sophia-back-antidote-v810.png",
  "/assets/generated/philia-left-antidote-v809.png",
  "/assets/generated/philia-right-antidote-v809.png",
  "/assets/generated/philia-back-antidote-v809.png",
  "/assets/generated/task-download-digital-v808.png",
  "/assets/generated/task-upload-digital-v808.png",
  "/assets/generated/philia-left-dash-v807.png",
  "/assets/generated/philia-right-dash-v807.png",
  "/assets/generated/sophia-back-water-v803.png",
  "/assets/generated/bot-kill-cutin-frame-0-prepared-v802.png",
  "/assets/generated/bot-kill-cutin-frame-1-prepared-v802.png",
  "/assets/generated/bot-kill-cutin-frame-2-prepared-v802.png",
  "/assets/generated/bot-kill-cutin-frame-3-prepared-v802.png",
  "/assets/generated/sophia-left-water-v800.png",
  "/assets/generated/white-hood-kill-cutin-prepared-v801.png",
  "/assets/generated/blue-dress-kill-cutin-prepared-v801.png",
  "/assets/generated/world-kill-residual-v800.png",
  "/assets/generated/sophia-right-water-v799.png",
  "/assets/generated/philia-back-water-v798.png",
  "/assets/generated/philia-left-water-v796.png",
  "/assets/generated/male-back-dash-v795.png",
  "/assets/generated/male-back-slow-v794.png",
  "/assets/generated/male-back-walk-v793.png",
  "/assets/generated/male-right-dash-v792.png",
  "/assets/generated/male-right-slow-v791.png",
  "/assets/generated/male-right-walk-v790.png",
  "/assets/generated/male-left-dash-v789.png",
  "/assets/generated/male-left-slow-v788.png",
  "/assets/generated/philia-left-dash-v787.png",
  "/assets/generated/sophia-front-dash-v786.png",
  "/assets/generated/male-left-walk-v785.png",
  "/assets/generated/male-front-slow-v784.png",
  "/assets/generated/male-front-dash-v784.png",
  "/assets/generated/male-front-walk-v783.png",
  "/assets/generated/philia-back-dash-v782.png",
  "/assets/generated/philia-right-dash-v781.png",
  "/assets/generated/philia-right-water-v780.png",
  "/assets/generated/philia-back-slow-v777.png",
  "/assets/generated/philia-front-seawater-v777.png",
  "/assets/generated/philia-right-slow-v776.png",
  "/assets/generated/philia-left-slow-v775.png",
  "/assets/generated/sophia-back-dash-v771.png",
  "/assets/generated/sophia-right-dash-v770.png",
  "/assets/generated/sophia-left-dash-v769.png",
  "/assets/generated/sophia-drink-four-v768.png",
  "/assets/generated/sophia-back-slow-v767.png",
  "/assets/generated/sophia-right-slow-v766.png",
  "/assets/generated/sophia-left-slow-v765.png",
  "/assets/generated/philia-front-antidote-v763.png",
  "/assets/generated/sophia-front-slow-v762.png",
  "/assets/generated/philia-front-slow-v761.png",
  "/assets/generated/philia-front-dash-v761.png",
  "/assets/generated/philia-back-nine-v760.png",
  "/assets/generated/philia-right-nine-v759.png",
  "/",
  "/index.html",
  "/styles.css",
  "/economy-catalog-v468.js",
  "/app.js",
  "/webgpu-acquisition.js",
  "/webgpu-body-benefits.js",
  "/webgpu-field-static.js",
  "/webgpu-frame-core.js",
  "/webgpu-primitives.js",
  "/webgpu-compositing.js",
  "/webgpu-gravity-zones.js",
  "/webgpu-hazard-fields.js",
  "/webgpu-renderer.js",
  "/webgpu-viewport.js",
  "/webgpu-text.js",
  "/webgpu-main-text-resources.js",
  "/webgpu-expanded-map.js",
  "/webgpu-expanded-runtime.js",
  "/webgpu-field-pass.js",
  "/webgpu-medical-environment-e.js",
  "/webgpu-medical-object-e.js",
  "/webgpu-medical-cabinet-e.js",
  "/webgpu-medical-footbath-use-e.js",
  "/webgpu-medical-upload-console-e.js",
  "/webgpu-medical-fixture-e.js",
  "/webgpu-effect-shapes.js",
  "/webgpu-stations.js",
  "/webgpu-map-object-labels.js",
  "/webgpu-mystery-boxes.js",
  "/webgpu-mystery-box-reveal-e.js",
  "/webgpu-alchemy-objects.js",
  "/webgpu-ground-items.js",
  "/webgpu-facility-effects.js",
  "/webgpu-bodies.js",
  "/webgpu-world-sound-effects.js",
  "/webgpu-throw-preview.js",
  "/webgpu-preparation-summons.js",
  "/webgpu-player-nameplates.js",
  "/webgpu-player-sprite.js",
  "/webgpu-head-markers.js",
  "/webgpu-head-marker-materials.js",
  "/webgpu-gunner-aim.js",
  "/webgpu-kill-camera-markers.js",
  "/webgpu-hit-effects.js",
  "/webgpu-gravity-impacts.js",
  "/webgpu-grenade-impact.js",
  "/webgpu-body-benefit-pass.js",
  "/webgpu-body-benefit-extra.js",
  "/webgpu-status-tempo-e.js",
  "/webgpu-barrier-e.js",
  "/webgpu-bust-e.js",
  "/webgpu-dodge-e.js",
  "/webgpu-renki-e.js",
  "/webgpu-idea-e.js",
  "/webgpu-alchemy-e.js",
  "/webgpu-hacker-root-e.js",
  "/webgpu-hacker-status-recovery-e.js",
  "/webgpu-flora-e.js",
  "/webgpu-heal-astra-prototype.js",
  "/webgpu-heal-astra-sfx.js",
  "/webgpu-sunbeam-e.js",
  "/webgpu-sunbeam-live-overlay.js",
  "/webgpu-sunbeam-e-sfx.js",
  "/webgpu-sunbeam-cue-adapter.js",
  "/webgpu-gravity-field-e.js",
  "/webgpu-rigid-item-impact-e.js",
  "/webgpu-bottle-shards-e.js",
  "/webgpu-archive-cabinet-e.js",
  "/webgpu-cable-spool-e.js",
  "/webgpu-fire-activation.js",
  "/webgpu-attack-targets.js",
  "/webgpu-task-indicators.js",
  "/webgpu-hud.js",
  "/webgpu-minimap.js",
  "/webgpu-mode-banner.js",
  "/webgpu-kill-residual-bloom.js",
  "/webgpu-kill-animation.js",
  "/webgpu-sensory-blackout.js",
  "/webgpu-marker-explanation.js",
  "/webgpu-main-scene.js",
  "/webgpu-main-pass-registry.js",
  "/webgpu-corridor-a01-e.js",
  "/webgpu-corridor-object-use-e.js",
  "/webgpu-room-object-use-e.js",
  "/webgpu-main-runtime.js",
  "/webgpu-main-frame-scheduler.js",
  "/webgpu-emp-effect.js",
  "/webgpu-special-ammo-effect.js",
  "/webgpu-common-action-body-e.js",
  "/webgpu-e-event-sfx.js",
  "/webgpu-combat-e-sfx.js",
  "/webgpu-defense-movement-e-sfx.js",
  "/webgpu-e-cue-player.js",
  "/object-space-collision.js",
  "/grenade-impact-sfx.js",
  "/game-runtime.js",
  "/game-engine.js",
  "/offline-runtime.js",
  "/offline-server-worker.js",
  "/offline-server-main.js",
  "/config.js",
  "/manifest.webmanifest",
  "/icon.png",
  "/assets/title-hero-v466.png",
  "/assets/site-thumbnail-v497.png",
  "/assets/generated/tactics-novel-briefing-room-v466.png",
  "/assets/generated/tactics-novel-digest-poster-v654.png",
  "/assets/generated/mystery-box-open-v655.png",
  "/assets/generated/tactics-manga-sparkle-v466.png",
  "/assets/generated/tactics-manga-idea-v466.png",
  "/assets/generated/tactics-manga-cheer-v466.png",
  "/assets/generated/tactics-manga-note-v466.png",
  "/assets/generated/throw-landing-preview-v384.png",
  "/assets/generated/clairvoyance-throw-ate-v412.png",
  "/assets/generated/gunner-weapon-icons-v422.png",
  "/assets/generated/gunner-weapon-icons-v422.webp",
  "/assets/generated/gunner-special-ammo-weak-v455.png",
  "/assets/generated/gunner-special-ammo-penetrate-v455.png",
  "/assets/generated/gunner-special-ammo-shock-v455.png",
  "/assets/generated/ui-panel-surface.webp",
  "/assets/generated/ui-control-surface.webp",
  "/assets/generated/ui-lobby-signal-surface.webp",
  "/assets/generated/ui-ability-command-surface.webp",
  "/assets/generated/ui-status-effect-surface.webp",
  "/assets/generated/ui-context-alert-surface.webp",
  "/assets/generated/operator-fighter-ate-v391.png",
  "/assets/generated/operator-gravity-ate-v391.png",
  "/assets/generated/operator-flora-ate-v391.png",
  "/assets/generated/operator-quantum-control-ate-v391.png",
  "/assets/generated/operator-gunner-ate-v391.png",
  "/assets/generated/operator-hacker-ate-v391.png",
  "/assets/generated/operator-assassin-ate-v510.png",
  "/assets/generated/natural-recovery-ate-v510.png",
  "/assets/generated/gbo-overdrive-ate-v513.png",
  "/assets/generated/shop-activation-ate-v581.png",
  "/assets/generated/status-preparation-barrier-ate-v392.png",
  "/assets/generated/fighter-energy-charge-ate-v404.png",
  "/assets/generated/item-orichalcum-sword-v453.png",
  "/assets/generated/instant-iai-abstract-v451.png",
  "/assets/generated/item-iai-v449.png",
  "/assets/generated/fighter-energy-release-ate-v404.png",
  "/assets/generated/fighter-energy-impact-ate-v404.png",
  "/assets/generated/fighter-shockwave-ate-v393.png",
  "/assets/generated/white-hood-kill-cutin-v404.png",
  "/assets/generated/luminous-meeting-effect-v311.png",
  "/assets/generated/fighter-slash-effect.webp",
  "/assets/generated/effect-transfer-out.webp",
  "/assets/generated/effect-transfer-in.webp",
  "/assets/generated/effect-bottle-shards.webp",
  "/assets/generated/field-aurelia-corridor-objects-v318.webp",
  "/assets/generated/effect-footbath-hidden-spring-godray-v359.png",
  "/assets/generated/object-effect-stamina-v327.png",
  "/assets/generated/object-effect-credits-v438.png",
  "/assets/generated/skin-blue-dress-walk-front-v483.png",
  "/assets/generated/skin-blue-dress-walk-left-v483.png",
  "/assets/generated/skin-blue-dress-walk-right-v483.png",
  "/assets/generated/skin-blue-dress-walk-back-v483.png",
  "/assets/generated/skin-white-hood-walk-front-v483.png",
  "/assets/generated/skin-white-hood-walk-left-v483.png",
  "/assets/generated/skin-white-hood-walk-right-v483.png",
  "/assets/generated/skin-white-hood-walk-back-v483.png",
  "/assets/generated/object-effect-mana-v327.png",
  "/assets/generated/object-effect-cooldown-reduction-v327.png",
  "/assets/generated/object-effect-status-recovery-v327.png",
  "/assets/generated/object-effect-acceleration-v327.png",
  "/assets/generated/object-effect-luck-boost-v327.png",
  "/assets/generated/object-effect-overheal-v327.png",
  "/assets/generated/object-effect-relaxation-v327.png",
  "/assets/generated/object-effect-herbal-recovery-v327.png",
  "/assets/generated/object-effect-healthy-meal-v327.png",
  "/assets/generated/object-effect-mineral-water-v327.png",
  "/assets/generated/object-effect-heal-v327.png",
  "/assets/generated/object-effect-full-recovery-v327.png",
  "/assets/generated/object-effect-decoy-v327.png",
  "/assets/generated/gravity-storm-safe-eye-v320.png",
  "/assets/generated/status-marker-acceleration-v376.png",
  "/assets/generated/status-levitation-v375.png",
  "/assets/generated/hover-sprint-jet-exhaust-v719.png",
  "/assets/generated/philia-left-nine-v756.png",
  "/assets/generated/sophia-back-five-v755.png",
  "/assets/generated/sophia-left-five-v754.png",
  "/assets/generated/sophia-right-five-v754.png",
  "/assets/generated/sophia-front-five-v753.png",
  "/assets/generated/philia-front-nine-v752.png",
  "/assets/generated/philia-drink-four-v752.png",
  "/assets/generated/benefit-stamina-v740.png",
  "/assets/generated/benefit-heal-v740.png",
  "/assets/generated/benefit-mana-v740.png",
  "/assets/generated/benefit-overheal-v740.png",
  "/assets/generated/benefit-acceleration-v740.png",
  "/assets/generated/benefit-luck-boost-v740.png",
  "/assets/generated/benefit-status-recovery-v740.png",
  "/assets/generated/benefit-cooldown-reduction-v740.png",
  "/assets/generated/benefit-credits-v740.png",
  "/assets/generated/enhance-hold-marker-v737.png",
  "/assets/generated/renki-coalescence-v736.png",
  "/assets/generated/renki-tenfold-release-v736.png",
  "/assets/generated/preparation-summon-circle-v726.png",
  "/assets/generated/status-hp-reduction-v375.png",
  "/assets/generated/status-mana-gpu-ate-v402.png",
  "/assets/generated/hacker-root-matrix-v497.png",
  "/assets/generated/gravity-time-keeper-v497.png",
  "/assets/generated/fire-jutsu-field.webp",
  "/assets/generated/substitution-field.webp",
  "/assets/generated/limit-break-field-v307.png",
  "/assets/generated/limit-break-release-v309.png",
  "/assets/generated/flora-self-heal-v336.png",
  "/assets/generated/flora-invisible-ate-v527.png",
  "/assets/generated/action-vibe-coding-v311.png",
  "/assets/generated/item-hsg-v486.png",
  "/assets/generated/gunner-rpg-v311.png",
  "/assets/generated/gunner-missile-v311.png",
  "/assets/generated/gunner-rpg.webp",
  "/assets/generated/gunner-missile.webp",
  "/assets/generated/effect-quantum-nuclear-v311.png",
  "/assets/generated/quantum-nuclear-fusion-ate-v522.png",
  "/assets/generated/quantum-electric-discharge-v554.png",
  "/assets/generated/emp-resonance-v398.png",
  "/assets/generated/emp-cancel-v311.png",

  "/assets/generated/heart-transfer-fist-glow-ate-v468.png",
  "/assets/generated/action-effect-task-v311.png",
  "/assets/generated/action-effect-stand-v311.png",
  "/assets/generated/action-effect-dodge-v311.png",
  "/assets/generated/action-effect-rest-v311.png",
  "/assets/generated/action-effect-teleport-v311.png",
  "/assets/generated/action-effect-warp-v311.png",
  "/assets/generated/action-effect-drone-v311.png",
  "/assets/generated/action-effect-aim-v311.png",
  "/assets/generated/action-effect-sabotage-v311.png",
  "/assets/generated/action-effect-vent-v311.png",
  "/assets/generated/action-effect-vending-v311.png",
  "/assets/generated/philosophy-effect-renki-v311.png",
  "/assets/generated/philosophy-effect-desire-v311.png",
  "/assets/generated/philosophy-effect-grit-v311.png",
  "/assets/generated/philosophy-effect-reason-v311.png",
  "/assets/generated/philosophy-effect-stand-v311.png",
  "/assets/generated/philosophy-effect-push-v311.png",
  "/assets/generated/philosophy-effect-truth-v311.png",
  "/assets/generated/philosophy-effect-beauty-v311.png",
  "/assets/generated/philosophy-effect-good-v311.png",
  "/assets/generated/philosophy-effect-ascension-v311.png",
  "/assets/generated/philosophy-effect-mystery-v311.png",
  "/assets/generated/philosophy-effect-emp-v311.png",
  "/assets/generated/alchemy-effect-renki-v311.png",
  "/assets/generated/alchemy-effect-desire-v311.png",
  "/assets/generated/alchemy-effect-rational-free-v311.png",
  "/assets/generated/alchemy-effect-generate-v311.png",
  "/assets/generated/alchemy-effect-credits-v311.png",
  "/assets/generated/alchemy-effect-stamina-v311.png",
  "/assets/generated/alchemy-effect-heal-v311.png",
  "/assets/generated/alchemy-effect-fire-v311.png",
  "/assets/generated/alchemy-effect-substitution-v311.png",
  "/assets/generated/item-teleport-map-scroll-v495.png",
  "/assets/generated/teleport-map-scroll-acquisition-ate-v495.png",
  "/assets/generated/alchemy-effect-grit-v311.png",
  "/assets/generated/alchemy-effect-reason-v311.png",
  "/assets/generated/gunner-break-handgun-v311.png",
  "/assets/generated/gunner-break-smg-v311.png",
  "/assets/generated/gunner-break-assault-v311.png",
  "/assets/generated/gunner-break-sniper-v311.png",
  "/assets/generated/gunner-break-taser-v311.png",
  "/assets/generated/gunner-fire-handgun-v311.png",
  "/assets/generated/gunner-fire-smg-v311.png",
  "/assets/generated/gunner-fire-assault-v311.png",
  "/assets/generated/gunner-fire-sniper-v311.png",
  "/assets/generated/gunner-fire-taser-v311.png",
  "/assets/generated/drone-altitude-low-v311.png",
  "/assets/generated/drone-altitude-middle-v311.png",
  "/assets/generated/drone-altitude-high-v311.png",
  "/assets/generated/physical-motion-blue-dress-attack-v483.png",
  "/assets/generated/physical-motion-blue-dress-cast-v483.png",
  "/assets/generated/physical-motion-blue-dress-evade-v483.png",
  "/assets/generated/physical-motion-blue-dress-focus-v483.png",
  "/assets/generated/physical-motion-blue-dress-heal-v483.png",
  "/assets/generated/physical-motion-blue-dress-heart-transfer-v483.png",
  "/assets/generated/physical-motion-blue-dress-interact-v483.png",
  "/assets/generated/physical-motion-blue-dress-power-v483.png",
  "/assets/generated/physical-motion-blue-dress-reload-v483.png",
  "/assets/generated/physical-motion-blue-dress-rest-v483.png",
  "/assets/generated/physical-motion-blue-dress-shoot-v483.png",
  "/assets/generated/physical-motion-blue-dress-slash-v483.png",
  "/assets/generated/physical-motion-blue-dress-throw-v483.png",
  "/assets/generated/physical-motion-white-hood-attack-v483.png",
  "/assets/generated/physical-motion-white-hood-cast-v483.png",
  "/assets/generated/physical-motion-white-hood-evade-v483.png",
  "/assets/generated/physical-motion-white-hood-focus-v483.png",
  "/assets/generated/physical-motion-white-hood-heal-v483.png",
  "/assets/generated/physical-motion-white-hood-heart-transfer-v483.png",
  "/assets/generated/physical-motion-white-hood-interact-v483.png",
  "/assets/generated/physical-motion-white-hood-power-v483.png",
  "/assets/generated/physical-motion-white-hood-reload-v483.png",
  "/assets/generated/physical-motion-white-hood-rest-v483.png",
  "/assets/generated/physical-motion-white-hood-shoot-v483.png",
  "/assets/generated/physical-motion-white-hood-slash-v483.png",
  "/assets/generated/physical-motion-white-hood-throw-v483.png",
  "/assets/generated/physical-motion-male-bot-attack-v465.png",
  "/assets/generated/physical-motion-male-bot-cast-v465.png",
  "/assets/generated/physical-motion-male-bot-evade-v465.png",
  "/assets/generated/physical-motion-male-bot-focus-v465.png",
  "/assets/generated/physical-motion-male-bot-heal-v465.png",
  "/assets/generated/physical-motion-male-bot-interact-v465.png",
  "/assets/generated/physical-motion-male-bot-power-v465.png",
  "/assets/generated/physical-motion-male-bot-heart-transfer-v468.png",
  "/assets/generated/physical-motion-male-bot-reload-v465.png",
  "/assets/generated/physical-motion-male-bot-rest-v465.png",
  "/assets/generated/physical-motion-male-bot-shoot-v465.png",
  "/assets/generated/physical-motion-male-bot-slash-v465.png",
  "/assets/generated/physical-motion-male-bot-throw-v465.png",
  "/assets/generated/weapon-motion-white-hood-handgun-fire-v483.png",
  "/assets/generated/weapon-motion-white-hood-handgun-switch-v483.png",
  "/assets/generated/weapon-motion-white-hood-handgun-reload-v483.png",
  "/assets/generated/weapon-motion-white-hood-smg-fire-v483.png",
  "/assets/generated/weapon-motion-white-hood-smg-switch-v483.png",
  "/assets/generated/weapon-motion-white-hood-smg-reload-v483.png",
  "/assets/generated/weapon-motion-white-hood-assault-fire-v483.png",
  "/assets/generated/weapon-motion-white-hood-assault-switch-v483.png",
  "/assets/generated/weapon-motion-white-hood-assault-reload-v483.png",
  "/assets/generated/weapon-motion-white-hood-sniper-fire-v483.png",
  "/assets/generated/weapon-motion-white-hood-sniper-switch-v483.png",
  "/assets/generated/weapon-motion-white-hood-sniper-reload-v483.png",
  "/assets/generated/weapon-motion-white-hood-taser-fire-v483.png",
  "/assets/generated/weapon-motion-white-hood-taser-switch-v483.png",
  "/assets/generated/weapon-motion-white-hood-taser-reload-v483.png",
  "/assets/generated/weapon-motion-blue-dress-handgun-fire-v483.png",
  "/assets/generated/weapon-motion-blue-dress-handgun-switch-v483.png",
  "/assets/generated/weapon-motion-blue-dress-handgun-reload-v483.png",
  "/assets/generated/weapon-motion-blue-dress-smg-fire-v483.png",
  "/assets/generated/weapon-motion-blue-dress-smg-switch-v483.png",
  "/assets/generated/weapon-motion-blue-dress-smg-reload-v483.png",
  "/assets/generated/weapon-motion-blue-dress-assault-fire-v483.png",
  "/assets/generated/weapon-motion-blue-dress-assault-switch-v483.png",
  "/assets/generated/weapon-motion-blue-dress-assault-reload-v483.png",
  "/assets/generated/weapon-motion-blue-dress-sniper-fire-v483.png",
  "/assets/generated/weapon-motion-blue-dress-sniper-switch-v483.png",
  "/assets/generated/weapon-motion-blue-dress-sniper-reload-v483.png",
  "/assets/generated/weapon-motion-blue-dress-taser-fire-v483.png",
  "/assets/generated/weapon-motion-blue-dress-taser-switch-v483.png",
  "/assets/generated/weapon-motion-blue-dress-taser-reload-v483.png",
  "/assets/generated/weapon-motion-male-bot-handgun-v313.webp",
  "/assets/generated/weapon-motion-male-bot-smg-v313.webp",
  "/assets/generated/weapon-motion-male-bot-assault-v313.webp",
  "/assets/generated/weapon-motion-male-bot-sniper-v313.webp",
  "/assets/generated/weapon-motion-male-bot-taser-v313.webp",
  "/assets/generated/item-gold-ingot-v436.png",
  "/assets/generated/effect-gold-transmutation-v436.png",
  "/assets/generated/fighter-push-double-milestone-v435.png",
  "/assets/generated/fighter-destruction-slash-milestone-v435.png",
  "/assets/generated/item-mercury.webp",
  "/assets/generated/item-lead.webp",
  "/assets/generated/item-uranium.webp",
  "/assets/generated/item-plutonium.webp",
  "/assets/generated/item-mineral-water.webp",
  "/assets/generated/item-seawater-v522.png",
  "/assets/generated/item-antidote.webp",
  "/assets/generated/item-heal.webp",
  "/assets/generated/item-stamina-cell.webp",
  "/assets/generated/mana-potion.webp",
  "/assets/generated/credit-crates.png",
  "/assets/generated/item-molotov.webp",
  "/assets/generated/item-ice.webp",
  "/assets/generated/item-heated-water.webp",
  "/assets/generated/push-stand-firm-break-v311.png",
  "/assets/generated/resolve-point.webp",
  "/assets/generated/mystery-box-christmas-v650.png",
  "/assets/generated/alchemy-excalibur.webp",
  "/assets/generated/hack-credits-delete.webp",
  "/assets/generated/hack-credits-duplicate.webp",
  "/assets/generated/hack-items-delete.webp",
  "/assets/generated/hack-items-duplicate.webp",
  "/assets/generated/hack-hp-delete.webp",
  "/assets/generated/hack-hp-duplicate.webp",
  "/assets/generated/hack-mana-delete.webp",
  "/assets/generated/hack-mana-duplicate.webp",
  "/assets/generated/alchemy-railgun-field-effect.webp",
  "/assets/generated/alchemy-particle-cannon-field-effect.webp",
  "/assets/generated/human-transmutation-sd-silhouette-v407.png",
  "/assets/generated/gunner-weapons-atlas.webp",
  "/assets/generated/gunner-taser.webp",
  "/assets/generated/ui-result-surface.webp",
  "/assets/facility-props.webp",
  "/assets/generated/alchemy-particle-cannon.webp",
  "/assets/generated/alchemy-railgun.webp",
  "/assets/generated/attacker-ally-marker.webp",
  "/assets/generated/effect-hazard-poison.webp",
  "/assets/generated/effect-hazard-water.webp",
  "/assets/generated/effect-quantum-cold.webp",
  "/assets/generated/effect-quantum-hot.webp",
  "/assets/generated/exile-clone.webp",
  "/assets/generated/gravity-storm.webp",
  "/assets/generated/fire-ability-v575.png",
  "/assets/generated/skin-blue-dress-back.webp",
  "/assets/generated/skin-blue-dress-front.webp",
  "/assets/generated/skin-blue-dress-kill-cutin.webp",
  "/assets/generated/skin-blue-dress-left.webp",
  "/assets/generated/skin-blue-dress-master-chibi-v3.webp",
  "/assets/generated/skin-blue-dress-right.webp",
  "/assets/generated/status-push.webp",
  "/assets/generated/status-stand-firm.webp",
  "/assets/generated/status-substitution.webp",
  "/assets/generated/tactical-systems-atlas.webp",
  "/assets/generated/ui-action-surface.webp",
  "/assets/generated/ui-battle-hud-surface.webp",
  "/assets/generated/ui-hacker-surface.webp",
  "/assets/generated/ui-lobby-surface.webp",
  "/assets/generated/ui-map-surface.webp",
  "/assets/generated/ui-meeting-surface.webp",
  "/assets/generated/ui-operator-surface.webp",
  "/assets/generated/ui-tablet-surface.webp",
  "/assets/generated/ui-tactics-surface.webp",
  "/assets/generated/ui-vending-surface.webp",
  "/assets/kill-cutin-60.webp",
  "/assets/operators-walk.webp",
  "/assets/operators.webp",
  "/assets/player-master-b.webp",
  "/assets/player-walk-60.webp",
  "/assets/room-props.webp",
  "/assets/tutorials/poster-basics.webp",
  "/assets/tutorials/poster-combat.webp",
  "/assets/tutorials/poster-intel.webp",
  "/assets/tutorials/poster-movement.webp",
  "/assets/sfx/alert.wav",
  "/assets/sfx/dash-step-1.wav",
  "/assets/sfx/dash-step-2.wav",
  "/assets/sfx/death.wav",
  "/assets/sfx/dodge.wav",
  "/assets/sfx/drone.wav",
  "/assets/sfx/emp.wav",
  "/assets/sfx/fighter-counter.wav",
  "/assets/sfx/fire-jutsu.wav",
  "/assets/sfx/footstep-1.wav",
  "/assets/sfx/footstep-2.wav",
  "/assets/sfx/gun-assault.wav",
  "/assets/sfx/gun-handgun.wav",
  "/assets/sfx/gun-smg.wav",
  "/assets/sfx/gun-sniper.wav",
  "/assets/sfx/impact.wav",
  "/assets/sfx/kill.wav",
  "/assets/sfx/lose.wav",
  "/assets/sfx/meeting.wav",
  "/assets/sfx/object.wav",
  "/assets/sfx/ranking.wav",
  "/assets/sfx/round.wav",
  "/assets/sfx/start.wav",
  "/assets/sfx/substitution.wav",
  "/assets/sfx/task.wav",
  "/assets/sfx/teleport.wav",
  "/assets/sfx/ui-click.wav",
  "/assets/sfx/ui-confirm.wav",
  "/assets/sfx/win.wav"
];

// Installation must make the shell and generated-offline authority usable,
// not download the complete visual/audio catalogue twice. All other listed
// assets remain network-first and are cached once under their release-scoped
// canonical key when gameplay first needs them.
const BOOT_CRITICAL_ASSETS = new Set([
  "/assets/generated/webgpu-text/atlas.json",
  "/assets/generated/webgpu-text/atlas-00.png",
  "/assets/generated/webgpu-text/atlas-01.png",
  "/assets/generated/webgpu-text/atlas-02.png",
  "/assets/generated/webgpu-text/atlas-03.png",
  "/assets/generated/webgpu-text/atlas-04.png",
  "/",
  "/index.html",
  "/styles.css",
  "/economy-catalog-v468.js",
  "/app.js",
  "/webgpu-acquisition.js",
  "/webgpu-body-benefits.js",
  "/webgpu-field-static.js",
  "/webgpu-frame-core.js",
  "/webgpu-primitives.js",
  "/webgpu-compositing.js",
  "/webgpu-gravity-zones.js",
  "/webgpu-hazard-fields.js",
  "/webgpu-renderer.js",
  "/webgpu-viewport.js",
  "/webgpu-text.js",
  "/webgpu-main-text-resources.js",
  "/webgpu-expanded-map.js",
  "/webgpu-expanded-runtime.js",
  "/webgpu-field-pass.js",
  "/webgpu-medical-environment-e.js",
  "/webgpu-medical-object-e.js",
  "/webgpu-medical-cabinet-e.js",
  "/webgpu-medical-footbath-use-e.js",
  "/webgpu-medical-upload-console-e.js",
  "/webgpu-medical-fixture-e.js",
  "/webgpu-effect-shapes.js",
  "/webgpu-stations.js",
  "/webgpu-map-object-labels.js",
  "/webgpu-mystery-boxes.js",
  "/webgpu-mystery-box-reveal-e.js",
  "/webgpu-alchemy-objects.js",
  "/webgpu-ground-items.js",
  "/webgpu-facility-effects.js",
  "/webgpu-bodies.js",
  "/webgpu-world-sound-effects.js",
  "/webgpu-throw-preview.js",
  "/webgpu-preparation-summons.js",
  "/webgpu-player-nameplates.js",
  "/webgpu-player-sprite.js",
  "/webgpu-head-markers.js",
  "/webgpu-head-marker-materials.js",
  "/webgpu-gunner-aim.js",
  "/webgpu-kill-camera-markers.js",
  "/webgpu-hit-effects.js",
  "/webgpu-gravity-impacts.js",
  "/webgpu-grenade-impact.js",
  "/webgpu-body-benefit-pass.js",
  "/webgpu-body-benefit-extra.js",
  "/webgpu-status-tempo-e.js",
  "/webgpu-barrier-e.js",
  "/webgpu-bust-e.js",
  "/webgpu-dodge-e.js",
  "/webgpu-renki-e.js",
  "/webgpu-idea-e.js",
  "/webgpu-alchemy-e.js",
  "/webgpu-hacker-root-e.js",
  "/webgpu-hacker-status-recovery-e.js",
  "/webgpu-flora-e.js",
  "/webgpu-heal-astra-prototype.js",
  "/webgpu-heal-astra-sfx.js",
  "/webgpu-sunbeam-e.js",
  "/webgpu-sunbeam-live-overlay.js",
  "/webgpu-sunbeam-e-sfx.js",
  "/webgpu-sunbeam-cue-adapter.js",
  "/webgpu-gravity-field-e.js",
  "/webgpu-rigid-item-impact-e.js",
  "/webgpu-bottle-shards-e.js",
  "/webgpu-archive-cabinet-e.js",
  "/webgpu-cable-spool-e.js",
  "/webgpu-fire-activation.js",
  "/webgpu-attack-targets.js",
  "/webgpu-task-indicators.js",
  "/webgpu-hud.js",
  "/webgpu-minimap.js",
  "/webgpu-mode-banner.js",
  "/webgpu-kill-residual-bloom.js",
  "/webgpu-kill-animation.js",
  "/webgpu-sensory-blackout.js",
  "/webgpu-marker-explanation.js",
  "/webgpu-main-scene.js",
  "/webgpu-main-pass-registry.js",
  "/webgpu-corridor-a01-e.js",
  "/webgpu-corridor-object-use-e.js",
  "/webgpu-room-object-use-e.js",
  "/webgpu-main-runtime.js",
  "/webgpu-main-frame-scheduler.js",
  "/webgpu-emp-effect.js",
  "/webgpu-special-ammo-effect.js",
  "/webgpu-common-action-body-e.js",
  "/webgpu-e-event-sfx.js",
  "/webgpu-combat-e-sfx.js",
  "/webgpu-defense-movement-e-sfx.js",
  "/webgpu-e-cue-player.js",
  "/object-space-collision.js",
  "/grenade-impact-sfx.js",
  "/game-runtime.js",
  "/game-engine.js",
  "/offline-runtime.js",
  "/offline-server-worker.js",
  "/offline-server-main.js",
  "/config.js",
  "/manifest.webmanifest",
  "/icon.png",
  "/assets/title-hero-v466.png"
]);
const PRECACHE_CONCURRENCY = 4;
const RUNTIME_CACHE_MAX_ENTRIES = 128;
let runtimeCacheMutation = Promise.resolve();

function installCacheKey(asset) {
  if (asset === "/" || asset === "/index.html") return asset;
  const versioned = new URL(asset, self.location.origin);
  versioned.searchParams.set("v", RUNTIME_RELEASE);
  return `${versioned.pathname}${versioned.search}`;
}

async function cacheBootCriticalAssets(cache) {
  const assets = STATIC_ASSETS.filter((asset) => BOOT_CRITICAL_ASSETS.has(asset)).map(installCacheKey);
  let cursor = 0;
  const worker = async () => {
    while (cursor < assets.length) {
      const asset = assets[cursor++];
      try {
        const response = await fetch(asset, { cache: "reload" });
        if (response.ok) await cache.put(asset, response);
      } catch {
        // A missing non-document shell asset must not strand an older worker.
      }
    }
  };
  await Promise.all(Array.from({ length: Math.min(PRECACHE_CONCURRENCY, assets.length) }, worker));
}

function runtimeCacheKey(request) {
  const url = new URL(typeof request === "string" ? request : request.url, self.location.origin);
  if (url.origin !== self.location.origin) return null;
  if (url.pathname === "/" || url.pathname === "/index.html") return url.pathname;
  return installCacheKey(url.pathname);
}

function isBootCriticalCacheRequest(request) {
  try {
    return BOOT_CRITICAL_ASSETS.has(new URL(request.url, self.location.origin).pathname);
  } catch {
    return false;
  }
}

async function trimRuntimeCache(cache) {
  const keys = await cache.keys();
  let overflow = keys.length - RUNTIME_CACHE_MAX_ENTRIES;
  if (overflow <= 0) return;
  for (const request of keys) {
    if (overflow <= 0) break;
    if (isBootCriticalCacheRequest(request)) continue;
    if (await cache.delete(request)) overflow -= 1;
  }
}

function commitRuntimeResponse(request, response) {
  const key = runtimeCacheKey(request);
  if (!key || response.status !== 200) return Promise.resolve();
  const operation = runtimeCacheMutation.catch(() => {}).then(async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(key, response);
    await trimRuntimeCache(cache);
  });
  runtimeCacheMutation = operation;
  return operation;
}

async function matchRuntimeResponse(request) {
  const key = runtimeCacheKey(request);
  if (!key) return null;
  try {
    const cache = await caches.open(CACHE_NAME);
    return (await cache.match(key)) || null;
  } catch {
    return null;
  }
}

async function matchNavigationShell() {
  try {
    const cache = await caches.open(CACHE_NAME);
    return (await cache.match("/index.html")) || (await cache.match("/")) || null;
  } catch {
    return null;
  }
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cacheBootCriticalAssets)
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)));
    })
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith("/api/")) return;
  if (event.request.method !== "GET") return;
  // Range responses are partial representations: bypass the full-resource cache key.
  if (event.request.headers.has("range")) { event.respondWith(fetch(event.request)); return; }

  const networkResponse = fetch(event.request);
  event.waitUntil(networkResponse.then((response) => {
    return response.ok ? commitRuntimeResponse(event.request, response.clone()) : undefined;
  }).catch(() => {}));
  event.respondWith(networkResponse.then(async (response) => {
    if (response.ok) return response;
    const exact = await matchRuntimeResponse(event.request);
    if (exact) return exact;
    if (event.request.mode === "navigate") return (await matchNavigationShell()) || response;
    return response;
  }).catch(async () => {
    const exact = await matchRuntimeResponse(event.request);
    if (exact) return exact;
    if (event.request.mode === "navigate") return (await matchNavigationShell()) || Response.error();
    return Response.error();
  }));
});
