"""会話で受領したBをEの設計JSONへシリアライズする。画像promptや画像生成は作らない。"""
import json, pathlib, copy
ROOT=pathlib.Path(__file__).resolve().parents[1]
SOURCE={'commit':'8ad8e9b07ab8dc8737dd9b4022a775bce61d16e1','base_blob':'4e10a53310be5b9d0aa3a6c881cf4f39d6590bd4','extension_blob':'0eda016558e426ff4142d850d26200b40fafd834'}
NAMES=['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience']
DATA={
 'A':{'object':'v302-reactor-reactorGauge-1','type':'reactorGauge','kind':'luckBoost','origin':[3699,388],'benefit':{'delta':.15,'duration_ms':20000},'cooldown_ms':38000,'file':'reactor','sound_ms':1720,
 'identity':'ゲージ開口 → 有限の帯状伝達 → 受け手の増分応答',
 'palette':{'base':'低密度部の深い青緑','secondary':'帯の青・シアン','accent':'源の針と受領輪郭の黄緑','neutral':'暗い青黒の輪郭保護'},
 'timing':'0–420msにゲージ開口、380–1120msに帯の先端が到達、1010–1240msに受領形が成立、1810–2200msに表示のみ消える。',
 'source':['開いた17/64 H半径のゲージ境界と14/64 Hの針が別々に読める','針の回転と開口量が連動し、源のピークは主輪郭の陰側まで塗り潰さない'],
 'carrier':['曲がった帯の進行端と後端の位置差','幅6.2/64 Hの帯と低密度の内部筋の差。残像・粒子ではない'],
 'receiver':['実際のplayerIdの周囲に立つ二つの開いた輪郭','到達後にだけ受領形が維持され、終端は緩やかに減衰する'],
 'math':'5次補間を[0,1]へ拘束し、源・先端・後端・受領・消失の別の時間窓を使う。',
 'audio':'138→254Hzの開口音の連続成分と到達時の508Hz成分。一つのPCM/一つのSourceに閉じる。'},
 'B':{'object':'v302-fabrication-recyclingUnit-2','type':'recyclingUnit','kind':'credits','origin':[4315,2102],'benefit':{'delta':3,'duration_ms':0},'cooldown_ms':34000,'file':'recycling','sound_ms':1620,
 'identity':'圧縮境界 → 3区画の押出し → 受け手の3区画の着座',
 'palette':{'base':'圧縮域の赤褐色','secondary':'搬送区画の銅橙','accent':'着座の切断縁の淡い琥珀','neutral':'赤黒の輪郭と区画間の抜け'},
 'timing':'0–280msに圧縮、360/540/720msに3区画を押出し、920/1100/1280msに各区画の受領、1820–2200msに表示の矩形を閉じる。',
 'source':['平行な二つの圧縮境界の間隔変化','暗い内部と明るい切断縁が異なる幅で残る'],
 'carrier':['3区画の長方形が別の開始・到達時刻で進む','各区画の後方の経路と進行位置の整合。ばらばらの粒子にしない'],
 'receiver':['受け手の横に間隔を保つ3つの着座区画','0→1→2→3の表示上の受領数の変化。サーバーの即時加算をこの時刻まで遅らせない'],
 'math':'圧縮・閉じる相はcosine、各搬送区画は別開始時刻の有界線形進行。Aの5次関数を使わない。',
 'audio':'短い圧縮の擦過、3回の押出し、920/1100/1280msの着座が一つの1620ms PCM内で進む。'},
}

def dump(path,value):
 (ROOT/path).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')

def make(key,d):
 shader=f"src/effects/{d['file']}/{d['file']}.wgsl";state=f"src/effects/{d['file']}/state.mjs";sound=f"src/effects/{d['file']}/sound.mjs"
 intent={
  'character_count':0,
  'character_attributes':{},
  'main_action':'照合済みの施設使用成功を原因単位で一回提示する。Eは身体を作画・追加しない。playerIdは既存受け手への参照で、人間の存在・性別・年齢を推測しない。',
  'main_objects':[{'objectId':d['object'],'type':d['type'],'count':1},{'id':'receipt.playerId','count':1,'kind':'既存受け手の参照。新しいキャラクターではない。'}],
  'background':'ホストが描く背景を置換しない。暗・明の検査背景は隔離ハーネス専用。',
  'style':'局所Eは2Dアニメ調の明瞭な形。既存人物・施設・背景の画風は変更しない。',
  'text_logo_policy':'E内に文字・ロゴを追加しない。検査UIの説明文はEの画素に含めない。',
  'facility_contract':{'objectId':d['object'],'type':d['type'],'effectKind':d['kind'],'worldOrigin':d['origin'],'declaredBenefit':d['benefit'],'cooldownMs':d['cooldown_ms'],'visual_lifetime_ms':2200,'client_grants_benefit':False}
 }
 expression={'source':'user_declared','purpose':'原因→媒体→受け手→結果をH64原寸の主形と時間変化で読ませる。',
  'must_communicate':['起点は照合された施設のworld origin','媒体の始点・終点と時間進行','結果表示は同じreceipt.playerIdへ結び付く','A/Bの形・色・音・時間関数は独立'],
  'preserve_ambiguity':['原因の観測・検証が不足している場合は実ゲーム因果の証明済みとしない'],
  'allowed_omission':[],'allowed_exaggeration':[],
  'protected_relations':['objectId/type/effectKind/playerId/objectCausalId/capturedTime/world originの一致','2200msのE寿命と利益時間/cooldownの分離','正確な原因IDで一回だけの専用音','画面外で可視フレームを妨げない','通常mute/音量とverifyの無音','主形不足をglow/粒子で隠さない']}
 links=[{'source':'PH1','target':'PH2','mechanism':'照合済み使用の源応答が、有限な提示用fieldの輸送相を開始する。サーバーの利益処理ではない。','consequence':'施設world originから受け手に向かう先端と後端が定義される。'},
  {'source':'PH2','target':'PH3','mechanism':'同一原因時計の到達相が、同一playerIdに束縛された受領形の提示を解放する。','consequence':'到達前に受領形が完成せず、2200msで表示だけが終端する。'}]
 reg={};phs={}
 titles=['既存施設に束縛された使用成功の源応答','有限な提示用fieldの輸送','既存受け手に束縛された受領表示']
 for n,(part,cues) in enumerate([('source',d['source']),('carrier',d['carrier']),('receiver',d['receiver'])],1):
  pid=f'PH{n}';reason=['独立した発生域と開口/圧縮の応答時間を持つ','源と受け手の間に有限の輸送領域と先端・後端を持つ','受け手への拘束と到達後の維持・終端を持つ'][n-1]
  identity={'id':pid,'name':titles[n-1],'origin':'declared' if n==1 else 'attribute_resolved','anchor':'object','visibility':'visible','local_state_difference':' / '.join(cues),'partition_reason':reason}
  reg[pid]=identity.copy()
  physical={'model_kind':'declared_fantasy','system_boundary':f'{pid}はゲーム内の提示用field。既存設備/actorの身体力学、サーバーの利益状態そのものは計算しない。輸送相はPH1→PH2→PH3に閉じる。',
   'state_variables':'表示用fieldの境界座標、無次元密度、coverage、不透明度、linear RGB放射量、経過ms。物性実測値ではない。',
   'inputs':'検証済みreceiptと単調時計。PH1はworldOrigin、PH2はPH1と実在受け手座標、PH3はPH2の到達相に依存。',
   'balance_conditions':{
    'mass':{'status':'not_applicable','balance_or_reason':'fieldは物質を生成・輸送しない。質量・燃料・残渣を捏造しない。'},
    'momentum':{'status':'not_applicable','balance_or_reason':'表示用fieldは人体・装置へ力を加えない。ノックバックや命中は実装しない。'},
    'energy':{'status':'applicable','balance_or_reason':'宣言された提示源から非負の有限RGB放射を供給し、各相の包絡と2200ms境界で消散表示を閉じる。J/Wの物理的保存や測定を主張しない。周囲を加熱しない。'},
    'charge':{'status':'not_applicable','balance_or_reason':'電荷輸送・放電を宣言していない。電磁学的な温度・電流を色から逆算しない。'}},
   'constitutive_response':'境界/密度/不透明度/発光を別の式で求める。'+d['math'],
   'initial_condition':'サーバー成功前に表示なし。遅延receiptはcapturedTimeから進んだ既存相へ参加する。',
   'boundary_conditions':'源は指定world座標に固定。受け手は同じplayerIdの250ms以内のサンプル。欠落時は受け手と輸送を非表示にし、施設位置を受け手に偽装しない。',
   'approximation_scope':'本モデルはゲーム効果の提示機構であり、実在する運動・エネルギー伝達の実証ではない。actor寸法はホスト入力H、ワールドのm換算は未確認なので比で扱う。'}
  na={'Thermo':'非熱発光の提示fieldなので温度差・熱膨張・燃焼を足さない。','Fluid':'質量流・粒子・空気抵抗を作らない。輸送は宣言fieldの境界移動。','Materials':'元の設備材質やactor衣服を測定/変更しない。密度は提示fieldの重み。','Electromagnetics':'色と光量は提示値であり、実在の電流・電荷分極の証拠ではない。','Rheology':'素材の粘弾性や接触力を計算しない。形の位相変化を機械的クリープと呼ばない。','WaveOptics':'波長・コヒーレンス・薄膜を宣言していない。色差を干渉の実証にしない。','SurfaceScience':'濡れ・付着・汚染を宣言していない。境界の色を表面反応と呼ばない。'}
  domains={}
  for name in NAMES:
   if name=='Optics':domains[name]={'applicability':'applicable','role':'primary','items':[cues[0],cues[1],'放射と遮蔽coverageを分離する。物理的レンズフレアは使わない。'],'evidence_or_constraint':f'{pid}の境界差を{shader}:fsが生成。OBS1はその源からの狭い周辺応答だけを付加。'}
   else:domains[name]={'applicability':'not_applicable','role':'latent','items':[na[name]],'evidence_or_constraint':f'{pid}.PhysicalModelの非物質fieldと、共有媒体条件を参照。数合わせで別の機構を足さない。'}
  phase=['源の開口/圧縮、供給の立上りと停止','有限領域の進行、受け手への到達','到達後の維持と表示のみの終端'][n-1]
  local_links=[x for x in links if pid in [x['source'],x['target']]]
  phs[pid]={
   'identity':identity,'DeepStructure':{'Core':cues[0],'Structure':cues[1],'Surface':'内部筋/切断縁/外側境界の幅と不透明度を区別し、共通のぼかし幅で塗り潰さない。'},
   'PhysicalModel':physical,
   'ScaleRegime':{'characteristic_length':'H=ホストが渡す既存actor基準高。検査はH=64 backing px。源・受領形はHに対する比、輸送長は登録済みworld座標間距離。',
    'characteristic_time':phase+'。全体は2200ms。'+d['timing'],
    'dominant_balance':'空間境界の可読性と因果時計を支配条件とする。実在の慣性・粘性・表面張力を比較する系ではない。',
    'dimensionless_reasoning':'機構の比較は境界幅/H、源-受け手距離/H、age/2200ms。Re/Weは質量流と媒体物性がないためnot_applicable。',
    'detail_cutoff':'必須の帯・針・区画はH64で約1.7–14px。1px未満の微細要素を唯一の証拠にしない。実画素の可読性は未観察。'},
   'OctaDomain':{'conform_to':'OctaDomainTemplate','all_8_domains_required':True,'Domains':domains},
   'PerceptualReadability':{'direct_evidence':cues,'indirect_evidence':'周辺PHへの接続は上記の共通時間とworld束縛で追跡。実ゲーム利益の証明にはしない。','figure_ground_separation':'high','edge_legibility':'広い主形と狭い明縁の外に暗い輪郭が残る設計。暗明背景で実観察が必要。','perceptual_failure_risk':'H64で起点/作用/結果のどれかが見失われること。単なる色替え・白い塊化。',
    'cue_roles':[{'cue':c,'supports':['局所状態の変化','因果経路に対する前後相'][j],'reliability_and_overlap':'輪郭と明度は同じ源に由来するため統計的独立とはみなさない。縮小・背景・遮蔽に依存する。'} for j,c in enumerate(cues)],
    'confusable_alternative':'施設と無関係な装飾、actorに当たる攻撃、露光残像、利益の二重加算。',
    'disambiguating_evidence':'源をworld originへ固定し、受け手は同一playerIdだけへ接続。位相順を保ち、利益APIを一切呼ばない。画素だけからサーバー真正性は証明できない。',
    'viewing_conditions':'H64を64 backing pixel、canvas 704×320のCSS等倍・ブラウザ100%として観察する想定。想定外の縮尺で同じ判別を保証しない。'},
   'GeometryConstraint':{'surface_orientation':'DVA 2D x右/y下を局所平面へ写像。現実の物体法線を捏造しない。','normal_field_coherence':'解析境界の法線と前後順を局所field内で保つ。物理的反射軸は非該当。','curvature_behavior':'アーチと帯の連続曲率。折れと内部筋を区別。' if key=='A' else '矩形の面・切断縁・区画間隔を保ち、円形噴出へ潰さない。','silhouette_logic':cues[0],
    'contact_relation':'既存actorへの表示束縛であり、物理接触/着弾/支持床の追加ではない。','spatial_relation':'PH1固定→PH2接続→PH3受け手追従。同じworld→screen投影を全体に使う。'},
   'StateDynamics':{'state_space_extent':phase,'transition_path_character':'monotonic','local_stability_type':'stable','convergence_behavior':phase+'。反復・ループなし。','damping_profile':'源/輸送/受領ごとの包絡を個別に設定。'+d['math'],'oscillation_pattern':'none','equilibrium_recovery':'表示終了はfieldの消失。既存サーバー効果・装置状態・actor姿勢を復帰させない。','transition_failure_risk':'カメラや再描画で時間を巻き戻すこと、遅延を初回相として再生すること。','driving_input':'PhysicalModel.inputsとreceipt.capturedTimeから一度だけ作るstartMono。','response_timescale':'ScaleRegime.characteristic_timeとVideoGenerationPolicy.Durationを参照。','phase_relation':d['timing'],'stability_condition':'共通単調時計、有限な境界、補間を[0,1]へ拘束。原子的な原因claimが成功した場合だけ存在。'},
   'Couplings':{'DominantCouplings':[f"{x['source']}.Optics -> {x['target']}.Optics: {x['mechanism']} {x['consequence']}" for x in local_links],
    'SecondaryCouplings':[],
    'CausalAssessment':{'intervention':'設計比較としてreceipt時刻とactor経路だけを変更し、objectId/効果種/寿命/源位置を保持する。','predicted_response':'遅延時は残り相だけ、2倍actor速度では同一受け手へ経路が追従し、expiredは無表示/無音。','competing_explanation':'明度の変化は背景や表示変換にも依存する。実ゲーム利益はサーバー処理でありEの到達が利益の原因ではない。','uncertainty':'wire receiptの認証経路・実ゲーム音声バス・物理GPU画素/聴感が未接続または未観察。フィールド数だけで成功を断定しない。','check_status':'hypothesis_only','evidence_refs':[]}},
   'CausalityLinks':{'physical_influence':local_links,'observation_dependency':[{'source':'OBS1','target':pid,'basis':'同じ源の位置・強度・時間から有限PSFを求める'},{'source':'OBS2','target':pid,'basis':'既存境界から暗い輪郭を求める'}],
    'gaze_path':[{'source':pid,'target':f'PH{n+1}','reason':'起点・輸送・受領の順を境界と時間差で読む'}] if n<3 else []},
   'Evidence':{'direct':cues,'indirect':[],'candidates':[]},
   'SurroundingChanges':{'entries':[{'target':x['target'],'change':x['consequence']} for x in local_links if x['source']==pid],'latent_reference_target':'none'},
   'VisualProjection':{'role':'essential','world_state_ref':f'{pid}.StateDynamics','retained_cues':cues,'simplification':'微細粒子や模様を追加せず、源/帯/区画の広い境界を残す。H64の単位で材質名より主形を優先。','omission_scope':[],'exaggeration_scope':[],'ambiguity_scope':[],'intent_ref':'InferenceExpansionPolicy.ExpressionIntent'},
   'BeautyStructureApplication':{'conform_to':'PlatonicGoodTemplate.BeautyStructuring','target_policy':'standard','adjustment_reason':'not_applicable: 既存の境界と余白だけで適用。','axes':{
    'contrast':[cues[0],'明るい放射縁の外に暗い輪郭を保持する'],
    'temporal_phase':[cues[1],'源の始動・受領・終了が同時の点滅にならない']}},
   'GTB_connections':{'Good':'同一原因・同一受け手・利益処理の非介入を保つ','Truth':'座標とcapturedTimeに連続に接続する','Beauty':'境界と時間差で情報を分ける'},
   'AcceptanceCriteria':{'full_structure_present':True,'all_8_domains_present':True,'visibility_specific_evidence_present':True,'physical_and_observation_links_not_mixed':True,'physical_model_scale_and_response_consistent':True,'perceptual_cues_and_identifiability_limits_explained':True,'causal_assessment_status_matches_evidence':True},
   'FailurePatterns':['H64で起点/作用/結果が見分けられない','白い塊/無根拠な粒子で主形不足を隠す','描画が利益を付与したと誤認させる','遅延/カメラ移動で再生を始め直す']}
 obs={
  'OBS1':{'operation_type':'posteffect','input_references':['PH1','PH2','PH3','optical_condition'],'target_mask':'源の明るい針/切断縁、輸送の帯/区画、受領縁から約1.15–1.5px@H64の減衰域。','stage':'world_render_observation','composite_method':'add','intensity':'源のlinear RGBに比例する係数0.12–0.19の局所応答。IntensityBudgetを参照。','protected_regions':['主形の内部筋/区画間の抜け','無関係な背景域'],'output_consequence':'既存の強い入力の近傍に狭いにじみ。主形そのものは作らない。','dependencies':['PH1','PH2','PH3','optical_condition'],'sampling_consequence':'H64では源周辺の1.15–1.5pxを中心に解析的減衰。外部画像・GPU readbackなし。実装は有限PSF近似で、測定されたカメラ応答ではない。'},
  'OBS2':{'operation_type':'edge','input_references':['PH1','PH2','PH3'],'target_mask':'既存PHの解析境界を約1.4–1.8px拡張した輪郭域。','stage':'world_render_observation','composite_method':'alpha_blend','intensity':'既存SDF境界の0.82–0.91 coverage。共有予算内でローカル。','protected_regions':['形の開口/区画間の余白','ホスト全体の画風・背景'],'output_consequence':'明背景でも主要境界の陰側を残す。源の発光値を弱めない。','dependencies':['PH1','PH2','PH3'],'sampling_consequence':'画面上の境界を解析評価。1px未満の繰返しパターンを導入しない。'},
  'OBS3':{'operation_type':'tone','input_references':['OBS1','OBS2','display_condition'],'target_mask':'ホストが同意したlinear HDR render attachment。隔離previewでは全canvas。','stage':'display','composite_method':'replace_with_constraint','intensity':'露光1.0、輝度0.75まではidentity、その上だけ連続な肩と色域圧縮。','protected_regions':['低輝度背景の既存値','源内部の構造差'],'output_consequence':'強い源の設計強度を保持して表示へ収める。白飛び回避のためPH放射量を一律低下させない。','dependencies':['OBS1','OBS2','display_condition'],'sampling_consequence':'同じGPU上のHDR textureを各出力pixelへtextureLoad。CPUへのreadback/ラスタ素材読込ではない。sRGBへ明示符号化する。'},
  'OBS4':{'operation_type':'other','input_references':['PH1','PH2','PH3','display_condition'],'target_mask':'同一原因IDの専用SFX一件だけ。','stage':'display','composite_method':'other','intensity':'源PCMは有界。専用バス内で同時N声を1/Nで混合し、通常mute/音量はホストの既存SFXバスで適用。通常音量を二重乗算しない。','protected_regions':['verifyの完全無音','他原因の音','既存の通常mute/音量設定'],'output_consequence':d['audio'],'dependencies':['PH1','PH2','PH3','display_condition'],'sampling_consequence':'Web Audio context.sampleRateでPCMを計算。capturedTimeに対応するoffsetから一つのBufferSourceを一回だけstart。音源合成の数値検査は聴感ではない。'}
 }
 layers=[]
 for n,(role,part) in enumerate([('primary_form','source'),('transport','carrier'),('environment_response','receiver')],1):
  pid=f'PH{n}';cues=d[part]
  layers.append({'layer_id':f'L{n}','role':role,'domain':'world','selection':{'basis':'explicit' if n==1 else 'attribute_resolved','scope_and_reason':'ユーザーの施設Eに存在する源・伝達・受領を具体化。独立した物体・出来事の追加ではない。'},'PH_refs':[pid],'OBS_refs':[],
   'function_and_visible_result':' / '.join(cues),
   'spatial_structure':{'anchor_and_transform':f'{pid}.GeometryConstraint / CoordinateGravityWindTemplate','extent_orientation_depth':'既存2D world上のfield。奥行きは重なりと境界内外で扱い、架空の3D厚み/物理接触を与えない。','macro':cues[0],'meso':cues[1],'micro':'H64で約1.4px未満の独立情報を使わない。ノイズ/粒子で水増ししない。','edge_and_occlusion':'暗い輪郭→field内部→細い放射縁→OBS1の順で局所合成。'},
   'material_and_optics':{'carrier_and_mechanism':'宣言されたゲームの提示field。実在素材の反射・化学反応ではない。','emission_opacity_density':'coverage、不透明度、密度係数、RGB放射を独立変数としてshaderで使用。','color_and_light_response':d['palette'],'model_refs':f'{pid}.PhysicalModel / {pid}.OctaDomain.Optics'},
   'motion_and_phase':{'driver_and_transport':'receiptとstartMonoから有限相を評価。actor位置はホストサンプルのみ。','distribution_and_correlation':'not_applicable: 独立した粒子集団なし。Bの3区画は既存credits+3の受領表現に対応する。','onset_peak_decay':d['timing'],'state_and_sampling_refs':f'{pid}.StateDynamics / VideoGenerationPolicy.timeline / ObservationIntegrationTemplate.SamplingContract'},
   'integration':{'composite_and_mask':'linear HDR passで世界位置を投影。観測応答はOBS参照へ分離。','protected_cues':cues,'failure_to_avoid':'位置・位相がずれる、受け手を推測で作る、glowが主形を代替する。'}})
 layers.append({'layer_id':'L4','role':'observation_support','domain':'observation','selection':{'basis':'attribute_resolved','scope_and_reason':'強い入力の源・境界に対応する局所観測応答だけを選択。'},'PH_refs':[],'OBS_refs':['OBS1','OBS2','OBS3'],
  'function_and_visible_result':'源周辺の狭いにじみと既存境界の分離を保持し、HDR入力を表示へ写像する。',
  'spatial_structure':{'anchor_and_transform':'既存源のscreen座標とmask','extent_orientation_depth':'screen上だけ。厚みや接触を持たない。','macro':'主形と背景の境界を保護','meso':'源周辺の小さな減衰域','micro':'PSF幅をH64へ従属。格子/scanlineなし。','edge_and_occlusion':'OBS2輪郭→PH本体/放射→OBS1周辺応答→OBS3表示'},
  'material_and_optics':{'carrier_and_mechanism':'OBSの有限PSF近似、境界処理、display transform','emission_opacity_density':'PHの密度/不透明度をOBS輝度と同一視しない','color_and_light_response':'CCMの源色へ従属。レンズghost/虹色の追加なし。','model_refs':'OBS1/OBS2/OBS3'},
  'motion_and_phase':{'driver_and_transport':'同じPH源の時間/位置。独立時計なし。','distribution_and_correlation':'源が消えればそのOBS寄与も消える。','onset_peak_decay':'基底PHから即時に評価。機械的慣性なし。','state_and_sampling_refs':'SamplingContract / 各OBS.sampling_consequence'},
  'integration':{'composite_and_mask':'OBSのstage/input/dependenciesに従う非循環順序。','protected_cues':'源・区画間の抜け・主形','failure_to_avoid':'主形をglowだけで作る、sourceなしのlens flare、globalな白幕'}})
 model={
  'FoundationOperationTemplate':{'OutputContract':{'schema_version':'B-Expression-2','mode':'Video','operation':'design_only'},'TemplateConsolidation':{'per_chapter_template_count':1,'template_position':'chapter_end','inter_template_duplication_forbidden':True,'cross_chapter_reference_preferred':True},'RuleContract':{'fields':['rule_id','owner','priority','applies_when','requirement','exception_to','validation_id'],'same_priority_resolution':'explicit_exception_or_compatible_union','unresolved_conflict_result':'spec_conflict'},'GlobalInterpretation':{'world_registry':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registry':'ObservationIntegrationTemplate.ObservationRegistry','full_PH_structure_required_for_all_visibilities':True,'WindCapsule_required':True},'UniversalNoLabelOnly':{'label_only_declaration_forbidden':True,'indirect_evidence_for_implicit_latent':True},'Acceptance':{'each_chapter_has_exactly_one_template':True,'independent_template_groups_absent':True,'unique_rule_ids_and_resolvable_references':True,'same_priority_conflicts_resolved_explicitly':True}},
  'InferenceExpansionPolicy':{'DeclaredIntent':intent,'ExpressionIntent':expression,'SelectionLifecycle':{'stages':['candidate','accepted','registered_world','registered_observation'],'candidate_catalog_in_final_code':False,'world_registry':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registry':'ObservationIntegrationTemplate.ObservationRegistry','adoption_checks':['DeclaredIntent_consistency','contribution','readability','activation_condition']},'inferred_support_elements':{'default_permission':'denied','explicit_user_permission_required':True,'allowed_domains':[],'allowed_scope':'user_explicitly_authorized_targets_and_domains_only','support_declared_elements_without_overriding_them':True,'latent_visualization_object_not_required':True},'Acceptance':{'declared_intent_preserved':True,'inference_without_explicit_user_permission_absent':True,'candidate_accepted_registered_distinguished':True,'unselected_candidates_absent_from_final':True}},
  'PlatonicGoodTemplate':{'Good':{'evidence':'正しい原因と受け手だけを一回提示し、サーバーの利益処理を変更しない。'},'Truth':{'coordinate_continuity':'world固定源と実actor座標を同じ投影へ渡す','physical_causality':'宣言された提示field内の相と境界のみをモデル化。実在物理/利益因果の実証とはしない。','state_transition_readability':d['timing']},'Beauty':{'boundary_readability':'PHごとの2種の境界差','gaze_circulation':'源→輸送→受領と、輪郭/余白の別経路','structural_separation':'色替えでなく異なるmacro/mesoと時間構造'},'BeautyStructuring':{'axes':['ratio_proportion','balance_symmetry','contrast','rhythm_repetition','whitespace_density','hierarchy_gaze_flow','material_response','temporal_phase'],'standard_minimum_axes_per_PH':2,'standard_minimum_evidence_per_applied_axis':2,'intent_adjustment_ref':'InferenceExpansionPolicy.ExpressionIntent'},'Acceptance':{'each_PH_connected_to_at_least_two_GTB_layers':True,'single_formula_does_not_dominate_beauty':True}},
  'PhenomenonSystemTemplate':{'PartitionPolicy':{'criterion':'源応答・輸送境界・受け手の維持相を分割。学問別・層数合わせの分割なし。','shared_condition_policy':'共通時間・H・receiptを一つのruntime契約で参照し、各PHの境界/時間関数は個別保持。','no_discipline_based_split':True},'SharedConditions':{},'PhenomenonRegistry':reg,'PhenomenonBlock':phs,'Acceptance':{'all_PH_have_required_full_structure':True,'visible_implicit_latent_have_same_field_set':True,'OBS_not_in_PH_registry':True,'PIA_resolved_as_identification_lifecycle':True}},
  'PEMTemplate':{'Mode':{'phenomenon_equality':True,'focus_phenomenon':'none'},'CausalMesh':{'physical_mesh_required':True,'gaze_target_policy':'standard','adjustment_reason':'not_applicable: 孤立した装飾を追加せず、源と受け手の関係を保持。','gaze_path_A':'源の始動→輸送の進行端→受領の成立','gaze_path_B':'源と受け手の外側輪郭/余白を往復し、中央の内部筋または3区画を数える。進行端の追跡とは別経路。','local_extrema_connected_to_gaze_paths':True},'AttentionControl':{'attention_focus':'hierarchical','single_requires_explicit_request':True},'Acceptance':{'no_unexplained_isolation':True,'gaze_paths_match_selected_policy_and_explicit_intent':True,'local_peak_returns_to_mesh':True}},
  'CoordinateGravityWindTemplate':{'WorldApplicability':{'status':'applicable','reason':'源・輸送・受領の提示fieldがworld座標へ束縛される。'},'Units':{'length':'m','time':'s','temperature':'K_or_declared','pressure':'Pa_or_declared','angle':'rad'},'WorldCoordinates':{'handedness':'right_handed','X':'right_positive','Y':'up_positive','Z':'backward_positive','camera_forward':'negative_Z','origin':'declared_anchor_origin: 対象のworld origin'},'CameraCoordinates':{'X':'right_positive','Y':'up_positive','forward':'negative_Z','projection':'orthographic','FOV_or_scale':'H_hostとpixelsPerWorldUnitで決定。DVA単位→mは未確認なのでs_m>0の記号変換で保持し、実装では比が相殺される。'},'ScreenCoordinates':{'domain':'[0,1]x[0,1]','x':'0_left_to_1_right','y':'0_top_to_1_bottom'},'TransformChain':{'order':['world','camera','screen'],'world_to_camera':'DVA(x,y)→canonical((x-origin.x)*s_m,-(y-origin.y)*s_m,0)。camera平行移動を同じs_mで写す。','camera_to_screen':'screen.x=((x-center.x)*pixelsPerWorldUnit+W/2)/W、screen.y=((y-center.y)*pixelsPerWorldUnit+H/2)/H。s_mは相殺。'},'ContactCoordinates':{'contact_patch':'none: 表示fieldなので物理接触なし','contact_normal':'none','support_relation':'not_applicable','no_penetration':True},'VectorField':{'dominant_vector':{'direction':'PH1 world origin→PH3実actorサンプル','magnitude':'PH2の進行端位置/共通秒','falloff':'既存源・受領境界の包絡のみ','fluctuation':'none: 任意ノイズなし'},'secondary_vector':{'direction':'zero','magnitude':0,'falloff':'none','fluctuation':'none'}},'Gravity':{'condition':'normal','vector':'canonicalの下向き[0,-1,0]を方向参照とする','strength':'not_applicable: この提示fieldは質量を持つ運動を計算しない。DVA全体の重力値を断定しない。','affected_responses':[],'evidence':'not_applicable: 床・弾道・荷重を追加しない。'},'WindCapsule':{'required':True,'medium_state':'other','medium_properties':{'density':'not_applicable: 非物質の提示用game field。空気/水/真空をDVA世界の事実として追加しない。','viscosity':'not_applicable: 流体ではない。'},'Field':{'direction':'zero','speed':0,'gust':'none','shear':'none','turbulence':'none'},'ApplicableResponses':{'body':'not_applicable: 身体を描画・変形しない','cloth':'not_applicable: 衣装なし','hair':'not_applicable: 髪なし','loose_elements':'not_applicable: 粒子/破片なし','environment':'PH1/PH3のfield境界だけ。風の証拠は要求しない。'},'non_applicable_responses_explicit':True},'Acceptance':{'world_camera_screen_transform_defined':True,'screen_axis_convention_defined':True,'Gravity_present':True,'WindCapsule_present':True,'medium_state_present':True,'no_inapplicable_wind_evidence_required':True}},
  'OctaDomainTemplate':{'Domains':{x:{'definition_ref':f'基底.md 05.{x}','instance_fields_location':'PhenomenonSystemTemplate.PhenomenonBlock.*.OctaDomain.Domains'} for x in NAMES},'Acceptance':{'all_8_domains_present':True,'role_classification_present':True,'latent_does_not_require_direct_visualization':True,'non_applicable_domains_retained_with_reason_and_latent_role':True}},
  'AnimeStudiesTemplate':{'applicability':'VideoのE。Image限定のsnapshot規則は非該当。局所のシルエットと作画密度だけ互換参照。','KeyframeSnapshot':{'phase':'environmental_peak','state_t_minus_1_evidence':'源・輸送の前相をVideo timelineで評価','state_t_evidence':'各PHの現在の境界を保持','state_t_plus_1_evidence':'既存fieldの次相。新規要素を追加しない。'},'Layout':{'staging':'source→carrier→receiverを同じ平面で読む','projection_consistency_ref':'CoordinateGravityWindTemplate','whitespace_role':'帯内部/区画間/受け手の中心を抜く。'},'PoseActing_or_SceneActing':{'character_ref':'not_applicable: 人体作画なし','object_balance':'not_applicable: 質量物体の姿勢を変えない','contact_logic':'world束縛のみ。命中/着弾を偽装しない。'},'MotionReadability':{'motion_blur_smear_speed_line_policy':'explicit_user_request_only','primary_causality_replacement_by_motion_effects':False},'CompositeIntegration':{'observation_ref':'ObservationIntegrationTemplate','contact_shadow_used_for_integration':'not_applicable: 接触床を追加しない。'},'Acceptance':{'previous_and_next_time_or_explicit_ambiguity_accounted_for':True,'projection_consistent':True,'posteffects_do_not_replace_primary_causality':True}},
  'ObservationIntegrationTemplate':{'ObservationRegistry':obs,'SamplingContract':{'output_resolution':'previewの実装設定704×320 backing pixel。ゲームはホストのwidth/height入力。実表示未観察。','intended_display_scale':'H64=64 backing px。preview CSSは等倍。ブラウザzoom100%を評価条件にする。','spatial_detail_policy':'主境界は複数pixel。解析SDFの0.65–0.7px遷移でedgeを積分近似。外部ラスター/ノイズ/grainなし。','temporal_sampling':'Video設計。runtimeはホストrAF cadenceに従い、絶対ageで評価。60Hzは検査予定値で実達成fpsではない。露光積分/残像なし。Audioはcontext.sampleRateに従う。','filter_and_resample_policy':'ネイティブWGSLによる解析境界とGPU内HDR→出力pixel。モデルに書いただけの後処理ではない。CPU画素取得/代替レンダラなし。'},'ImageIntegration':{'ToneColor':['OBS3'],'LightIntegration':['OBS1'],'ShadowDensity':[],'DepthAir':[],'EdgeLine':['OBS2'],'TextureOutput':[]},'LensFlareField':{'registry_id':'none','artifact_type':'optical_observation_artifact','world_anchor':'none','SourceMapping':{'source_state':'none','source_id':'none','source_screen_position':'not_applicable','source_luminance_rank':'none'},'ResponseVisibility':{'level':'none','reason':'仮想orthographic観測。レンズ面/開口/ghost経路を宣言していない。PSFの局所にじみをlens flareと呼ばない。'},'LensModel':{'flare_mode':'latent','coating_strength':'high','aperture_state':'mid','anamorphic':False,'parameter_status':'非起動なので光学事実として適用しない'},'SpatialBinding':{'image_center_relation':'not_applicable','optical_axis_offset':'none','chain_axis':'none'},'Responses':{'Ghost':'disabled','Veil':'disabled','Streak':'disabled','Spectral':'disabled'}},'IntensityBudget':{'global_observation_budget':'局所PSF係数0.12–0.19、edgeは既存境界の近傍だけ。源のHDR放射を先に定義し、表示の肩のみで変換する。','para':'low_to_medium','flare_gradient':'low_to_medium','glow':'low','diffusion':'low','grain':'very_low','chromatic_aberration':'very_low','protected_region_priority':'highest','intentional_departures':[]},'CompositeValidation':{'contour_preserved':'not_tested','highlight_clipping':'not_tested','shadow_crushing':'not_tested','chroma_displacement':'not_tested','fine_detail_retention':'not_tested','protected_background_preserved':'not_tested'},'Acceptance':{'OBS_separate_from_PH':True,'physical_lensflare_source_binding_preserved':True,'display_artifact_does_not_fake_physical_source':True,'intensity_budget_is_single_source_of_truth':True,'sampling_conditions_and_actual_execution_distinguished':True}},
  'ExtremumDesignColorTemplate':{'PEV':{'candidate_state_set':[{'state_id':'accepted_finite_field_sequence','status':'accepted','readable_physics':'源・有限輸送・受領の採用済み状態列','response_hierarchy':'PH1→PH2→PH3'}],'selected_physics_extremum':'accepted_finite_field_sequence','reason':'採用済みの源・輸送・受領の状態列だけを完成形として残す。未採用候補を登録しない。実物理の最適性を主張しない。'},'AES':{'selected_from_PEV_only':True,'visual_circulation':'進行端と周辺の境界/余白の2つの読み','asymmetric_balance':'world源と受け手の位置差を保持。任意の黄金比は強制しない。','tension_release':'源の密度上昇から受領後の維持へ','body_environment_consonance':'既存actor位置へ束縛。身体作画は非該当。','selected_aesthetic_extremum':d['identity']},'DesignScience':{'VisualHierarchy':'源応答→輸送→受領の境界。OBSは補助。','DensityPlan':'主形を広く、内部筋/区画間を抜き、微細粒子を置かない。','ShapeOrder':'Aは開口/連続帯/分岐輪郭、Bは圧縮/3区画/着座の矩形。','OrnamentFunction':'独立装飾なし。すべて既存Eの因果または観測に結び付く。'},'CCM':{'Palette':d['palette'],'ColorDynamics':{'temp':'cool' if key=='A' else 'warm','value_range':'暗い輪郭から局所HDR源まで。値はshaderに明示。','saturation':'局所の源色に従属。全球虹色化なし。'},'Lighting':{'key_K':'not_applicable: 非熱RGB発光。Kからの色推定なし。','fill_tint':'既存背景の色は変更しない。'},'BackgroundBinding':{'bg_dominant':'ホスト背景を維持','bg_accent':'追加なし'},'PerceptualControl':{'attention_focus':'hierarchical','figure_ground_stability':'high','arousal_level':'mid','perceptual_noise_tolerance':'low'}},'Acceptance':{'PEV_applied_before_AES_when_world_candidates_exist':True,'AES_does_not_override_world_validity':True,'legacy_FDS_resolved_to_DesignScience':True,'CCM_fields_fixed':True}},
  'ReflectionClosureTemplate':{'Applicability':{'applies_when':[],'otherwise':'latent_optics_condition','reason':'明縁はfieldの放射であり反射・金属光沢・濡れ面ではない。設備材質を推測しない。'},'ReflectionClosureBlock':{},'Acceptance':{'reflection_integrated_into_PH_mesh':True,'lensflare_registered_as_OBS_not_reflection':True}},
  'PhenomenonProfileTemplate':{'ApplicabilityGuide':{'selections':[]},'ProfilePolicy':{'secondary_boost_only':True,'full_PH_structure_still_required':True,'only_selected_profiles_in_design':True},'Profiles':{},'reason':'既存fieldにWater/Fire/Metal等の材料機構を付加しない。','Acceptance':{'profile_does_not_replace_PH_schema':True,'reactive_profile_only_when_applicable':True}},
  'TermsTemplate':{'PH':'world-internal phenomenon','OBS':'observation/display operation','PIA':'PH identification lifecycle','PEM':'Phenomenon Equality Mode','PEV':'Physics Extremum Visualization','AES':'Aesthetic Extremum Selection','CCM':'Color Catalog Module','FDS':'legacy alias -> DesignScience + AES Form Design Selection','DeclaredIntent':'explicit user intent preservation','ValidationResults':'actual validation outcomes separated from requirements','Acceptance':{'undefined_legacy_terms_absent':True}},
  'ExtensionActivationTable':{'entries':{'VFX':{'trigger':'explicit','output_blocks':['VFX']},'ECodeImplementation':{'trigger':'executable_runtime_E_code_explicit','output_blocks':['ECodeImplementation']},'PostEffects':{'trigger':'attribute_resolved','output_blocks':['PostEffects']},'LDM':{'trigger':'explicit_VFX','output_blocks':['LuminanceDynamicsModule']},'VideoGenerationPolicy':{'trigger':'Mode=Video design only','output_blocks':['VideoGenerationPolicy']}},'expression_intent_ref':'InferenceExpansionPolicy.ExpressionIntent','output_contract_ref':'FoundationOperationTemplate.OutputContract','Acceptance':{'one_activation_source_of_truth':True,'disabled_modules_omitted':True}},
  'VFX':{'trigger':'explicit','world_registration':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registration':'ObservationIntegrationTemplate.ObservationRegistry','design_intent':{'subject_and_action':d['identity'],'expression_intent_ref':'InferenceExpansionPolicy.ExpressionIntent','primary_read':'源→媒体→受け手→結果','layering_basis':'源/輸送/受領の異なる境界と時間相。層数で物体・粒子を増やさない。'},'layers':layers,'interlayer_links':[{'source_layer':'L1','target_layer':'L2','relation_type':'physical_influence','mechanism_and_consequence':links[0]['mechanism']+' '+links[0]['consequence'],'foundation_binding':'PH1.CausalityLinks.physical_influence'},{'source_layer':'L2','target_layer':'L3','relation_type':'physical_influence','mechanism_and_consequence':links[1]['mechanism']+' '+links[1]['consequence'],'foundation_binding':'PH2.CausalityLinks.physical_influence'},*({'source_layer':'L4','target_layer':f'L{n}','relation_type':'observation_dependency','mechanism_and_consequence':'観測層が既存源の位置/強度/時間を入力にする。入力層を先に評価する。','foundation_binding':f'OBS1/OBS2 dependencies→PH{n}'} for n in range(1,4))],
   'causal_path':{'input':'照合済み成功receipt','carrier_PH':'PH2','receiver':'同じplayerIdの既存actor。欠落時は推測しない。','ScaleRegime_ref':'PH2.ScaleRegime','StateDynamics_ref':'PH2.StateDynamics','ReactivePhaseChange_ref':'not_applicable: 反応/相変化なし'},
   'orchestration':{'common_time_basis':'VideoGenerationPolicy.timeline / receipt.capturedTime→startMono','layer_phase_relations':d['timing'],'environment_response':'源と受け手の既存位置にfield応答。床・破片・煙・熱変形を追加しない。','visual_hierarchy':d['identity'],'bullet_time':'not_applicable: 未指定'},
   'output_integration':{'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','LDM_ref':'LuminanceDynamicsModule','composite_order':'OBS2輪郭→world放射→OBS1周辺応答→OBS3表示。OBS4音は同じ原因時計で別出力。','color_alpha_contract':'linear rgba16float、coverageはpremultiplied alpha、放射は加算成分。最終のみsRGB。source-alpha二重乗算なし。','scale_adaptation':'Hで境界幅を比例制御。H64未満の可読性は未観察。'},
   'validation_plan':{'layer_checks':'源・内部・外縁・受領の役割をOBS無効時にも検査','composite_checks':'暗明背景、源の局所白化と内部境界、3区画間の余白','temporal_checks':'全寿命、通常/2倍actor、duplicate/delayed/offscreenを検査。実画素は別記録。','actual_results_ref':'GlobalAcceptanceTemplate.ValidationResults'},
   'Acceptance':{'world_VFX_registered_as_PH':True,'observation_only_effects_not_misregistered_as_VFX_PH':True,'layer_roles_scales_and_relations_explicit':True,'layer_count_does_not_force_new_content_or_PH_partition':True,'material_motion_environment_and_composite_consistent':True,'shared_intensity_and_sampling_contracts_preserved':True,'structural_requirements_not_reported_as_render_evidence':True}},
  'ECodeImplementation':{'trigger':'executable_runtime_E_code_explicit','output_kind':'executable_effect_source_not_image_generation','source_revision':SOURCE,'target_runtime':'native WebGPU + Web Audio API','source_and_time_contract':'FacilityController.receive: 認証→7項目照合→IndexedDB原子的claim→一回だけの専用経路。capturedTimeを同期server時計から単調時計へ一回写す。','world_PH_refs':['PH1','PH2','PH3'],'observation_OBS_refs':['OBS1','OBS2','OBS3','OBS4'],'implementation_artifacts':[shader,state,sound,'src/runtime/controller.mjs','src/runtime/audio.mjs','src/gpu/renderer.mjs','src/gpu/composite.wgsl'],'applicable_rule_evidence':'docs/B-rule-mapping.json / docs/B-rule-mapping.md','validation':{'syntax_and_shader':'not_run','actual_GPU_pixels_and_timing':'not_run','game_event_and_SFX':'not_run'},'Acceptance':{'baseline_and_selected_extensions_preserved':True,'image_generation_not_implied':True,'runtime_code_and_visual_acceptance_distinguished':True}},
  'PostEffects':{'trigger':{'ordinary_posteffects':False,'beta_targets':[]},'selection':{'mode':'exact_selected_operations','scope_resolution':'attribute_resolved_target_and_scope','exact_selected_operations':['source_bound_finite_PSF','existing_boundary_edge','HDR_display_transform']},'autonomous_activation':{'physical_causality_input_required':False,'registry':'ObservationIntegrationTemplate.ObservationRegistry','budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract'},'SPCA':{'applies_if':'world_internal_PH_local_peak_selected','evidence_types_standard_two_of':['gradient','decay','occlusion'],'explicit_intent_adjustment':'not_applicable','PostEffects_alone_does_not_require_new_PH':True},'global_posteffects':{'applies':True,'exact_OBS_operations':['HDR_display_transform'],'OBS_refs':['OBS3']},'local_posteffects':{'applies':True,'targets':['PH1','PH2','PH3'],'exact_OBS_operations':['source_bound_finite_PSF','existing_boundary_edge'],'OBS_refs':['OBS1','OBS2']},'operation_contract':{'required_fields':['input_references','target_mask','stage','composite_method','intensity','protected_regions','sampling_consequence'],'sampling_consequence':'各OBSと共有SamplingContractを参照。レンズghostやscanlineを一括追加しない。'},'Acceptance':{'exact_selected_operation_does_not_infer_layers':True,'global_local_scope_unambiguous':True,'legacy_five_domain_reference_absent':True}},
  'LuminanceDynamicsModule':{'trigger':{'explicit_VFX':True,'explicit_PostEffects':False,'inferred_requires_luminance_dynamics':False},'omitted_if_not_enabled':True,'target_metrics':{'target_size':'H64基準','camera_distance':'orthographicなので拡大率で拘束','screen_occupancy':'clipped_bounds_area/(viewport_width*viewport_height)。Hと実投影位置に従う設計量。画素占有率の実測値ではない。','readability_priority':'high'},'Image':{'spatial_envelope':'not_applicable: Video設計','local_contrast_budget':'not_applicable: Video設計'},'Video':{'temporal_envelope':d['timing'],'micro_variation':'none: 任意の点滅/微小変動を追加しない','anti_flicker':'高周波点滅を設計しない。実cadenceでの意図しないちらつきは未観察。'},'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','sampling_consequence':'実rAFの経過msで直接相を評価。フレーム番号の加算で時間を作らない。','AlphaBackground':{'enabled':False,'required_background_if_enabled':'#000000'},'alpha_ref':'LuminanceDynamicsModule.AlphaBackground','ActivationExclusions':{'non_emissive_particles_only':'no_auto_activation','grain_only':'no_auto_activation'},'Acceptance':{'mode_specific_envelope':True,'numeric_defaults_subordinate_to_target_metrics':True,'no_unwanted_global_luma_lift':True,'screen_processing_stays_in_observation_layer':True,'screen_signal_appearance_integrated_into_VFX_layers':True,'source_mask_stage_composite_and_sampling_defined':True,'unselected_operations_not_inferred':True,'physical_mechanism_not_asserted_without_source':True}},
  'VideoGenerationPolicy':{'Mode':'Video','Duration':{'source':'user_declared','seconds':2.2},'Style':intent['style'],'dataclass_forbidden':True,'timeline':{'unit':'seconds','tracks':{'PH':[{'id':pid,'start':0,'end':2.2,'state_before':'fieldなし','state_during':phs[pid]['StateDynamics']['state_space_extent'],'state_after':'field表示だけが終了。サーバー利益に触れない。'} for pid in phs],'OBS':[{'id':oid,'start':0,'end':d['sound_ms']/1000 if oid=='OBS4' else 2.2,'state_before':'寄与なし','state_during':obs[oid]['output_consequence'],'state_after':'寄与なし/再発音なし'} for oid in obs],'camera':[{'start':0,'end':2.2,'transform':'ホストのorthographic投影','state_before':'同じworld座標','state_during':'動いてもreceipt再発火なし','state_after':'Eの存否に関係なくホストが制御'}],'audio':[{'id':'OBS4','start':0,'end':d['sound_ms']/1000,'role':'専用一回SFX','state_before':'未予約','state_during':d['audio'],'state_after':'consumed; mute解除や再入場で再生しない'}],'dialogue':[]}},'ContinuityLedger':{'characters':'既存playerIdの参照のみ。新規人体なし。','costumes':'変更なし','light_sources':'PH1/PH2/PH3のfield放射','objects':d['object']+'一件と既存受け手。3区画はBのfield内部状態であり新しい貨幣物体ではない。','contacts':'物理接触/命中を追加しない。'},'ResponseAndSamplingChecks':{'PH_response_timescale_refs':[f'{pid}.StateDynamics.response_timescale' for pid in phs],'temporal_sampling_ref':'ObservationIntegrationTemplate.SamplingContract.temporal_sampling','OBS_sampling_consequence_refs':[f'{oid}.sampling_consequence' for oid in obs],'frame_cadence_and_exposure':'実rAF。露光積分なし。実フレーム時間は未計測。','observation_windows_fit_timeline':True,'longer_physical_response_state_at_video_end':'Aの20s利益とcooldownはサーバーの別時間軸。2200ms終端で消去しない。'},'DialoguePolicy':{'applies_if_declared':True,'required_sentence':'動画モデルは明示されているセリフを核に、自然な間・息継ぎ・演出音響を推測補完する','mora_guides':{'10s':30,'15s':45,'25s':75},'final_line_end_margin':.5,'application':'not_applicable: セリフ/BGMなし。'},'Acceptance':{'single_duration_source_of_truth':True,'all_tracks_within_duration':True,'response_timescale_and_OBS_sampling_checked_against_timeline':True,'character_costume_light_object_contact_continuity_checked':True}},
  'GlobalAcceptanceTemplate':{'Requirements':{'PhenomenonRegistry_required':True,'full_PH_structure_required':True,'all_8_domains_required':True,'ObservationRegistry_required_when_OBS_exist':True,'WindCapsule_required':True,'Gravity_required':True,'world_camera_screen_transform_required':True},'ValidationResults':{'StructuralInspection':{'status':'not_run','checks':{}},'SemanticReconciliation':{'status':'warning','checks':{'DeclaredIntent_preserved':'指定対象/値/源座標/寿命はcontracts.mjsへ固定。利益APIなし。','trigger_resolution':'VFX/E/PostEffects/LDM/Video設計のみ。人体/魔法preset/キーワード/反応は非起動。','exception_resolution':'実画素の未観察をPassへ置換しない。','source_binding':'OBS1は既存PH。SFXは同一原因ID。','scope_and_dependencies':'認証・真のserver時計・actor座標・原子的subscriber交換はホストが提供。実ゲームへの接続は未実行。','scientific_consistency':'非物質の提示fieldの近似として記述。実在の波動/材料/利益因果の実証ではない。m換算と実観測は未確認。'}},'RenderObservation':{'status':'not_run','evidence_source':'none','checks':{x:'not_run' for x in ['visual_causality','contour_preservation','clipping_crushing','chroma_detail','contact_projection','temporal_continuity','cue_discrimination_and_sampling']}}},'OutcomeEvaluation':{'intent_alignment':{'status':'not_run','evidence_refs':[],'rationale':'実GPU画素を観察していない。H64可読性を断定しない。'},'artistic_effect':{'status':'not_run','evidence_refs':[],'evaluator_basis':'not_run','strengths':'not_run','limitations':'技術再生・層数・静的テストは芸術的成功の根拠ではない。'}},'ComparativeEvaluation':{'status':'planned','question':'A/Bの独自性と暗明/H64/全寿命/速度差の可読性。旧Eは比較素材にしない。','changed_factor':'施設、背景、actor速度、receipt条件','controlled_conditions':'同一H64設定/2200ms。実GPU/ブラウザ/フレーム時刻はまだ揃えていない。','scene_set':'verification/scenario-matrix.json','repetitions_and_order':'各条件最低3回、順序を交替して人が評価する計画。未実施。','criteria':expression['must_communicate']+['glowを外しても主形を識別できる'],'evidence':'none','result_and_limitations':'ロジックの反復試験を画素比較の実証に数えない。'},'FinalStatus':{'specification_status':'Warning','render_status':'NotRun','failure_reasons':[]}}
 }
 return model
for key,d in DATA.items():dump(pathlib.Path('design')/f'{key}.B-Expression-2.json',make(key,d))
dump(pathlib.Path('provenance')/'B-source-revision.json',{
 'normative_authority':'この会話で受領した基底.md/拡張.md。リポジトリ現行版で会話指定を上書きしない。',
 'received_base_title':'Template Consolidated Edition / 表現意図・科学的適用・検証統合改訂 2026-09-11',
 'received_extension_title':'多層VFX・魔法構成章改訂 2026-09-23／Eコード分岐追記 2026-09-24',
 'repository':'player13579/B',**SOURCE,'repository_tree':'8bc0df41381ced1ae0647e7f6e5d402ad6ddfcb8',
 'verified_via':'GitHub connector: branch→commit→tree→各ファイルの1–15行とblob SHAを確認',
 'repository_blob_sizes':{'base':123327,'extension':75142},
 'entire_repository_blob_to_chat_byte_comparison':'not_run: 会話貼付全文とリポジトリblobのバイト同一性は検査していない。',
 'reference_source_code_copied':False,'old_effect_sources_read':False,'repository_writes':[]})
scenarios=[]
for key in DATA:
 for bg in ['dark','light']:
  for speed in [1,2]:
   for event in ['normal','duplicate','delayed','expired','offscreen','missing']:
    scenarios.append({'id':f'{key}-{bg}-{speed}-{event}','effect':key,'background':bg,'actor_speed':speed,'event':event,'H_backing_px':64,
     'lifetime_ms':2200,'sampling_plan_ms':list(range(0,2201,50)),'logic':'tests/motion.test.mjs','pixels':'not_run','hearing':'not_run',
     'reject_if':['起点/作用/結果を識別できない','主形がglow依存','A/Bが同形の色替え','原因不明の変化を証明済みと断定','二重発音/再発火']})
dump(pathlib.Path('verification')/'scenario-matrix.json',{'scenario_count':len(scenarios),'cases':scenarios,'additional_manual_checks':['glow off','reduced motion','同時A/B','入力源が画面外で受け手が画面内','通常muteと途中音量変更','device loss後に古い原因を再発火しない']})
print('2 full B designs, source revision, 48-scenario matrix written')
