import test from 'node:test';
import assert from 'node:assert/strict';
import {PHASE,GEOMETRY as G,H64_WORLD_TO_CSS,EFFECT_DURATION_SECONDS} from '../src/contract.mjs';
import {evaluatePhase,routePoint,routeRadius,sampleLightAtWorld} from '../src/phase.mjs';
import {sampleFields,receiverShape} from '../src/geometry.mjs';
import {fieldMasks,connectedComponentSizes} from '../tools/reference-utils.mjs';
const area=m=>m.reduce((s,v)=>s+v,0);
const intersection=(a,b)=>a.reduce((s,v,i)=>s+(v&&b[i]?1:0),0);
const union=m=>m.source.map((v,i)=>v||m.transport[i]||m.receive[i]);
// これらはCPU解析場の代理検査。H64実GPUの意味読解や芸術的合格ではない。
test('r0.2もduration正本は1.6所有者秒',()=>assert.equal(EFFECT_DURATION_SECONDS,1.6));
test('源を空にする時刻と輸送後端の出発が一致',()=>{assert.equal(PHASE.sourceDrainEnd,PHASE.tailStart);assert.equal(evaluatePhase(PHASE.tailStart).source,0);assert.equal(evaluatePhase(PHASE.tailStart).tail,0);});
test('前端の到着より前には蓄積量を増やさない',()=>{assert.equal(PHASE.travelEnd,PHASE.receiveStart);for(let i=0;i<=300;i++){const s=evaluatePhase(i/1000);assert.equal(s.received,0);}assert.ok(evaluatePhase(.31).received>0);});
test('Rが満たされるまで後端は受領先へ連続移動',()=>{assert.equal(PHASE.receiveEnd,PHASE.tailEnd);let prev=0;for(let i=0;i<=1000;i++){const s=evaluatePhase(i/1000);assert.ok(s.tail>=prev);assert.ok(s.tail<=s.front+1e-10);prev=s.tail;}});
test('源の初期面積はH64解析場で300pixelを上回る（代理検査）',()=>{for(const u of [0,.08,.16,.24])assert.ok(area(fieldMasks(u).source)>=300);});
test('輸送全区間はH64で少なくとも約11pxの厚みを持つ設計',()=>{for(let i=0;i<=100;i++)assert.ok(2*routeRadius(i/100)*H64_WORLD_TO_CSS>=11);});
test('初期供給中の源と輸送に接続面を残す',()=>{for(const u of [.08,.16,.24,.32,.40,.48,.56]){const m=fieldMasks(u);assert.ok(intersection(m.source,m.transport)>=12,`u=${u}`);}});
test('到着から輸送終了まで受領域と輸送に接続面を残す',()=>{for(const u of [.34,.40,.48,.56,.64,.68,.72]){const m=fieldMasks(u);assert.ok(intersection(m.transport,m.receive)>=8,`u=${u}`);}});
test('合成主形はH64解析場の引渡し区間で分断しない',()=>{for(let i=4;i<=150;i+=2){const sizes=connectedComponentSizes(union(fieldMasks(i/200)));assert.equal(sizes.length,1,`u=${i/200} sizes=${sizes}`);}});
test('受領量の増加に対し面積が減らず、色付き面を累積',()=>{let prev=0;for(let i=32;i<=76;i+=2){const n=area(fieldMasks(i/100).receive);assert.ok(n>=prev,`u=${i/100}`);prev=n;}assert.ok(prev>=600);});
test('source・transport・receiveが同時存在する引渡し時点',()=>{for(const u of [.4,.48,.56]){const m=fieldMasks(u);assert.ok(area(m.source)>=90);assert.ok(area(m.transport)>=300);assert.ok(area(m.receive)>=100);}});
test('輸送終了後も受領量と面積を保持してから収束',()=>{const a=area(fieldMasks(.77).receive);assert.equal(a,area(fieldMasks(.82).receive));assert.ok(area(fieldMasks(.92).receive)<a);});
test('收束光も源面の面積縮小に従い、広いglowだけ残さない',()=>{const point={phase:.8,worldX:0,worldY:0,seed:.5,reducedMotion:false};const full=sampleLightAtWorld(point,0,-61);const end=sampleLightAtWorld({...point,phase:.97},0,-61);assert.ok(end[1]<full[1]*.05);assert.deepEqual(sampleLightAtWorld({...point,phase:.97},35,-61),[0,0,0]);});
test('seedとreduced motionで経路・量・到着時刻を変えない',()=>{for(const u of [.1,.3,.5,.7,.9])for(const seed of [0,.5,1]){const a=evaluatePhase(u,false,seed),b=evaluatePhase(u,true,seed);assert.deepEqual(a.transportCenter,b.transportCenter);assert.equal(a.front,b.front);assert.equal(a.received,b.received);}});
test('包絡の外に主形も照明もない',()=>{for(const u of [0,.2,.4,.6,.8,.95])for(const [x,y]of [[-67,-60],[67,-60],[0,-128],[0,14]]){const s=sampleFields(x,y,u);assert.equal(s.source.opacity+s.transport.opacity+s.receive.opacity,0);assert.deepEqual(s.light,[0,0,0]);}});
test('u=1で全主形と放射が厳密にゼロ',()=>{for(let y=-127;y<=13;y+=7)for(let x=-66;x<=66;x+=6){const f=sampleFields(x,y,1);assert.equal(f.source.opacity+f.transport.opacity+f.receive.opacity,0);assert.deepEqual(f.light,[0,0,0]);}});
test('inletは足元中心から独立した外部物体ではなく受領面内',()=>{const p=routePoint(1),s=evaluatePhase(.6);assert.ok(receiverShape(p.x,p.y,s).distance<0);assert.equal(s.receiver.y,G.receiverY);});
test('小さな中央定常物だけの負対照は三段階代理条件を満たさない',()=>{const fake={source:new Uint8Array(128*112),transport:new Uint8Array(128*112),receive:new Uint8Array(128*112)};for(let y=58;y<62;y++)for(let x=62;x<66;x++)fake.receive[y*128+x]=1;assert.equal(area(fake.source)>0&&area(fake.transport)>0&&area(fake.receive)>=600,false);});
