/** ソースの梱包/参照検査。WGSLコンパイラや画素検査の代用ではない。 */
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {assembleShader} from '../src/shader-source.mjs';import {PHASE,GEOMETRY,EFFECT_DURATION_SECONDS} from '../src/contract.mjs';
const text=path=>readFile(new URL('../'+path,import.meta.url),'utf8');
test('WGSLへPHASEとGEOMETRYの全選択値を一度だけ展開する',async()=>{const s=assembleShader(await text('shaders/mana.wgsl'));for(const [prefix,values]of [['P',PHASE],['G',GEOMETRY]])for(const [key,value]of Object.entries(values)){const literal=`const ${prefix}_${key}:f32=${Number(value).toFixed(8)};`;assert.equal(s.split(literal).length-1,1);}const defs=new Set([...s.matchAll(/const ([PG]_\w+)/g)].map(x=>x[1]));for(const m of s.matchAll(/\b[PG]_\w+\b/g))assert.ok(defs.has(m[0]),m[0]);});
test('プレビューのDOM IDは存在し重複しない',async()=>{const html=await text('index.html'),js=await text('preview/main.mjs');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const m of js.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.includes(m[1]),m[1]);assert.match(html,/id="phaseDetails" hidden/);});
test('実行経路はCPU参照描画・Canvas 2D・画像素材を読み込まない',async()=>{const paths=['src/controller.mjs','src/renderer.mjs','src/shader-source.mjs','src/engine.mjs','src/index.mjs','preview/main.mjs'];for(const p of paths){const s=await text(p);assert.doesNotMatch(s,/getContext\(['"]2d['"]\)|new Image\s*\(|createImageBitmap\s*\(/);assert.doesNotMatch(s,/import[^\n]+geometry\.mjs|(?:from|import)[^\n]+reference-utils/);assert.doesNotMatch(s,/fetch\([^\n]+\.(?:png|jpe?g|webp)/i);}assert.match(await text('src/renderer.mjs'),/getContext\('webgpu'\)/);});
test('静的GPU検査ページと手動受入記録は同梱される',async()=>{const html=await text('tests/verify.html'),js=await text('tests/gpu-tests.mjs');assert.match(html,/gpu-tests\.mjs/);assert.match(js,/H64SemanticReadability:'not_run'/);assert.match(js,/phaseSampleCount:161/);assert.match(await text('docs/ACCEPTANCE.md'),/not_run/);});
test('packageと正式B設計のduration正本に差異がない',async()=>{const b=JSON.parse(await text('design/mana-receive.B-Expression-2.json'));assert.equal(b.ECodeImplementation.source_and_time_contract.serialized_duration_seconds,EFFECT_DURATION_SECONDS);assert.equal(b.FoundationOperationTemplate.OutputContract.operation,'design_only');assert.match(JSON.parse(await text('package.json')).version,/^0\.2\./);});
