/** Deterministic scalar graph emitter. No eval, dynamic imports of input code, or external dependencies. */
import {writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {FUNCTIONS,VERSION,SHAPE} from '../barrier-pro-model.mjs';
const root=new URL('../',import.meta.url), check=process.argv.includes('--check');
const input=await readFile(new URL('barrier-pro-model.mjs',root));
const digest=createHash('sha256').update(input).digest('hex');
const header=`// GENERATED from barrier-pro-model.mjs. ${VERSION}\n// Source SHA256 ${digest}. Run node tools/build-shader.mjs; DO NOT edit this file.\n`;
const structs=new Map(FUNCTIONS.filter(f=>f.returns!=='f32').map(f=>[f.returns,Object.keys(f.result)]));
let js=header+`const {abs,min,max,exp,sin,cos,sqrt}=Math;\nconst clamp=(x,a,b)=>max(a,min(b,x));\nconst select=(a,b,c)=>c?b:a;\nconst mix=(a,b,t)=>a+(b-a)*t;\nexport const MODEL_SHA256='${digest}';\n`;
let wgsl=header+[...structs].map(([s,fields])=>`struct ${s} { ${fields.map(x=>`${x}:f32`).join(',')}, };`).join('\n')+'\n';
for(const f of FUNCTIONS){
  if(!/^[A-Za-z]\w*$/.test(f.name))throw new Error('Invalid function name');
  js+=`export function ${f.name}(${f.args.join(',')}) {\n`;
  wgsl+=`fn ${f.name}(${f.args.map(x=>`${x}:f32`).join(',')})->${f.returns} {\n`;
  for(const [name,expression] of f.body){js+=`  const ${name}=${expression};\n`;wgsl+=`  let ${name}=${expression};\n`;}
  js+=`  return ${f.returns==='f32'?f.result:'{'+Object.entries(f.result).map(([k,v])=>`${k}:${v}`).join(',')+'}'};\n}\n`;
  wgsl+=`  return ${f.returns==='f32'?f.result:f.returns+'('+Object.values(f.result).join(',')+')'};\n}\n`;
}
const suffix=await readFile(new URL('tools/shader-entry.wgsl',root),'utf8');
wgsl+=suffix.replaceAll('$NU$',String(SHAPE.nu)).replaceAll('$NV$',String(SHAPE.nv));
for(const [file,text] of [['barrier-pro-kernel.mjs',js],['barrier-pro.wgsl',wgsl]]){
 if(check){if(await readFile(new URL(file,root),'utf8')!==text)throw new Error(`${file} is out of sync with canonical model`);}
 else await writeFile(new URL(file,root),text);
}
console.log(JSON.stringify({mode:check?'check':'build',status:'pass',sourceSHA256:digest}));
