import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),D=read('design/b-design.json'),rows=[];
const test=(name,ok,detail='')=>rows.push({name,status:ok?'pass':'failed',detail});
const fields=(obj,keys,p)=>{for(const key of keys.split(' '))test(`${p}.${key}`,obj!=null&&Object.hasOwn(obj,key));};
fields(D,'InferenceExpansionPolicy FoundationOperationTemplate PlatonicGoodTemplate PhenomenonSystemTemplate PEMTemplate CoordinateGravityWindTemplate OctaDomainTemplate AnimeStudiesTemplate ObservationIntegrationTemplate ExtremumDesignColorTemplate ReflectionClosureTemplate PhenomenonProfileTemplate TermsTemplate GlobalAcceptanceTemplate ExtensionActivationTable VFX PostEffects LuminanceDynamicsModule ECodeImplementation','root');
const reg=D.PhenomenonSystemTemplate.PhenomenonRegistry,ph=D.PhenomenonSystemTemplate.PhenomenonBlock,obs=D.ObservationIntegrationTemplate.ObservationRegistry;
test('registry/block key一致',JSON.stringify(Object.keys(reg))===JSON.stringify(Object.keys(ph)));
const domainKeys=['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience'];
for(const [id,p] of Object.entries(ph)){
 test(`${id}.identity`,JSON.stringify(p.identity)===JSON.stringify(reg[id]));
 fields(p,'identity DeepStructure PhysicalModel ScaleRegime OctaDomain PerceptualReadability GeometryConstraint StateDynamics Couplings CausalityLinks Evidence SurroundingChanges VisualProjection BeautyStructureApplication AcceptanceCriteria FailurePatterns',id);
 fields(p.DeepStructure,'Core Structure Surface',id+'.deep');
 fields(p.PhysicalModel,'model_kind system_boundary state_variables inputs balance_conditions constitutive_response initial_condition boundary_conditions approximation_scope',id+'.physics');
 for(const q of ['mass','momentum','energy','charge']){const b=p.PhysicalModel.balance_conditions[q];test(id+'.balance.'+q,['applicable','not_applicable'].includes(b?.status)&&b.balance_or_reason.length>12);}
 fields(p.ScaleRegime,'characteristic_length characteristic_time dominant_balance dimensionless_reasoning detail_cutoff',id+'.scale');
 for(const domain of domainKeys){const d=p.OctaDomain.Domains[domain];test(id+'.'+domain,!!d&&Array.isArray(d.items)&&d.items.length>0&&d.evidence_or_constraint.length>10);if(d?.applicability==='not_applicable')test(id+'.'+domain+'.latent',d.role==='latent');if(d?.role==='primary')test(id+'.'+domain+'.two_items',d.items.length>=2);}
 fields(p.PerceptualReadability,'direct_evidence indirect_evidence figure_ground_separation edge_legibility perceptual_failure_risk cue_roles confusable_alternative disambiguating_evidence viewing_conditions',id+'.perception');
 fields(p.GeometryConstraint,'surface_orientation normal_field_coherence curvature_behavior silhouette_logic contact_relation spatial_relation',id+'.geometry');
 fields(p.StateDynamics,'state_space_extent transition_path_character local_stability_type convergence_behavior damping_profile oscillation_pattern equilibrium_recovery transition_failure_risk driving_input response_timescale phase_relation stability_condition',id+'.dynamics');
 fields(p.Couplings.CausalAssessment,'intervention predicted_response competing_explanation uncertainty check_status evidence_refs',id+'.causality');
 test(id+'.uncertainty',p.Couplings.CausalAssessment.check_status==='hypothesis_only'&&p.Couplings.CausalAssessment.evidence_refs.length===0);
 fields(p.VisualProjection,'role world_state_ref retained_cues simplification omission_scope exaggeration_scope ambiguity_scope intent_ref',id+'.projection');
 test(id+'.GTB',Object.keys(p.GTBConnections).length>=2);
 const axes=Object.values(p.BeautyStructureApplication.axes);test(id+'.beauty_constraints',axes.length>=2&&axes.every(a=>a.length>=2));
 for(const l of p.CausalityLinks.physical_influence)test(id+'.physical_link',!!reg[l.source]&&!!reg[l.target]&&l.mechanism.length>10&&l.consequence.length>10);
 if(p.identity.visibility==='visible')test(id+'.visible',p.Evidence.direct.length>=2);else test(id+'.indirect',p.Evidence.indirect.length>=1&&p.CausalityLinks.physical_influence.length>0);
}
const valid=x=>Object.hasOwn(reg,x)||Object.hasOwn(obs,x)||['display_condition','optical_condition'].includes(x);
for(const [id,o] of Object.entries(obs)){fields(o,'operation_type input_references target_mask stage composite_method intensity protected_regions output_consequence dependencies sampling_consequence',id);test(id+'.resolved',o.dependencies.every(valid)&&o.input_references.every(valid));}
const active=new Set(),done=new Set();function dfs(x){if(active.has(x))return false;if(done.has(x))return true;active.add(x);for(const v of obs[x]?.dependencies??[])if(obs[v]&&!dfs(v))return false;active.delete(x);done.add(x);return true;}test('OBS DAG',Object.keys(obs).every(dfs));
fields(D.CoordinateGravityWindTemplate,'WorldApplicability Units WorldCoordinates CameraCoordinates ScreenCoordinates TransformChain ContactCoordinates VectorField Gravity WindCapsule','coordinates');
fields(D.ObservationIntegrationTemplate.SamplingContract,'output_resolution intended_display_scale spatial_detail_policy temporal_sampling filter_and_resample_policy','sampling');
const layers=D.VFX.layers,byId=Object.fromEntries(layers.map(l=>[l.layer_id,l]));test('VFX unique/world',Object.keys(byId).length===layers.length&&layers.some(l=>l.domain==='world'));
for(const l of layers){fields(l,'layer_id role domain selection PH_refs OBS_refs function_and_visible_result spatial_structure material_and_optics motion_and_phase integration',l.layer_id);test(l.layer_id+'.separate',l.domain==='world'?l.PH_refs.every(x=>!!reg[x])&&l.PH_refs.length>0&&l.OBS_refs.length===0:l.OBS_refs.every(x=>!!obs[x])&&l.OBS_refs.length>0&&l.PH_refs.length===0);fields(l.spatial_structure,'anchor_and_transform extent_orientation_depth macro meso micro edge_and_occlusion',l.layer_id+'.space');fields(l.material_and_optics,'carrier_and_mechanism emission_opacity_density color_and_light_response model_refs',l.layer_id+'.material');fields(l.motion_and_phase,'driver_and_transport distribution_and_correlation onset_peak_decay state_and_sampling_refs',l.layer_id+'.time');}
for(const l of D.VFX.interlayer_links)test('layer endpoints/direction',byId[l.source_layer]&&byId[l.target_layer]&&l.source_layer!==l.target_layer&&(l.relation_type!=='observation_dependency'||byId[l.source_layer].domain==='observation'));
test('active extensions only',['VFX','PostEffects','LDM','ECodeImplementation'].every(k=>D.ExtensionActivationTable.entries[k])&&!D.MagicArchitecture&&!D.CharacterPolicy&&!D.VideoGenerationPolicy);
test('posteffects exact',D.PostEffects.trigger.ordinary_posteffects===false&&D.PostEffects.selection.mode==='exact_selected_operations');
test('clipping explicit departures',D.ObservationIntegrationTemplate.IntensityBudget.intentional_departures.length===2);
const contract=D.FoundationOperationTemplate.OutputContract;test('B Image/design only',contract.schema_version==='B-Expression-2'&&contract.mode==='Image'&&contract.operation==='design_only');
test('render not run accurately',D.GlobalAcceptanceTemplate.ValidationResults.RenderObservation.status==='not_run'&&D.GlobalAcceptanceTemplate.FinalStatus.render_status==='NotRun');
const mapping=read('foundation/rule-evidence.json'),seen=new Set();for(const row of mapping.rules){test('rule unique '+row.rule_id,!seen.has(row.rule_id));seen.add(row.rule_id);const ok=row.source_locations.every(loc=>fs.existsSync(path.join(root,loc.path))&&fs.readFileSync(path.join(root,loc.path),'utf8').includes(loc.marker));test('rule source '+row.rule_id,ok);row.result.source_link_check=ok?'pass':'failed';test('rule method '+row.rule_id,fs.existsSync(path.join(root,row.verification_method)));}
function allFiles(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(f=>f.isDirectory()?allFiles(path.join(p,f.name)):[path.join(p,f.name)]);}
for(const f of allFiles(root).filter(p=>p.endsWith('.mjs'))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});test('JS syntax '+path.relative(root,f),r.status===0,r.stderr);}
const failed=rows.filter(r=>r.status==='failed'),report={schema:'DVA-v5-structural',status:failed.length?'failed':'pass',total:rows.length,passed:rows.length-failed.length,failed:failed.length,scope:'パッケージ専用静的構造/参照存在/JS構文。原本validator・GPU・芸術性は検査しない。',canonicalValidator:'not_run',shaderCompilation:'not_run',visualAcceptance:'not_run',checks:rows};
fs.writeFileSync(path.join(root,'evidence/structural-check.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(root,'foundation/rule-evidence.json'),JSON.stringify(mapping,null,2)+'\n');
D.GlobalAcceptanceTemplate.ValidationResults.StructuralInspection={status:failed.length?'fail':'pass',checks:{required_blocks:'evidence/structural-check.json',rule_contracts:'正本参照はrule-evidence.json、対応markerの存在のみ検査。',PH_OBS_separation:'registry/依存方向を検査。',OctaDomain:'全PHの8領域と非適用理由。',scientific_fields:'構造存在だけを検査。実物理の実証ではない。',coordinate_gravity_wind:'保持ブロックと投影契約を確認。',template_consolidation:'独立二重テンプレートなし。'}};
D.GlobalAcceptanceTemplate.FinalStatus.specification_status=failed.length?'Fail':'Warning';fs.writeFileSync(path.join(root,'design/b-design.json'),JSON.stringify(D,null,2)+'\n');console.log(JSON.stringify({status:report.status,total:report.total,passed:report.passed,failed:failed.length,failures:failed},null,2));process.exitCode=failed.length?1:0;
