"""Canonical schema instantiation from technical rules only; no past effect input."""
from pathlib import Path
import json, hashlib, subprocess
own=Path(__file__).resolve().parent
repo=own.parents[3]
canonical=repo/'outputs/request-20260930/sol61-barrier-zero/r1/b-source'
schema=json.loads((canonical/'scripts/design_contract.json').read_text(encoding='utf-8'))
def seed(s):
    if 'constant' in s:return s['constant']
    if 'object' in s:return {k:seed(v) for k,v in s['object'].items() if not v.get('optional')}
    if 'array' in s:return []
    if 'values' in s:return {}
    return None
def merge(a,b):
    for k,v in b.items():
        if isinstance(v,dict) and isinstance(a.get(k),dict):merge(a[k],v)
        else:a[k]=v
    return a
d={k:seed(s) for k,s in schema['baseline'].items()}
merge(d,{
 'FoundationOperationTemplate':{'OutputContract':{'schema_version':'B-Expression-2','mode':'Video','operation':'design_only'},'RuleContract':{'fields':['rule_id','owner','priority','applies_when','requirement','exception_to','validation_id'],'same_priority_resolution':'explicit_exception_or_compatible_union','unresolved_conflict_result':'spec_conflict'},'GlobalInterpretation':{'world_registry':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registry':'ObservationIntegrationTemplate.ObservationRegistry'}},
 'InferenceExpansionPolicy':{'DeclaredIntent':{'character_count':1,'character_attributes':{'actor':'実playerIdの既存原画・姿勢・属性を保持。新人体や動作なし。'},'main_action':'成功producerが通知したバイブコーディング生成／書換行為','main_objects':['実actor','三片から連結する仮想コード場'],'background':'本編既存world。変更／適応しない。','style':'デジタル立体コードの組立と実行','text_logo_policy':'可読コード文字・ラベルに意味を代用しない'},'ExpressionIntent':{'source':'user_declared','purpose':'生成行為に固有の因果とデジタル主形','must_communicate':['記述片の成立→連結→実行→有限解体'],'preserve_ambiguity':['具体的な取得物／対象の効果量は別producerが所有'],'allowed_omission':['物品の外観','未提供のターゲット命中'],'allowed_exaggeration':['仮想コードの立体形態と強発光'],'protected_relations':['元actorと実source位置','同causeと共有E clock']},'SelectionLifecycle':{'stages':['producer/source確定','geometry/optics選択','native層別比較','品質判断'],'world_registry':'PH1/PH2','observation_registry':'OBS1/OBS2','adoption_checks':['rootが実GPU／品質／本編／採用を別受入']},'inferred_support_elements':{'default_permission':'未宣言物体を増やさず既存行為を属性具体化','allowed_domains':['既存source周囲の仮想場と観測光学'],'allowed_scope':'一つのaction receiptの1200Ems'}},
 'PlatonicGoodTemplate':{'Good':'成功producerの行為を改変せず生成・書換の意味を保つ','Truth':{'coordinate_continuity':'原丸めx/y→actualcamera→同submission。actor移動でsourceを偽装しない。','physical_causality':'declared_fantasy状態から放射→既存actor受光→観測。実物理生成の証明としない。','state_transition_readability':'0/160/320成立、480..900実行、900..1180解体'},'Beauty':{'boundary_readability':'太い分岐と開口、接合順が主役','gaze_circulation':'sourceactor→接合域→実行前線→有限解体','structural_separation':'world材質／emission／近光／lensを別出力'}},
 'CoordinateGravityWindTemplate':{'Units':'worldゲーム座標とH64 body相対長。角度rad、Ems。','WorldCoordinates':'x右、y下。event x/yは足元worldsource。局所z前向き。','CameraCoordinates':'actual camera変換。局所x投影=x+.35z,y投影=y-.24z。','ScreenCoordinates':'pixel x右y下、viewportとDPR。','TransformChain':{'order':['event world','actualcamera','sourcePx','Hscaled localprojection'],'world_to_camera':'本編world camera矩陣をhostが供給','camera_to_screen':'actualviewport。正規化localHをpixelへ変換'},'ContactCoordinates':'物体命中なし。三仮想片の共有接合域のみ。','VectorField':'記述片のクリップ前線と接合実行順。風で運ばない。','Gravity':{'condition':'normal','vector':[0,1,0],'strength':'ゲームworld既存。仮想場はsource拘束で落下しない。','affected_responses':['元actorの姿勢は既存ゲームが所有'],'evidence':'本Eは重力／body motionを変更しない'},'WindCapsule':{'required':True,'medium_state':'既存環境。風入力なし。','medium_properties':'空気や粒子の輸送を仮定しない。','Field':{'direction':[0,0,0],'speed':0,'gust':0,'shear':0,'turbulence':0},'ApplicableResponses':{'body':'姿勢原本保持','cloth':'原本保持、新風なし','hair':'原本保持、新風なし','loose_elements':'仮想片は記述clock駆動','environment':'地形・texture変更なし'},'non_applicable_responses_explicit':'風粒子／布／髪の新運動はこのEに不適用'},'WorldApplicability':{'status':'applicable','reason':'既存actorと局所仮想場のworld PH'}},
 'PEMTemplate':{'Mode':'源と局所連結構造の因果可読性','CausalMesh':{'gaze_path_A':['PH1','PH2'],'gaze_path_B':['PH2','PH1'],'gaze_target_policy':'standard','adjustment_reason':'実actorと記述接点を順に読む','physical_mesh_required':True}},
 'AnimeStudiesTemplate':{'KeyframeSnapshot':'160/480/760/1080Ems。前後の組立／解体を追える。','Layout':'H64 actorは一人、主構造中心(.20,-.50)H、開口を保持','PoseActing_or_SceneActing':'元actor姿勢を維持。新しい手動作を制作しない。','MotionReadability':'三片が接合し実行が順序伝達、最後に解体する','CompositeIntegration':'rear→原actor→front。frontをbody alphaで全消去しない'},
 'PhenomenonProfileTemplate':{'ApplicabilityGuide':{'selections':[]},'Profiles':{}},
 'ReflectionClosureTemplate':{'Applicability':'actor原材質の局所拡散受光のみ。床や鏡面reflectionの新geometry入力なし。','ReflectionClosureBlock':{}},
 'TermsTemplate':{'Acceptance':d['TermsTemplate']['Acceptance']},
})
facts=[('PH1','既存sourceactorと原材質の局所応答','実playerId原actor','既存worldsource丸めx/yと元body','rigid_or_articulated','原姿勢／crop／alphaを変えず、源近傍の局所受光だけが応答。'),('PH2','分岐記述片が接合して実行される仮想コード場','成功action receipt','sourceから(.20,-.50)Hを中心','declared_fantasy','三開放forkを0/160/320Emsで記述し、480..900接合実行、900..1180解体。')]
phdef=schema['baseline']['PhenomenonSystemTemplate']['object']['PhenomenonBlock']['values']
registry={};blocks={}
for id,name,origin,anchor,model,mechanism in facts:
    identity={'id':id,'name':name,'origin':origin,'anchor':anchor,'visibility':'visible','local_state_difference':mechanism,'partition_reason':'既存材質の受光と生成する仮想場は異なる境界／状態の系。内部前線をPH水増ししない。'}
    p=seed(phdef);p['identity']=identity
    p['DeepStructure']={'Core':'成功行為の同causeとsource拘束' if id=='PH2' else '既存人体の原姿勢／材質','Structure':mechanism,'Surface':'PH2は厚み.12H、背骨／枝幅.10Hの開放プリズム。PH1は実originalRGB/alpha。'}
    p['PhysicalModel']={'model_kind':model,'system_boundary':'source半径145はeventmetadata、実E支持はsource局所box[-.9,-1.4,1.3,.4]H。','state_variables':'記述成立率、実行包絡、解体率、coverage、radiance' if id=='PH2' else '原RGB/alpha、姿勢、入射照明','inputs':'same effect-id/source Eage/rate／実alpha遮蔽／相対光位置','balance_conditions':{q:{'status':'not_applicable','balance_or_reason':'仮想コード場の宣言機構。実質量／電荷／力／エネルギーの生成を科学的事実と主張しない。原actorの力学は既存ゲーム所有。'} for q in ['mass','momentum','energy','charge']},'constitutive_response':mechanism,'initial_condition':'sourceは原body、仮想片の登録0','boundary_conditions':'成功receipt有限1200Ems、live visual<1180、source invisible/expiryでzero','approximation_scope':'ゲーム表現。医療／錬金術／実世界の生成機構の実証ではない。'}
    p['ScaleRegime']={'characteristic_length':'H64、fork .52H長／.12H厚、receiver実body','characteristic_time':'1200Ems、160ms記述、480..900実行','dominant_balance':'仮想場のclock状態と光学coverage','dimensionless_reasoning':'H比でgeometryを固定、age/1200で寿命を固定。rateはclock一回。','detail_cutoff':'H64で.10Hの枝、stars半長6/4px。細かいノイズなし。'}
    domains={}
    for domain in ['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience']:
        applicable=domain in ['Optics','Materials','SurfaceScience'];role='primary' if domain=='Optics' else 'supporting' if applicable else 'latent'
        descriptions={'Thermo':'熱発生・温度を定義していない。色を熱の証拠にしない。','Fluid':'気流・液体・粒子輸送なし。記述面はclockで成立。','Optics':'材質RGB/alpha、透過extinction1.8/Hと別emission/sourceSignal。','Materials':'既存body実材質／仮想SDF表面。opacityとemission独立。','Electromagnetics':'コード場は実電荷／電磁力の実証なし。電撃へ置換しない。','Rheology':'粘性流れ／弾性変形なし。剪断を捏造しない。','WaveOptics':'世界の干渉場を登録しない。回折像は別OBS2の観測モデル。','SurfaceScience':'源位置と実actor表面の局所距離応答。floor/mirrorなし。'}
        items=[descriptions[domain]]
        if role=='primary':items.append('sourceOFFでradiance/received/postをzero、直線RGBを一度encodeする。')
        domains[domain]={'applicability':'applicable' if applicable else 'not_applicable','role':role,'items':items,'evidence_or_constraint':('kernel.mjs worldFS/receiverFS、actualbodySurfaceのCPU契約。native未実施。' if applicable else descriptions[domain])}
    p['OctaDomain']=domains
    p['PerceptualReadability']={'direct_evidence':mechanism,'indirect_evidence':'sourceOFF/receiverOFF/mainonlyの差でsourceと役割を分ける','figure_ground_separation':'開口と厚い接合域を保つ。背景でgainを変えない。','edge_legibility':'H64太い枝、mainonly/fullcombined両方で接合が残る','perceptual_failure_risk':'panel／propeller／armour／haloへの退化','cue_roles':[{'cue':'三片成立→連結→実行→解体','supports':'生成・書換行為','reliability_and_overlap':'glow/starを外してもmainの因果が残る必要'}],'confusable_alternative':'取得物／防護／回復の形','disambiguating_evidence':'永久外装や完成itemでなく一回の組立実行で有限に消える','viewing_conditions':'actual H64、dark/light、通常rate、途中倍率変更'}
    p['GeometryConstraint']={'surface_orientation':'三片は120°差、local厚み.12H','normal_field_coherence':'boxSDFの境界／内部は同じdensity場','curvature_behavior':'角を持つ分岐片。勝手に丸haloへ平滑化しない。','silhouette_logic':'閉じたcontainerではなく三方向の開放fork接合','contact_relation':'実itemとの接触は無し。仮想片は共有接合域。','spatial_relation':'rear/body/frontと同submittedsource。新人体変形なし。'}
    p['StateDynamics']={'state_space_extent':'一つのreceipt1200Ems、render live0..1180','transition_path_character':'monotonic','local_stability_type':'stable','convergence_behavior':'記述成立→連結保持→解体zero','damping_profile':'各解除smoothstep、sourceexpiry即zero','oscillation_pattern':'none','equilibrium_recovery':'仮想場消滅、原bodyへ戻る','transition_failure_risk':'後半が粒子だけ／位相を飛ばす','driving_input':'受信済み成功receipt＋normalizedEage','response_timescale':'160ms組立、140ms接合実行順','phase_relation':mechanism,'stability_condition':'singleclock/seenreceipt/sourcecurrent'}
    p['Couplings']={'DominantCouplings':['PH2.Optics→PH1.Optics：実表面拡散受光'],'SecondaryCouplings':[],'CausalAssessment':{'intervention':'source/main/receiver/near/flare/star OFF、実source/observer移動、遮蔽','predicted_response':'各依存先だけ変わり原姿勢は同じ','competing_explanation':'fakealpha／古いclock／飾りlens','uncertainty':'nativepixel／聴感未実施','check_status':'planned','evidence_refs':[]}}
    p['CausalityLinks']={'physical_influence':[{'source':'PH2','target':'PH1','mechanism':'仮想場放射から実表面へ局所入射','consequence':'PH1姿勢不変で局所材質応答'}],'observation_dependency':[{'source':'OBS1','target':'PH2','basis':'放射像の有限near PSF'},{'source':'OBS2','target':'PH2','basis':'実接点sourceSignalとobserverを参照'}],'gaze_path':[{'source':'PH1','target':'PH2','reason':'actor生成行為から組立域を追う'}]}
    p['Evidence']={'direct':['HANDOFF native全寿命matrixを予定'],'indirect':['CPU-CHECK geometry/source/clockを品質と分離'],'candidates':['sourceOFF／OBS比較／actualbodyfixture']}
    p['SurroundingChanges']={'entries':[{'target':'PH1','change':'source入射に応じた局所拡散受光'}],'latent_reference_target':'PH2' if id=='PH1' else 'PH1'}
    p['VisualProjection']={'role':'主生成構造' if id=='PH2' else '実sourceactorの受光','world_state_ref':id+'.StateDynamics','retained_cues':['fork開口','接合順','有限消滅'],'simplification':'noise/microglyphなし','omission_scope':['未知target結果'],'exaggeration_scope':['強発光と立体コード'],'ambiguity_scope':['レシピ結果は別receipt'],'intent_ref':'InferenceExpansionPolicy.ExpressionIntent'}
    p['BeautyStructureApplication']={'conform_to':'PlatonicGoodTemplate.BeautyStructuring','target_policy':'standard','adjustment_reason':'三方向分岐と一回の実行を読む','axes':{'ratio_proportion':['H相対長／太い枝'],'structural_separation':['材質/放射/OBS別'],'causal_continuity':['同receiptclock']}}
    p['FailurePatterns']=['panel／halo／propellerだけに見える','接合の意味がglowで消える','sourceの無いSFX']
    registry[id]=identity;blocks[id]=p
d['PhenomenonSystemTemplate']['PartitionPolicy']={'criterion':'既存actor受光と生成される場の系境界','shared_condition_policy':'同viewport/source/clock/IntensityBudget','no_discipline_based_split':True};d['PhenomenonSystemTemplate']['PhenomenonRegistry']=registry;d['PhenomenonSystemTemplate']['PhenomenonBlock']=blocks
ops={'OBS1':{'operation_type':'source-bound near PSF','input_references':['PH2'],'target_mask':'source局所scissor、emissionのみ','stage':'E-only observer HDR','composite_method':'linear additive alpha0','intensity':'25tap half8px、nearGain.45','protected_regions':['元world/actor geometry'],'output_consequence':'実源近傍へ光が広がる','dependencies':[],'sampling_consequence':'H64-scaled kernel、DPRactual'},'OBS2':{'operation_type':'chosen lens diffraction field','input_references':['PH2','optical_condition'],'target_mask':'各実接点からhalf10/7px、actualsource alpha','stage':'E-only observer HDR','composite_method':'linear additive alpha0','intensity':'.42*actualsourceSignal、37度固定軸、observer偏位で長さ変化','protected_regions':['原world/actor/source形'],'output_consequence':'源から観測レンズへ結び付いた短い回折','dependencies':[],'sampling_consequence':'fixedangle、source/C移動とopaqueOFFをnative観察'}}
merge(d,{'ObservationIntegrationTemplate':{'ObservationRegistry':ops,'SamplingContract':{'output_resolution':'actual sharedviewport/DPR','intended_display_scale':'actualH64、DPR1/2','spatial_detail_policy':'fork幅.10H、star半長6/4px','temporal_sampling':'usualcontinuous＋HANDOFF20断面、wall/E時刻','filter_and_resample_policy':'sourceemission半浮動HDR、linearPSF、oneoutputencode'},'IntensityBudget':{'intentional_departures':[]},'CompositeValidation':{k:'not_tested' for k in d['ObservationIntegrationTemplate']['CompositeValidation']}},'ExtremumDesignColorTemplate':{'PEV':{'candidate_state_set':['480連結成立','760実行後半','1080解体'],'selected_physics_extremum':'760接合経路の有限実行','reason':'実際の生成行為を抽象化し結果を捏造しない'},'AES':{'selected_from_PEV_only':True,'visual_circulation':'actor→三分岐→接合→解除','asymmetric_balance':'source中心から(.20,-.50)Hの非対称body周辺','tension_release':'片がつながる緊張→実行→解体','body_environment_consonance':'原actor/床保持、局所光のみ','selected_aesthetic_extremum':'760の連結実行'},'CCM':{'Palette':'cyanblueの深さgradient＋白い実行芯','ColorDynamics':'色相は深さ依存、時間は同causeの輝度包絡','Lighting':'[14,14,12]linear芯、near.45','BackgroundBinding':'既存背景保持、色によるgain調整なし','PerceptualControl':'shape/openingと接合の意味を守る、白ピーク禁止なし'}}})
g=d['GlobalAcceptanceTemplate'];merge(g,{'ValidationResults':{'StructuralInspection':{'status':'planned','checks':['公式完全schema／CPU境界']},'SemanticReconciliation':{'status':'planned','checks':['源/PH/OBS/位相/code対応']},'RenderObservation':{'status':'not_run','evidence_source':'native未実施'}},'FinalStatus':{'render_status':'NotRun'},'OutcomeEvaluation':{'intent_alignment':{'status':'not_run','evidence_refs':[],'rationale':'native未実施'},'artistic_effect':{'status':'not_run','evidence_refs':[],'evaluator_basis':'実H64全寿命を後続Sol判断','strengths':'設計仮説のみ','limitations':'native/聴感/本編未実施'}},'ComparativeEvaluation':{'status':'planned','question':'main/OBS/actor受光が生成実行の因果を強めるか','changed_factor':'near/flare/sparkle/receiverの個別OFF','controlled_conditions':'sameevent/source/Eage/H64/rate/viewport','scene_set':'全46variantと主要negativecontrols','repetitions_and_order':'各OFF→restore、全寿命連続','criteria':'生成接合実行解体が主形で読める','evidence':'HANDOFF検証計画','result_and_limitations':'未実施'}})
for ext in ['CharacterPolicy','VFX','PostEffects','LuminanceDynamicsModule','ECodeImplementation']:d[ext]=seed(schema['extensions'][ext])
merge(d,{'CharacterPolicy':{'trigger':'既存humanactorを描くhost。新人物生成なし。','GeneralCharacter':{'character_id':'actor','declared_attributes':'actualplayer原画・姿勢・skinを保持。属性を新presetで上書きしない。','male_expression_policy':'既存原画が男性なら既存表現を保持'}},'ECodeImplementation':{'trigger':'executable_runtime_E_code_explicit','output_kind':'executable_effect_source_not_image_generation','source_revision':{'commit':'37eb4bdfe59f0dc075f9b4333b7d6af76b784a88','base_blob':'8a908495ae1f9b7175e00384ab88c50e5c78bd43','extension_blob':'0eda016558e426ff4142d850d26200b40fafd834'},'target_runtime':'shared-device WebGPU pass record only','source_and_time_contract':'contract.mjs exact46 producer receipt/normalized1200Ems','world_PH_refs':['PH1','PH2'],'observation_OBS_refs':['OBS1','OBS2'],'implementation_artifacts':['artist.mjs','contract.mjs','kernel.mjs','sfx.mjs'],'applicable_rule_evidence':'RULE-CODE-EVIDENCE.json','validation':{'syntax_and_shader':'not_run','actual_GPU_pixels_and_timing':'not_run','game_event_and_SFX':'not_run'}},'LuminanceDynamicsModule':{'trigger':{'explicit_VFX':True,'explicit_PostEffects':False,'inferred_requires_luminance_dynamics':True},'target_metrics':{'target_size':'H64','camera_distance':'actualcamera投影','screen_occupancy':'sourcebox[-.9,-1.4,1.3,.4]H','readability_priority':'fork開口と接合経路'},'Video':{'temporal_envelope':'0/160/320成立、480..900実行、900..1180解体','micro_variation':'none、因果以外のちらつきなし','anti_flicker':'analytic smoothstep／sameclock、nativecontinuous未確認'},'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','sampling_consequence':'H64で枝6.4px、ray24steps/half','AlphaBackground':{'enabled':False,'required_background_if_enabled':'不適用、actualworldへ合成'},'alpha_ref':'premultmaterial、observeralpha0','ActivationExclusions':{'non_emissive_particles_only':False,'grain_only':False}}})
v=d['VFX'];merge(v,{'trigger':'explicit','world_registration':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registration':'ObservationIntegrationTemplate.ObservationRegistry','design_intent':{'subject_and_action':'バイブコーディング生成／書換の行為','expression_intent_ref':'InferenceExpansionPolicy.ExpressionIntent','primary_read':'三片から一構造への接合・実行・解体','layering_basis':'主立体、接点、actor受光、near/lensは異なる機能'},'layers':[],'interlayer_links':[],'causal_path':{'input':'exact successful producer action receipt','carrier_PH':'PH2','receiver':'PH1','ScaleRegime_ref':'PH2.ScaleRegime','StateDynamics_ref':'PH2.StateDynamics','ReactivePhaseChange_ref':'不適用、実化学生成／相変化なし'},'orchestration':{'common_time_basis':'normalized1200Ems、rate一回','layer_phase_relations':'三片160ms差、実行140ms差、finite解体','environment_response':'actor実材質のみ局所受光','visual_hierarchy':'main開口→実行芯→stars→OBS','bullet_time':'不適用、実actorE倍率のみ'},'output_integration':{'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','LDM_ref':'LuminanceDynamicsModule','composite_order':'rear/body/front/receiver/star→source-boundOBS','color_alpha_contract':'linearHDR、materialpremult、radiance/OBSalpha0、oneencode','scale_adaptation':'H比、元shape/三片数/有限因果保持'},'validation_plan':{'layer_checks':'mainonly/receiver/star/near/flareOFF各actualnative','composite_checks':'actor前後とactualalpha、sourceOFF exactbase','temporal_checks':'normalcontinuous＋20断面、rate変更、expiry','actual_results_ref':'GlobalAcceptanceTemplate.ValidationResults'}})
layerdef=schema['extensions']['VFX']['object']['layers']['array']
for lid,role,domain,ph,obs,meaning in [('L1','primary_form','world',['PH2'],[],'三開放forkが一つの厚い連結構造へ'),('L2','boundary','world',['PH2'],[],'接合実行芯と37度の有限star'),('L3','environment_response','world',['PH1'],[],'元actorのsource局所材質応答'),('L4','observation_support','observation',[],['OBS1','OBS2'],'源に束縛したnearとレンズ回折')]:
    l=seed(layerdef);merge(l,{'layer_id':lid,'role':role,'domain':domain,'selection':{'basis':'attribute_resolved','scope_and_reason':meaning},'PH_refs':ph,'OBS_refs':obs,'function_and_visible_result':meaning,'spatial_structure':{'anchor_and_transform':'actualsourcePx/H、camera/body登録保持','extent_orientation_depth':'fork.52H、厚み.12H、120度三方向。OBSは有限10px域。','macro':meaning,'meso':'背骨と二枝／共有接合／ray前後厚み','micro':'細grain／microglyphなし。stars6/4px半長。','edge_and_occlusion':'rear/body/frontとactualforegroundalpha'},'material_and_optics':{'carrier_and_mechanism':'PH2 declaredcode/PH1 originalsurface/OBS sourcecamera','emission_opacity_density':'extinction1.8/H、alpha別、linear白芯14','color_and_light_response':'cyanblue深さgradient、局所受光、PSFnear','model_refs':'PH1/PH2 models, OBS1/2'},'motion_and_phase':{'driver_and_transport':'normalizedEage、source固定','distribution_and_correlation':'三片／接点star3、同clock','onset_peak_decay':'0/160/320成立、480..900実行、1180OFF','state_and_sampling_refs':'PH2.StateDynamics／commonSamplingContract'},'integration':{'composite_and_mask':'actualalpha、3HDRMRT、E-onlypost','protected_cues':'原body／接合開口／finite','failure_to_avoid':'粒子だけ／panel／古いsource／vacuouslens'}});v['layers'].append(l)
v['interlayer_links']=[{'source_layer':'L1','target_layer':'L3','relation_type':'physical_influence','mechanism_and_consequence':'コード場から原actorへの局所照明','foundation_binding':'PH2→PH1'},{'source_layer':'L1','target_layer':'L4','relation_type':'observation_dependency','mechanism_and_consequence':'radiance/sourceSignalからnear/lens','foundation_binding':'OBS1/2 input PH2'}]
# Exact PostEffects structure is schema seeded; selected operations have real scope/mapping.
merge(d['PostEffects'],{'ordinary_posteffects':False,'selection':{'mode':'exact_selected_operations','operations':['near PSF','chosen observer diffraction'],'basis':'attribute_resolved','scope_and_reason':'既存強sourceの観測応答、装飾全体filterなし'}})
# Keep canonical nested ancillary structures when the concrete decision was given as prose.
def restore_nested(value,definition):
    if 'constant' in definition:return definition['constant']
    if 'object' in definition:
        if not isinstance(value,dict):
            statement='；'.join(map(str,value)) if isinstance(value,list) else str(value)
            return {k:restore_nested(statement,c) for k,c in definition['object'].items() if not c.get('optional')}
        for k,c in definition['object'].items():
            if k in value:value[k]=restore_nested(value[k],c)
        return value
    return value
for name,definition in schema['baseline'].items():d[name]=restore_nested(d[name],definition)
for p in blocks.values():
    p['Couplings']['CausalAssessment']['check_status']='hypothesis_only'
    p['VisualProjection']['role']='essential' if p['identity']['id']=='PH2' else 'supporting'
    p['BeautyStructureApplication']['axes']={'ratio_proportion':['H64幅と厚み','.10Hの枝と開口'],'structural_separation':['source／receiverの系境界','world／OBSの合成所有']}
v['interlayer_links'][1]['source_layer']='L4';v['interlayer_links'][1]['target_layer']='L1'
merge(d['CoordinateGravityWindTemplate'],{'Units':{'length':'H相対、worldゲーム座標','time':'Ems、音のwall秒を区別','temperature':'入力なし、熱を描かない','pressure':'入力なし、圧力を描かない','angle':'rad'},'WorldCoordinates':{'handedness':'local右手系、ゲームmapx右y下','X':'右','Y':'下','Z':'観測者側','camera_forward':'local-z','origin':'immutableevent丸めsourcex/y'},'CameraCoordinates':{'X':'右','Y':'下','forward':'local-z','projection':'x+.35z,y-.24z','FOV_or_scale':'actualcameraとbodyH'},'ScreenCoordinates':{'domain':'actualviewportpixels、normalizedscreen[0,1]','x':'右','y':'下'},'ContactCoordinates':{'contact_patch':'仮想片の共有域、現物命中なし','contact_normal':'boxSDF境界の向き','support_relation':'source拘束、原actor足元を維持'},'VectorField':{'dominant_vector':{'direction':'三fork各localYの記述前線','magnitude':'160msで全長成立','falloff':'finiteboundaryclip','fluctuation':'none'},'secondary_vector':{'direction':'0→1→2接合実行順','magnitude':'140ms各接点遅れ','falloff':'各260ms有限応答','fluctuation':'none'}},'WindCapsule':{'medium_properties':{'density':'未入力、輸送なし','viscosity':'未入力、輸送なし'},'non_applicable_responses_explicit':True}})
merge(d['AnimeStudiesTemplate'],{'KeyframeSnapshot':{'phase':'action_peak','state_t_minus_1_evidence':'三片成立','state_t_evidence':'760Ems接合実行','state_t_plus_1_evidence':'900..1180Ems解体'},'Layout':{'staging':'H64原actorと三方向の局所コード構造','projection_consistency_ref':'CoordinateGravityWindTemplate.TransformChain','whitespace_role':'fork開口と接合域を読む'},'PoseActing_or_SceneActing':{'character_ref':'actor','object_balance':'source拘束、実itemを増やさない','contact_logic':'原body足元登録と仮想片接合'},'MotionReadability':{'motion_blur_smear_speed_line_policy':'未指定なので不採用','primary_causality_replacement_by_motion_effects':False},'CompositeIntegration':{'observation_ref':'OBS1/OBS2','contact_shadow_used_for_integration':'新shadowなし、元actor/world shadow保持。光学受光のみ。'}})
merge(d['ReflectionClosureTemplate'],{'Applicability':{'applies_when':[],'otherwise':'actorの局所拡散受光はPH1。鏡面／floorreflectionなし、別reflection PHは作らない。'}})
d['BeautifulPoseCapsule']=seed(schema['extensions']['BeautifulPoseCapsule'])
merge(d['BeautifulPoseCapsule'],{'trigger':'既存actorの原姿勢を保持するreferencefixture','PoseType':'standing','PosePhase':'STATIC','Common':{'intent':'原actorの姿勢を維持。動作生成なし。','primary_axis':'元body縦軸','gaze_or_orientation':'元sprite方向','contact_points':['元actor足元'],'COM_or_support_center':'元sprite原画の支持中心','reaction_or_propulsion':'本Eから力学入力なし','limb_or_appendage_roles':'元手足。新関節動作なし。','recovery':'元spriteへ照明だけ戻る','PH_mechanics_refs':{'PhysicalModel':'PH1.PhysicalModel','ScaleRegime':'PH1.ScaleRegime','StateDynamics':'PH1.StateDynamics'},'static_dynamic_mechanics':{'mode':'原姿勢reference、gameのactualpose所有を変えない','static_balance_or_support':'既存足元／姿勢保持','momentum_propulsion_or_contact_change':'不適用、本Eは移動／姿勢を駆動しない'},'perceptual_readability_ref':{'PerceptualReadability':'PH1.PerceptualReadability','joint_and_contact_cues':['元alphaシルエット','原足元anchor']}}})
d['VideoGenerationPolicy']=seed(schema['extensions']['VideoGenerationPolicy'])
d['GradientAnchorPolicy']=seed(schema['extensions']['GradientAnchorPolicy'])
merge(d['GradientAnchorPolicy'],{'trigger':'hue_gradient_declared_or_accepted_inferred','gradient_type':'world_VFX_gradient','anchor':'PH2','registration':{'world_surface_gradient':'不採用、actor色模様を変えない','world_VFX_gradient':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_gradient':'不採用、画面filterなし'},'o9_ref':'不適用、prism画面加工を選ばない'})
d['GradientAnchorPolicy']['resolved_anchor_contract']={'selection':'attribute_resolved','anchors':[{'position':'localz back','linearRGB':[.13,.12,.54],'role':'奥側有色材質'},{'position':'localz front','linearRGB':[.03,.44,.60],'role':'手前有色材質'},{'position':'実行接点の境界、execute包絡','linearRGB':[14,14,12],'role':'別emissionの白い実行芯'}],'transition':'材質はz線形mix、第三白芯は境界と有限executeに因果接続。均等虹色帯なし。'}
tracks={'PH':[{'id':i,'start':0,'end':1.2,'state_before':'原body／仮想場zero','state_during':mechanism,'state_after':'原body、仮想場zero'} for i,_,_,_,_,mechanism in facts],'OBS':[{'id':i,'start':0,'end':1.18,'state_before':'sourcezero','state_during':op['output_consequence'],'state_after':'zero'} for i,op in ops.items()],'camera':[{'start':0,'end':1.2,'transform':'actualgamecamera','state_before':'既存camera','state_during':'actualcamera保持','state_after':'既存camera'}],'audio':[{'id':'finite-code-score','start':0,'end':1.2,'role':'記述→接合実行→解体','state_before':'silent','state_during':'新score、rate一回、同submission','state_after':'terminal0'}],'dialogue':[]}
merge(d['VideoGenerationPolicy'],{'Mode':'Video','Duration':{'source':'client magicEffectDuration fallback1200Ems','seconds':1.2},'Style':'デジタル立体の有限生成実行','timeline':{'unit':'seconds at reference rate1','tracks':tracks},'ContinuityLedger':{'characters':'元actor1','costumes':'原衣装','light_sources':'実三接点有限source','objects':'仮想三片、ゲーム物品追加なし','contacts':'仮想片接合、足元anchor保持'},'ResponseAndSamplingChecks':{'PH_response_timescale_refs':['PH1.StateDynamics','PH2.StateDynamics'],'temporal_sampling_ref':'ObservationIntegrationTemplate.SamplingContract','OBS_sampling_consequence_refs':['OBS1','OBS2'],'frame_cadence_and_exposure':'actualsubmittedframe時刻。連続提示は後続native。','longer_physical_response_state_at_video_end':'ゲーム結果は別owner。仮想場／OBS／SFX完全終端。'}})
merge(d['PostEffects'],{'trigger':{'ordinary_posteffects':False,'beta_targets':['既存sourceの属性具体化']},'selection':{'mode':'exact_selected_operations','scope_resolution':'source近傍PSFと選んだ観測レンズのみ','exact_selected_operations':['near PSF','OBS2 source/observer diffraction']},'autonomous_activation':{'registry':'ObservationIntegrationTemplate.ObservationRegistry','budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract'},'global_posteffects':{'applies':False,'exact_OBS_operations':[],'OBS_refs':[]},'local_posteffects':{'applies':True,'targets':['actualsourceの有限pixel域'],'exact_OBS_operations':['OBS1','OBS2'],'OBS_refs':['OBS1','OBS2']},'operation_contract':{'required_fields':['sourcePH','sourcealpha','observercentre','pixelmask','linearHDR','sameEclock'],'sampling_consequence':'H64-scalednear25taps／fixedanglelens、移動／遮蔽OFFnative'}})
# Every remaining scalar belongs to a canonical ancillary policy, not an omitted PH field.
# Resolve it to concrete section-specific conditions; no placeholders or schema summaries.
ancillary={
 'PlatonicGoodTemplate':'主形比.52H/.10H、120度三分岐、接合→実行→解体が因果と形の秩序。',
 'PEMTemplate':'actor→接合域の視線、局所sourceから主形へ読む。未知itemへ視線を誘導しない。',
 'ObservationIntegrationTemplate':'linear E-onlyHDRとactualsourcealpha、near.45/lens.42、H64全寿命OFF比較。元worldは変更しない。',
 'PostEffects':'属性具体化のnear PSFとOBS2回折だけ。source/observer/coverage/timeを使うkernel.observeFS、全画面filterなし。',
 'GlobalAcceptanceTemplate':'全寿命native／層OFF／normal聴感／実eventを別受入。未観察not_run、CPUでqualityを合格にしない。'}
merge(d,{'FoundationOperationTemplate':{'TemplateConsolidation':{'template_position':'chapter_end'}},'ExtremumDesignColorTemplate':{'DesignScience':{'VisualHierarchy':'三分岐の主輪郭→接合の芯→有限star→OBS。主形をglowで代用しない。','DensityPlan':'三片の支持は個別成立から一連結へ。内部粒子／noise carpetなし。','ShapeOrder':'.10Hの太い枝と開口が主幹。固定outline panelではなく時間で接合・解体する。','OrnamentFunction':'三接点starのみ実行完了を強める。源なしの飾りや別item像を足さない。'}}})
unresolved=[]
def finalize(node,path):
    if isinstance(node,dict):
        for k,v in node.items():
            if v is None:
                chapter=path.split('.')[0]
                if chapter not in ancillary:unresolved.append(path+'.'+k)
                else:node[k]=ancillary[chapter]
            else:finalize(v,path+'.'+k)
    elif isinstance(node,list):
        for i,v in enumerate(node):finalize(v,path+f'[{i}]')
for k,v in d.items():finalize(v,k)
if unresolved:raise ValueError('Unsettled canonical fields: '+str(unresolved))
text=json.dumps(d,ensure_ascii=False,indent=2)
(own/'b-expression-design.json').write_text(text+'\n',encoding='utf-8')
(own/'B-DESIGN.py').write_text('# 完全B設計。WebGPU実行翻訳はartist.mjs。画像生成命令ではない。\nprompt = '+repr(text)+'\n',encoding='utf-8')
command=['python',str(canonical/'scripts/validate_design.py'),str(own/'B-DESIGN.py'),'--character','--vfx','--posteffects','--min-ph','2']
r=subprocess.run(command,capture_output=True,text=True,encoding='utf-8')
print(r.stdout);print(r.stderr)
(own/'CANONICAL-VALIDATION.json').write_text(json.dumps({'command':command,'exitCode':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'status':'STRUCTURAL_PASS_ONLY' if r.returncode==0 else 'FAIL','scope':'完全schemaのみ。native／科学的真実／美的品質ではない。'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
raise SystemExit(r.returncode)
