import json, pathlib, hashlib, subprocess
p=pathlib.Path('outputs/request-20260930/sol61-barrier-zero/r9/attempts/b-expression-contract-a1'); source=p.parent.parent
sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
items=[
('InferenceExpansionPolicy.AttributeAndActionResolutionRule','InferenceExpansionPolicy','design.mjs: DESIGN/cells/cellState','User many-hex digital protection supplies topology; source-state timing settles otherwise unspecified cells. No fabricated collision direction.','CPU topology/lifecycle pass; native readability pending'),
('FoundationOperationTemplate.OutputAndReferenceResolutionRule','FoundationOperationTemplate','artist.mjs exports; RUNTIME-HANDOFF-ADDENDUM.md','Image/design_only serializes a parameterized reference-frame family; separately executable WebGPU E code; no raster generation.','canonical structural pass; runtime pending'),
('PlatonicGoodTemplate.BeautyStructuringRule','PlatonicGoodTemplate','design.mjs: field/cellState','72 cells form coherent enclosing structure; gaps/rims/insets carry protection and adjacent response.','CPU finite topology pass; aesthetic/user acceptance pending'),
('PhenomenonSystemTemplate.StateTransformerRule','PhenomenonSystemTemplate','design.mjs: cellState/field/focus/authoritativeState','Create registration, actual/contact-unknown response, break unregistration; surviving body and stable positive durability separate.','CPU lifecycle pass; GPU actual-pixels pending'),
('PhenomenonSystemTemplate.LinkTypeRule','PhenomenonSystemTemplate','world-shader.mjs world integration; post-shader.mjs visibleSource/optical/finish','PH world radiance supplies OBS near/aperture/display. OBS depends on PH, does not feed PH emission or move body.','typed structural pass; source read; OFF interventions pending'),
('PhenomenonSystemTemplate.PerceptualEvidenceDiscriminationRule','PhenomenonSystemTemplate','design.mjs: field; projection.mjs: uniformFloats','Cell boundary/inset is direct world evidence; source-bound optical image is indirect observer evidence.','H64 main/combined continuous and sampled phases pending'),
('PEMTemplate.PhenomenonEqualityMode','PEMTemplate','world-shader.mjs field integration; design.mjs: field/focus','Field interior/rims, body registration, and compact source remain simultaneous; source brightness is not a sole phenomenon replacement.','source-grounded design intention; native pending'),
('CoordinateGravityWindTemplate.CoordinateSystemDefinition','CoordinateGravityWindTemplate','design.mjs: view; projection.mjs: support/uniformFloats','Right-handed world +Z front; fixed orthographic positive-Z observer; source/body share receiver projection; no authored wind/gravity deformation.','CPU uniform/body hash pass; native registration pending'),
('OctaDomainTemplate.OctaDomainDefinition','OctaDomainTemplate','design.mjs: field; world-shader.mjs; sfx-score.mjs: score','Digital state topology/clock/emission/attenuation and finite sound are modeled. No chemical/magnetic/fluid response or stress solver is asserted; those domains explicitly held outside this mechanism.','applicability/source audit, not science validation'),
('AnimeStudiesTemplate.KeyframeSnapshotRule','AnimeStudiesTemplate','design.mjs: cellState/focus; body.png original fixture','Original body pose retained; sequential activation, contact receipt and collapse carry readable action timing without invented body motion.','finite CPU state pass; actual H64 timing pending'),
('ObservationIntegrationTemplate.LensFlareObservationCoordinates','ObservationIntegrationTemplate','post-shader.mjs: source/view/visibleSource/optical/encode','OBS1 near filters submitted world image; OBS2/3 source-bound cross/filled aperture with measured-source alpha; OBS4 final sRGB transfer. No lens-glass physical accuracy claim.','source mapping; GPU source-OFF/occlusion/move/observer-center pending'),
('ExtremumDesignColorTemplate.AESRule','ExtremumDesignColorTemplate','design.mjs: optics.white/field; post-shader.mjs: finish','Strong source and quiet blue enclosure; no blanket dimming, background darkening or clipped-white ban.','creative requirement, actual contrast/art quality pending'),
('ReflectionClosureTemplate.ReflectionVsLensFlareSeparation','ReflectionClosureTemplate','world-shader.mjs field/body integration; post-shader.mjs optical','World directional surface response and attenuation distinct from optional pupil artifact; OBS aperture is not object reflection.','declared-fantasy phenomenological model, not physical glass proof'),
('PhenomenonProfileTemplate.ProfileApplicabilityGuideRule','PhenomenonProfileTemplate','body.png unchanged fixture; design.mjs','No dynamic anatomy/cloth/fluid mechanism is authored. Receiver appearance stays fixed; full PH domain assessment remains. Empty specialized profiles reflect declared scope, not missing receiver.','independent applicability audit; no invented measurements'),
('TermsTemplate.Terms','TermsTemplate','design.mjs graphDistance/field; post-shader.mjs optical','Cell registration is digital-fantasy state, ray integration effective attenuation, ghost effective pupil response; these do not assert a material solver.','semantic terminology review'),
('GlobalAcceptanceTemplate.PassWarningFailEvaluation','GlobalAcceptanceTemplate','CPU-CHECK.json; CLOCK-CHECK.json; native fixture instructions','Structure/source CPU and intended acceptance requirements remain separate from not-run GPU/listening/user acceptance.','no automatic creative pass'),
('ECodeImplementation.ExecutableECodeBranchRule','ECodeImplementation','artist.mjs; e-clock-contract.mjs; RUNTIME-HANDOFF-ADDENDUM.md','Executable E plus validation artifacts; canonical absolute E clock feeds VFX/SFX once, fixed ACC2 rate2, gameplay durability unchanged.','7 clock + 3 semantic CPU pass; actual host rate2 pending'),
('VFX.MultilayerArchitectureRule','VFX','world-shader.mjs; design.mjs field; post-shader.mjs','Primary spatial hex registration, integrated emission/attenuation, source-dependent OBS layers; source/shell/body causal order preserved.','official --vfx structure pass; native quality pending'),
('VFX.ScreenSignalSurfaceRule','VFX','projection.mjs uniformFloats; world-shader.mjs MRT; post-shader.mjs finish','MRT sourceSignal and cell scissors constrain OBS; real actor quad/alpha required, no particle-only stand-in.','CPU buffer mapping; faithful adapter/GPU pending'),
('PostEffects.SPCARule','PostEffects','post-shader.mjs gaussian/finish/encode','Near Gaussian and manual display encoding selected with exact source/cause/scope; no automatic global bloom/grain/scanline coating.','official --posteffects structure pass; per-cell native pending'),
('LuminanceDynamicsModule.LDMModeRule','LuminanceDynamicsModule','design.mjs cellState/focus; sfx-score.mjs score','Finite E age gates source events; same normalized submitted clock/rate drives audio cursor; reference Image does not imply Video generation.','CPU clock/lifecycle pass; actual scheduling/listening pending'),
('CharacterPolicy.CharacterPolicyGeneralRule','CharacterPolicy/BeautifulPoseCapsule','body.png; projection.mjs actor gate','Existing Sophia body fixture retained without new body image, demographic substitution or forced body warp. Pose is receiver context.','immutable body hash verified; H64 actual quad pending')]
report={'B_commit':'37eb4bdfe59f0dc075f9b4333b7d6af76b784a88','scope':'Rule-specific authored-source translation audit. Evidence status is not a physical truth or artistic result.','entries':[dict(rule_id=a,contract=b,source=c,consequence=d,evidence=e)for a,b,c,d,e in items], 'wire_normalization':{'serialized_id':'id','serialized_discriminator':['type','variant'],'owners':'targetId for created/timed-bust-break; playerId for hit/durability-broken','serialized_break_type':'preparation-barrier-hit','helper_break_type':'durability-broken internal only','receipt_clock':'local startedAt; canonical eEffectNow absolute timestamp','no_serialized_claim':['eventId','causeId','startedAtMs','contact vector']},'approximations':['Hex lattice latitude/longitude ellipsoid projection may distort poles; actual H64 silhouette/aliasing pending','Fixed 64-step effective emission/attenuation integration is not validated physical transport','Gaussian/cross/filled-aperture OBS uses authored effective kernel, not a measured physical lens','Original bitmap body is static receiver, not dynamically modeled anatomy','Wire contact absent uses declared cell22; this is not a measured impact position'],'pending':['native complete lifecycle main-only/combined H64 on dark/light','actual per-cell OFF/observer/source interventions','actual host rate2 VFX/SFX scheduling and listening','user creative acceptance and adoption']}
(p/'RULE-CODE-EVIDENCE.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
checkout=pathlib.Path('outputs/request-20260930/sol61-dodge-zero/r1/input-provenance/b-foundation-checkout')
cmd=['python',str(checkout/'scripts/validate_design.py'),str(p/'b-expression-design.json'),'--vfx','--posteffects','--min-ph','3']
r=subprocess.run(cmd,capture_output=True,text=True);(p/'canonical-validator.log').write_text(r.stdout+r.stderr,encoding='utf8')
validation={'command':cmd,'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'candidate_sha256':sha(p/'b-expression-design.json'),'validator_sha256':sha(checkout/'scripts/validate_design.py'),'schema_sha256':sha(checkout/'scripts/design_contract.json'),'B_commit':report['B_commit'],'scope':'official structural-only instance validation; not science/cause truth, native quality, audio listening or adoption','status':'STRUCTURAL_PASS'if r.returncode==0 else'fail'}
(p/'CANONICAL-VALIDATION.json').write_text(json.dumps(validation,indent=2)+'\n',encoding='utf8');print(json.dumps(validation));assert r.returncode==0
