// Instance field/reference/implementation consistency checks. Not the official B validator, not artistic scoring.
import fs from 'node:fs';import {fileURLToPath} from 'node:url';import path from 'node:path';import {CONTRACT} from '../src/contract.js';import {sampleTime,PALETTE,LOBES} from '../src/sampler.js';import {GPU_CONTRACT} from '../src/gpu.js';
const root=fileURLToPath(new URL('..',import.meta.url)),file=path.join(root,'docs/B-Expression-2.json'),d=JSON.parse(fs.readFileSync(file,'utf8')),checks=[];
const check=(id,ok,evidence)=>checks.push({id,status:ok?'pass':'fail',evidence});
const fields=(obj,keys,id)=>keys.forEach(k=>check(`${id}.${k}`,obj!=null&&Object.hasOwn(obj,k),'Required field exists; semantics separately reviewed'));
fields(d,['FoundationOperationTemplate','InferenceExpansionPolicy','PlatonicGoodTemplate','PhenomenonSystemTemplate','PEMTemplate','CoordinateGravityWindTemplate','OctaDomainTemplate','AnimeStudiesTemplate','ObservationIntegrationTemplate','ExtremumDesignColorTemplate','ReflectionClosureTemplate','PhenomenonProfileTemplate','TermsTemplate','GlobalAcceptanceTemplate'],'root');
check('schema',d.FoundationOperationTemplate.OutputContract.schema_version==='B-Expression-2','Current serialization');
const ps=d.PhenomenonSystemTemplate,ph=ps.PhenomenonBlock,obs=d.ObservationIntegrationTemplate.ObservationRegistry,ids=Object.keys(ph),domains=['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience'];
check('registry-keys',JSON.stringify(Object.keys(ps.PhenomenonRegistry))===JSON.stringify(ids),'Concrete mappings, same world identities');
for(const [id,p] of Object.entries(ph)){
 check(`${id}.identity`,JSON.stringify(p.identity)===JSON.stringify(ps.PhenomenonRegistry[id]),'Includes matching partition reason');
 fields(p,['DeepStructure','PhysicalModel','ScaleRegime','OctaDomain','PerceptualReadability','GeometryConstraint','StateDynamics','Couplings','CausalityLinks','Evidence','SurroundingChanges','VisualProjection','BeautyStructureApplication','AcceptanceCriteria','FailurePatterns'],id);
 fields(p.DeepStructure,['Core','Structure','Surface'],`${id}.deep`);
 fields(p.PhysicalModel,['model_kind','system_boundary','state_variables','inputs','balance_conditions','constitutive_response','initial_condition','boundary_conditions','approximation_scope'],`${id}.model`);
 for(const quantity of ['mass','momentum','energy','charge']){const b=p.PhysicalModel.balance_conditions[quantity];check(`${id}.${quantity}`,['applicable','not_applicable'].includes(b.status)&&b.balance_or_reason.length>20,'Balances or explicit inapplicability');}
 fields(p.ScaleRegime,['characteristic_length','characteristic_time','dominant_balance','dimensionless_reasoning','detail_cutoff'],`${id}.scale`);
 fields(p.StateDynamics,['state_space_extent','transition_path_character','local_stability_type','convergence_behavior','damping_profile','oscillation_pattern','equilibrium_recovery','transition_failure_risk','driving_input','response_timescale','phase_relation','stability_condition'],`${id}.dynamics`);
 fields(p.PerceptualReadability,['direct_evidence','indirect_evidence','figure_ground_separation','edge_legibility','perceptual_failure_risk','cue_roles','confusable_alternative','disambiguating_evidence','viewing_conditions'],`${id}.perception`);
 for(const domain of domains){const v=p.OctaDomain.Domains[domain];check(`${id}.${domain}`,v&&['applicable','not_applicable'].includes(v.applicability)&&['primary','supporting','latent'].includes(v.role)&&v.items.length>0&&v.evidence_or_constraint.length>0,'Expanded domain with reason/evidence');if(v.applicability==='not_applicable')check(`${id}.${domain}.latent`,v.role==='latent','No forced mechanism');if(v.role==='primary')check(`${id}.${domain}.items`,v.items.length>=2,'Selected primary mechanisms, not added objects');}
 const c=p.Couplings.CausalAssessment;fields(c,['intervention','predicted_response','competing_explanation','uncertainty','check_status','evidence_refs'],`${id}.causal`);check(`${id}.causal-status`,c.check_status==='hypothesis_only'&&c.evidence_refs.length===0,'Design causal model is not experimental evidence');
 check(`${id}.evidence`,p.Evidence.direct.length>=2,'Distinct proposed cues, not assumed independent');
 check(`${id}.beauty-axes`,Object.keys(p.BeautyStructureApplication.axes).length>=2&&Object.values(p.BeautyStructureApplication.axes).every(v=>v.length>=2),'Structure evidence is not an artistic score');
 check(`${id}.GTB`,Object.keys(p.GTBConnections).length>=2,'At least two GTB layers');
 for(const [type,links] of Object.entries(p.CausalityLinks))for(const l of links){if(type==='physical_influence')check(`${id}.physical-link`,!!ph[l.source]&&!!ph[l.target]&&l.mechanism.length>0&&l.consequence.length>0,JSON.stringify(l));if(type==='observation_dependency')check(`${id}.OBS-link`,!!obs[l.source]&&!!ph[l.target],JSON.stringify(l));}
}
const validRef=r=>!!ph[r]||!!obs[r]||['display_condition','optical_condition'].includes(r);
for(const [id,o] of Object.entries(obs)){fields(o,['operation_type','input_references','target_mask','stage','composite_method','intensity','protected_regions','output_consequence','dependencies','sampling_consequence'],id);check(`${id}.refs`,[...o.dependencies,...o.input_references].every(validRef),'Registered dependencies only');}
let cycle=false;const visiting=new Set(),done=new Set();function visit(id){if(visiting.has(id)){cycle=true;return;}if(done.has(id))return;visiting.add(id);for(const r of obs[id].dependencies)if(obs[r])visit(r);visiting.delete(id);done.add(id);}Object.keys(obs).forEach(visit);check('OBS-DAG',!cycle,'Dependent → input arrows, acyclic');
check('PH-OBS-separated',!Object.keys(obs).some(id=>ph[id]),'No optical filter registered as world PH');
fields(d.CoordinateGravityWindTemplate,['WorldApplicability','WorldCoordinates','CameraCoordinates','ScreenCoordinates','TransformChain','Gravity','WindCapsule'],'coordinates');check('wind',d.CoordinateGravityWindTemplate.WindCapsule.Field.speed==='0 m/s','Calm, no invented wind VFX');
fields(d.ObservationIntegrationTemplate.SamplingContract,['output_resolution','intended_display_scale','spatial_detail_policy','temporal_sampling','filter_and_resample_policy'],'sampling');
const expected=['VFX','PostEffects','LDM','BeautifulPoseCapsule','GradientAnchorPolicy','VideoGenerationPolicy'];check('extensions',JSON.stringify(Object.keys(d.ExtensionActivationTable.entries).sort())===JSON.stringify(expected.sort()),'Only six applicable extensions');
for(const e of Object.values(d.ExtensionActivationTable.entries))for(const block of e.output_blocks)check(`active.${block}`,!!d[block],'Selected module has one instance');
check('no-preset-keyword',!d.CharacterPolicy&&!d.KeywordExpansion,'No human preset or keyword auto expansion for calibration proxy');
const lids=new Set(d.VFX.layers.map(l=>l.layer_id));check('unique-layers',lids.size===d.VFX.layers.length,'No duplicate layer ID');
for(const l of d.VFX.layers){check(`layer.${l.layer_id}`,l.domain==='world'?l.PH_refs.length>0&&l.PH_refs.every(id=>ph[id])&&l.OBS_refs.length===0:l.OBS_refs.length>0&&l.OBS_refs.every(id=>obs[id])&&l.PH_refs.length===0,'World/OBS refs not mixed');fields(l.spatial_structure,['anchor_and_transform','extent_orientation_depth','macro','meso','micro','edge_and_occlusion'],l.layer_id);}
for(const l of d.VFX.interlayer_links)check(`layer-link.${l.source_layer}.${l.target_layer}`,lids.has(l.source_layer)&&lids.has(l.target_layer)&&l.source_layer!==l.target_layer,'Actual layer endpoints');
check('duration-binding',d.VideoGenerationPolicy.Duration.seconds*1000===CONTRACT.durationMs&&CONTRACT.minimumMs===900,'Design/runtime contract share 1500ms default and 900ms minimum');
check('ABI',GPU_CONTRACT.vertexStride===64,'Actual runtime vertex ABI');check('source-budget',GPU_CONTRACT.sourceIntensity===3.6&&GPU_CONTRACT.bloomGain===0.42,'Separate strong source and local observation coefficient');
check('flux-weights',Math.abs(LOBES.reduce((s,v)=>s+v.weight,0)-1)<1e-12,'Finite normalized quantity');
for(const t of [0,400,850,1380,1500]){const s=sampleTime(t);check(`quantity.${t}`,Math.abs(s.external+s.stored-1)<1e-12,'No resource loss during optical fade');}
for(const [track,entries] of Object.entries(d.VideoGenerationPolicy.timeline.tracks))for(const [i,e] of entries.entries()){check(`timeline.${track}.${i}`,e.start>=0&&e.end<=1.5&&e.start<=e.end,'Common actor duration');fields(e,['state_before','state_during','state_after'],`timeline.${track}.${i}`);}
const ga=d.GlobalAcceptanceTemplate;check('render-unobserved',ga.ValidationResults.RenderObservation.status==='not_run'&&ga.FinalStatus.render_status==='NotRun','No actual GPU observation has been claimed');check('outcome-unobserved',ga.OutcomeEvaluation.intent_alignment.status==='not_run'&&ga.OutcomeEvaluation.artistic_effect.status==='not_run','CPU images cannot pass artistic/GPU review');check('production',ga.FinalStatus.production_connection_approved===false,'Game adoption is separate');
function walk(v){if(Array.isArray(v)){v.forEach(walk);return;}if(v&&typeof v==='object'){check('fully-expanded',!Object.hasOwn(v,'$ref'),'No unresolved shared references');Object.values(v).forEach(walk);return;}if(typeof v==='string'){const m=v.match(/^(PH\d+|OBS\d+)(?:\.([A-Za-z0-9_.]+))?$/);if(m){let r=ph[m[1]]??obs[m[1]];for(const k of m[2]?.split('.')??[])r=r?.[k];check(`field-ref.${v}`,r!==undefined,'Resolvable field reference');}}}walk(d);
const report={release:'r0.4',scope:'Local field/enum/ref/DAG/runtime-binding inspection; not official B validator, physical proof, GPU execution or quality score',passed:checks.filter(c=>c.status==='pass').length,failed:checks.filter(c=>c.status==='fail').length,checks};
if(process.argv.includes('--record')){fs.writeFileSync(path.join(root,'qa/design-checks.json'),JSON.stringify(report,null,2)+'\n');if(!report.failed){ga.ValidationResults.StructuralInspection={status:'pass',checks:{required_blocks:'Local field inspection: qa/design-checks.json',rule_contracts:'Source rules referenced; no claim of official validator coverage.',PH_OBS_separation:'Registry endpoints and dependency DAG checked.',OctaDomain:'8 fields, reasons, roles and primary item count checked.',scientific_fields:'Full model/scale/dynamics/cue/causal fields present; not a physics proof.',coordinate_gravity_wind:'Coordinate chain, calm air and ordinary host gravity conditions retained.',template_consolidation:'Single keyed instance for each selected module.'}};fs.writeFileSync(file,JSON.stringify(d,null,2)+'\n');}}
console.log(JSON.stringify({passed:report.passed,failed:report.failed,failures:checks.filter(c=>c.status==='fail')},null,2));if(report.failed)process.exitCode=1;
