// GENERATED from barrier-pro-model.mjs. barrier-pro-r0.2
// Source SHA256 1c73eddc5de500b8940bdec77c909b912ca151d1f10d4652193c0fad28f0eceb. Run node tools/build-shader.mjs; DO NOT edit this file.
struct Envelope { kind:f32,r:f32,eventOn:f32,visible:f32,createFront:f32,drainFront:f32,load:f32,dent:f32,breakWidth:f32,breakScale:f32,residueGain:f32,core:f32, };
struct Point { x:f32,y:f32,z:f32, };
struct Field { r:f32,g:f32,b:f32,a:f32,coverage:f32,core:f32,emissionY:f32,normalX:f32,normalY:f32,normalZ:f32,stress:f32,formed:f32, };
fn sat(x:f32)->f32 {
  return clamp(x,0.0,1.0);
}
fn ramp(a:f32,b:f32,x:f32)->f32 {
  return sat((x-a)/(b-a));
}
fn softStep(a:f32,b:f32,x:f32)->f32 {
  let t=ramp(a,b,x);
  return t*t*(3.0-2.0*t);
}
fn sq(x:f32)->f32 {
  return x*x;
}
fn gauss(x:f32)->f32 {
  return exp(-x*x);
}
fn tri(x:f32)->f32 {
  return max(0.0,1.0-abs(x));
}
fn widthAt(v:f32)->f32 {
  return 0.25+0.20*ramp(0.0,0.10,v)+0.15*ramp(0.10,0.25,v)+0.04*ramp(0.25,0.58,v)-0.10*ramp(0.72,0.87,v)-0.26*ramp(0.87,1.0,v);
}
fn keel(v:f32)->f32 {
  return 0.10-0.13*ramp(0.0,0.43,v)+0.18*ramp(0.43,0.78,v)-0.07*ramp(0.78,1.0,v);
}
fn capAt(v:f32)->f32 {
  return min(1.0,min(v/0.14,(1.0-v)/0.14));
}
fn duration(kind:f32)->f32 {
  return select(650.0,480.0,kind>=2.0);
}
fn envelope(requested:f32,age:f32,authority:f32)->Envelope {
  let eventOn=select(0.0,1.0,requested>=0.0 && requested<=3.0 && age>=0.0 && age<duration(requested));
  let kind=select(-1.0,requested,eventOn>0.5);
  let r=sat(age/duration(requested));
  let visible=select(0.0,1.0,eventOn>0.5 || authority>0.5);
  let createFront=0.12+0.84*r;
  let drainFront=0.96-0.82*r;
  let load=0.24+0.76*exp(-3.2*r);
  let dent=0.033+0.105*exp(-2.6*r);
  let breakWidth=0.016+0.054*r;
  let breakScale=1.0-0.14*r-0.32*ramp(0.68,1.0,r);
  let residueGain=1.0-0.53*ramp(0.60,1.0,r);
  let core=select(select(select(0.0,0.45+0.45*sin(3.141592653589793*r),kind==0.0),0.13+0.79*exp(-3.6*r),kind==1.0),0.84*exp(-4.0*r),kind==2.0);
  return Envelope(kind,r,eventOn,visible,createFront,drainFront,load,dent,breakWidth,breakScale,residueGain,core);
}
fn stressAt(q:f32,v:f32,iq:f32,iv:f32,r:f32)->f32 {
  let known=select(0.0,1.0,iv>=0.0);
  let cq=select(0.02,iq,known>0.5);
  let cv=select(0.55,iv,known>0.5);
  let wx=select(0.62,0.44,known>0.5)+0.12*r;
  let wy=select(0.24,0.19,known>0.5)+0.09*r;
  return gauss((q-cq)/wx)*gauss((v-cv)/wy);
}
fn tearMain(q:f32,v:f32)->f32 {
  let teeth=0.027*tri((q+0.53)/0.13)-0.022*tri((q+0.06)/0.11)+0.036*tri((q-0.42)/0.16);
  return v-(0.49+0.19*q+teeth);
}
fn tearBranch(q:f32,v:f32)->f32 {
  return q-(-0.18+0.35*(v-0.49)+0.09*tri((v-0.76)/0.10));
}
fn geometry(q:f32,v:f32,requested:f32,age:f32,authority:f32,iq:f32,iv:f32,front:f32)->Point {
  let e=envelope(requested,age,authority);
  let w=widthAt(v);
  let k=keel(v);
  let slope=select((q-k)/(1.0-k),(k-q)/(1.0+k),q<k);
  let dome=max(0.0,1.0-slope)*max(0.0,capAt(v));
  let x0=(-0.025+0.045*v)+q*w;
  let y0=(v-0.5)*1.24;
  let fill=1.0-softStep(e.createFront-0.10,e.createFront+0.10,v+0.075*q);
  let stress=stressAt(q,v,iq,iv,e.r);
  let expansion=select(1.0,0.86+0.14*e.r,e.kind==0.0);
  let collapse=select(1.0,e.breakScale,e.kind==2.0);
  let depth=select(0.23,0.29,front>0.5);
  let depthGain=select(select(select(1.0,0.26+0.74*fill,e.kind==0.0),1.0-0.55*e.r,e.kind==2.0),1.0-0.77*e.r,e.kind==3.0);
  let dent=select(0.0,e.dent*stress*capAt(v),e.kind==1.0 && front>0.5);
  let signZ=select(-1.0,1.0,front>0.5);
  let z=signZ*max(0.0,depth*dome*depthGain-dent);
  let shear=select(0.0,0.022*e.load*stress*(1.0-q*q),e.kind==1.0);
  let buckling=select(0.0,0.06*e.r*tearMain(q,v),e.kind==2.0);
  return Point(x0*expansion*collapse+shear,y0*collapse-buckling,z*collapse);
}
fn material(q:f32,v:f32,requested:f32,age:f32,authority:f32,iq:f32,iv:f32,front:f32,hPx:f32,coreOn:f32,yaw:f32,pitch:f32)->Field {
  let e=envelope(requested,age,authority);
  let g=geometry(q,v,requested,age,authority,iq,iv,front);
  let gqx=geometry(q+0.001,v,requested,age,authority,iq,iv,front);
  let gqy=geometry(q-0.001,v,requested,age,authority,iq,iv,front);
  let gvx=geometry(q,min(0.9999,v+0.001),requested,age,authority,iq,iv,front);
  let gvy=geometry(q,max(0.0001,v-0.001),requested,age,authority,iq,iv,front);
  let tx=gqx.x-gqy.x;
  let ty=gqx.y-gqy.y;
  let tz=gqx.z-gqy.z;
  let ux=gvx.x-gvy.x;
  let uy=gvx.y-gvy.y;
  let uz=gvx.z-gvy.z;
  let cx=ty*uz-tz*uy;
  let cy=tz*ux-tx*uz;
  let cz=tx*uy-ty*ux;
  let norm=max(0.000000001,sqrt(cx*cx+cy*cy+cz*cz));
  let nx=cx/norm;
  let ny=cy/norm;
  let nz=cz/norm;
  let viewDot=abs(sin(pitch)*ny+cos(pitch)*(-sin(yaw)*nx+cos(yaw)*nz));
  let facet=clamp(0.61+0.26*nx+0.17*ny+0.15*nz,0.30,0.98);
  let rim=softStep(0.67,0.97,abs(q));
  let cap=max(0.0,capAt(v));
  let path=0.58+0.30*(1.0-viewDot)+0.22*rim+0.10*(1.0-cap);
  let aa=max(0.002,0.60/(hPx*1.24));
  let fillCoord=v+0.075*q;
  let fill=1.0-softStep(e.createFront-0.030,e.createFront+0.030,fillCoord);
  let joinBand=gauss((fillCoord-e.createFront)/0.045);
  let stress=stressAt(q,v,iq,iv,e.r);
  let mainCrack=tearMain(q,v);
  let sideCrack=tearBranch(q,v);
  let branchGate=softStep(0.49,0.56,v);
  let crackA=softStep(e.breakWidth-aa,e.breakWidth+aa,abs(mainCrack));
  let crackB=1.0-branchGate*(1.0-softStep(1.65*e.breakWidth-aa,1.65*e.breakWidth+aa,abs(sideCrack)));
  let breakMask=crackA*crackB;
  let cut=e.drainFront+0.065*q;
  let drainMask=1.0-softStep(cut-aa,cut+aa,v);
  let drainBand=gauss((v-cut+0.022)/0.037);
  let coverage=e.visible*select(select(1.0,breakMask,e.kind==2.0),drainMask,e.kind==3.0);
  let formed=select(1.0,0.47+0.53*fill,e.kind==0.0);
  let lateGain=select(1.0,e.residueGain,e.kind==2.0);
  let tau=path*select(0.19,0.43,front>0.5)*formed*lateGain;
  let alpha=coverage*(1.0-exp(-tau));
  let baseR=0.048+0.084*facet;
  let baseG=0.25+0.40*facet;
  let baseB=0.43+0.42*facet;
  let backGain=select(0.63,1.0,front>0.5);
  let volumeGain=(0.62+0.38*facet)*(0.62+0.38*cap)*(1.0-0.35*rim)*backGain;
  let stateLum=select(select(select(1.0,0.64+0.36*fill,e.kind==0.0),1.0+0.35*e.load*stress,e.kind==1.0),1.05*lateGain,e.kind==2.0);
  let emitR=0.030*volumeGain*stateLum;
  let emitG=0.260*volumeGain*stateLum;
  let emitB=0.320*volumeGain*stateLum;
  let loadPatch=select(0.0,e.load*stress,e.kind==1.0);
  let joinPatch=select(0.0,joinBand,e.kind==0.0);
  let drainPatch=select(0.0,drainBand,e.kind==3.0);
  let foldPatch=select(0.0,gauss((abs(mainCrack)-e.breakWidth-0.025)/0.040),e.kind==2.0);
  let k=keel(v);
  let coreQ=select(k,select(0.02,iq,iv>=0.0),e.kind==1.0);
  let coreV=select(select(e.createFront-0.075*coreQ,select(0.55,iv,iv>=0.0),e.kind==1.0),0.49+0.19*coreQ,e.kind==2.0);
  let coreSpot=gauss(((q-coreQ)*widthAt(v))/0.018)*gauss((v-coreV)/0.031);
  let core=coreSpot*e.core*coreOn*select(0.18,1.0,front>0.5);
  let extraR=(0.09*loadPatch+0.085*joinPatch+0.018*drainPatch+0.025*foldPatch)*backGain;
  let extraG=(0.12*loadPatch+0.13*joinPatch+0.16*drainPatch+0.10*foldPatch)*backGain;
  let extraB=(0.025*loadPatch+0.035*joinPatch+0.075*drainPatch+0.035*foldPatch)*backGain;
  let E_R=coverage*(emitR+extraR+1.38*core);
  let E_G=coverage*(emitG+extraG+1.25*core);
  let E_B=coverage*(emitB+extraB+1.12*core);
  return Field(alpha*baseR+E_R,alpha*baseG+E_G,alpha*baseB+E_B,alpha,coverage,core*coverage,0.2126*E_R+0.7152*E_G+0.0722*E_B,nx,ny,nz,stress,formed);
}

// Uniforms are 64 bytes. No background color, texture, character UV or caster ID.
struct Params {
 viewport:vec4f, // framebuffer W,H,Hpx,ageMs
 event:vec4f,    // kind (-1 idle,0..3), authority, impact q (-2 unknown), impact v (-1 unknown)
 pose:vec4f,     // center x,y, yaw radians, pitch radians
 options:vec4f,  // core 0/1, diagnostic 0 normal 1 alpha 2 emission 3 normals, unused, unused
};
@group(0) @binding(0) var<uniform> p:Params;
struct RasterVertex {
 @builtin(position) position:vec4f,
 @location(0) uv:vec2f,
 @location(1) @interpolate(flat) front:f32,
};
fn rotatePoint(g:Point)->vec3f {
 let cy=cos(p.pose.z);let sy=sin(p.pose.z);let cp=cos(p.pose.w);let sp=sin(p.pose.w);
 let x=cy*g.x+sy*g.z;let z=-sy*g.x+cy*g.z;
 return vec3f(x,cp*g.y-sp*z,sp*g.y+cp*z);
}
@vertex fn vs(@builtin(vertex_index) id:u32,@builtin(instance_index) instance:u32)->RasterVertex {
 let nu=48u;let nv=64u;
 // Indexed shared parameter grid: ~6,370 unique vertices for two faces, not 36,864 evaluations.
 let grid=vec2u(id%(nu+1u),id/(nu+1u));
 let q=2.0*f32(grid.x)/f32(nu)-1.0;let v=f32(grid.y)/f32(nv);
 let front=f32(instance); // draw instance 0 back, then 1 front; never draw twice as layers.
 let g=geometry(q,v,p.event.x,p.viewport.w,p.event.y,p.event.z,p.event.w,front);
 let pos=rotatePoint(g);let pixel=p.pose.xy+vec2f(pos.x,-pos.y)*p.viewport.z;
 var out:RasterVertex;out.position=vec4f(2.0*pixel.x/p.viewport.x-1.0,1.0-2.0*pixel.y/p.viewport.y,0.5-pos.z*0.20,1.0);
 out.uv=vec2f(q,v);out.front=front;return out;
}
@fragment fn fs(v:RasterVertex)->@location(0) vec4f {
 let f=material(v.uv.x,v.uv.y,p.event.x,p.viewport.w,p.event.y,p.event.z,p.event.w,v.front,p.viewport.z,p.options.x,p.pose.z,p.pose.w);
 if(p.options.y==1.0){return vec4f(vec3f(f.a),f.a);}
 if(p.options.y==2.0){return vec4f(vec3f(f.emissionY),f.a);}
 if(p.options.y==3.0){return vec4f((vec3f(f.normalX,f.normalY,f.normalZ)*0.5+0.5)*f.a,f.a);}
 // GENERALIZED premultiplied emission: RGB = alpha*surface + coverage*emission.
 // RGB>alpha is legal. Outside coverage both RGB and alpha are zero. No add pass.
 return vec4f(f.r,f.g,f.b,f.a);
}
// GPU/CPU scalar parity. Independent of rasterization; cannot certify visual quality.
struct Probe { config:vec4f, point:vec4f, contact:vec4f }; // kind age auth H; q v front core; iq iv yaw pitch
struct ProbeOut { geometry:vec4f, rgba:vec4f, diagnosis:vec4f };
@group(1) @binding(0) var<storage,read> probes:array<Probe>;
@group(1) @binding(1) var<storage,read_write> probeResults:array<ProbeOut>;
@compute @workgroup_size(64) fn parity(@builtin(global_invocation_id) id:vec3u){
 if(id.x>=arrayLength(&probes)){return;}
 let a=probes[id.x];let g=geometry(a.point.x,a.point.y,a.config.x,a.config.y,a.config.z,a.contact.x,a.contact.y,a.point.z);
 let f=material(a.point.x,a.point.y,a.config.x,a.config.y,a.config.z,a.contact.x,a.contact.y,a.point.z,a.config.w,a.point.w,a.contact.z,a.contact.w);
 probeResults[id.x]=ProbeOut(vec4f(g.x,g.y,g.z,f.coverage),vec4f(f.r,f.g,f.b,f.a),vec4f(f.core,f.emissionY,f.normalX,f.normalY));
}
