/** Local static conformance/consistency checks. Does not execute shaders or certify images. */
import{readFile,writeFile,readdir,stat}from'node:fs/promises';import{createHash}from'node:crypto';import{spawnSync}from'node:child_process';import{fileURLToPath}from'node:url';
import{GPU_CONTRACT as G}from'../src/gpu-contract.js';import{CONTRACT as C}from'../src/contract.js';import{inspectWGSL}from'./wgsl-lexicon.mjs';
const root=new URL('../',import.meta.url);const read=path=>readFile(new URL(path,root),'utf8');const checks=[];
function verify(name,condition,evidence=''){checks.push({name,status:condition?'pass':'fail',evidence});}
const d=JSON.parse(await read('design/B-Expression-2.design.json'));
const phs=d.PhenomenonSystemTemplate.PhenomenonBlock,reg=d.PhenomenonSystemTemplate.PhenomenonRegistry,obs=d.ObservationIntegrationTemplate.ObservationRegistry;
const phKeys=['identity','DeepStructure','PhysicalModel','ScaleRegime','OctaDomain','PerceptualReadability','GeometryConstraint','StateDynamics','Couplings','CausalityLinks','Evidence','SurroundingChanges','VisualProjection','BeautyStructureApplication','AcceptanceCriteria','FailurePatterns'];
const top=['InferenceExpansionPolicy','FoundationOperationTemplate','PlatonicGoodTemplate','PhenomenonSystemTemplate','PEMTemplate','CoordinateGravityWindTemplate','OctaDomainTemplate','AnimeStudiesTemplate','ObservationIntegrationTemplate','ExtremumDesignColorTemplate','ReflectionClosureTemplate','PhenomenonProfileTemplate','TermsTemplate','GlobalAcceptanceTemplate'];
for(const name of top)verify(`top.${name}`,!!d[name]);
verify('schema',d.FoundationOperationTemplate.OutputContract.schema_version==='B-Expression-2');verify('branch',d.FoundationOperationTemplate.ImplementationBranch.name==='ECodeImplementation');
verify('same registry/blocks ids',JSON.stringify(Object.keys(reg))===JSON.stringify(Object.keys(phs)));
const domainNames=['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience'];
const allRefs=new Set([...Object.keys(reg),...Object.keys(obs),'display_condition','optical_condition']);
for(const[id,ph]of Object.entries(phs)){
 verify(`${id}.identity`,JSON.stringify(reg[id])===JSON.stringify(ph.identity));
 for(const key of phKeys)verify(`${id}.${key}`,ph[key]!==undefined);
 for(const key of['model_kind','system_boundary','state_variables','inputs','balance_conditions','constitutive_response','initial_condition','boundary_conditions','approximation_scope'])verify(`${id}.PhysicalModel.${key}`,ph.PhysicalModel[key]!==undefined);
 for(const key of['mass','momentum','energy','charge']){const item=ph.PhysicalModel.balance_conditions[key];verify(`${id}.balance.${key}`,!!item&&['applicable','not_applicable'].includes(item.status)&&item.balance_or_reason.length>10);}
 for(const key of['characteristic_length','characteristic_time','dominant_balance','dimensionless_reasoning','detail_cutoff'])verify(`${id}.ScaleRegime.${key}`,typeof ph.ScaleRegime[key]==='string'&&ph.ScaleRegime[key].length>5);
 for(const domain of domainNames){const entry=ph.OctaDomain.Domains[domain];verify(`${id}.domain.${domain}.present`,!!entry);verify(`${id}.domain.${domain}.applicability`,['applicable','not_applicable'].includes(entry?.applicability));verify(`${id}.domain.${domain}.role`,['primary','supporting','latent'].includes(entry?.role));verify(`${id}.domain.${domain}.items`,Array.isArray(entry?.items)&&entry.items.length>=1);verify(`${id}.domain.${domain}.evidence`,entry?.evidence_or_constraint?.length>5);if(entry?.applicability==='not_applicable')verify(`${id}.domain.${domain}.nonapp-latent`,entry.role==='latent');}
 for(const key of['driving_input','response_timescale','phase_relation','stability_condition','transition_path_character','convergence_behavior'])verify(`${id}.StateDynamics.${key}`,ph.StateDynamics[key]!==undefined);
 for(const key of['cue_roles','confusable_alternative','disambiguating_evidence','viewing_conditions'])verify(`${id}.PerceptualReadability.${key}`,ph.PerceptualReadability[key]!==undefined);
 const ca=ph.Couplings.CausalAssessment;verify(`${id}.causal status/evidence`,ca.check_status==='hypothesis_only'&&ca.evidence_refs.length===0);
 if(ph.identity.visibility==='visible')verify(`${id}.visible evidence`,ph.Evidence.direct.length>=2);
 if(ph.identity.visibility==='implicit')verify(`${id}.implicit evidence`,ph.Evidence.indirect.length>=1&&ph.CausalityLinks.physical_influence.length>=1);
 const beauty=ph.BeautyStructureApplication;verify(`${id}.beauty`,beauty.target_policy==='standard'?Object.keys(beauty.axes).length>=2&&Object.values(beauty.axes).every(a=>a.length>=2):beauty.adjustment_reason.length>15);
 verify(`${id}.GTB`,Object.keys(ph.GTBConnections??{}).length>=2);
 for(const link of ph.CausalityLinks.physical_influence)verify(`${id}.physical.${link.source}->${link.target}`,!!reg[link.source]&&!!reg[link.target]&&link.mechanism.length>10&&link.consequence.length>10);
 for(const link of ph.CausalityLinks.observation_dependency)verify(`${id}.observation.${link.source}->${link.target}`,!!obs[link.source]&&allRefs.has(link.target));
}
const obsFields=['operation_type','input_references','target_mask','stage','composite_method','intensity','protected_regions','output_consequence','dependencies','sampling_consequence'];
for(const[id,o]of Object.entries(obs)){for(const key of obsFields)verify(`${id}.${key}`,o[key]!==undefined);for(const ref of[...o.input_references,...o.dependencies])verify(`${id}.ref.${ref}`,allRefs.has(ref));}
function hasCycle(){const path=new Set(),done=new Set();function walk(id){if(path.has(id))return true;if(done.has(id))return false;path.add(id);for(const child of obs[id].dependencies.filter(x=>obs[x]))if(walk(child))return true;path.delete(id);done.add(id);return false;}return Object.keys(obs).some(walk);}
verify('OBS dependency DAG',!hasCycle());
const wind=d.CoordinateGravityWindTemplate.WindCapsule;verify('wind calm',wind.medium_state==='air'&&wind.Field.speed==='0m/s');verify('world applicability',d.CoordinateGravityWindTemplate.WorldApplicability.status==='applicable');verify('gravity present',!!d.CoordinateGravityWindTemplate.Gravity);verify('transform chain',d.CoordinateGravityWindTemplate.TransformChain.order.join(',')==='world,camera,screen');
for(const key of['output_resolution','intended_display_scale','spatial_detail_policy','temporal_sampling','filter_and_resample_policy'])verify(`sampling.${key}`,!!d.ObservationIntegrationTemplate.SamplingContract[key]);
for(const name of['KeywordExpansion','GradientAnchorPolicy'])verify(`unselected module ${name} absent`,!d[name]);
for(const[name,entry]of Object.entries(d.ExtensionActivationTable.entries))verify(`activation ${name}`,entry.output_blocks.every(k=>!!d[k])&&entry.reason.length>5);
const layerIds=new Set(d.VFX.layers.map(l=>l.layer_id));verify('layer ids unique',layerIds.size===d.VFX.layers.length);verify('VFX world carrier',d.VFX.layers.some(l=>l.domain==='world'&&l.PH_refs.includes(d.VFX.causal_path.carrier_PH)));
for(const layer of d.VFX.layers){verify(`${layer.layer_id}.separation`,layer.domain==='world'?layer.PH_refs.length>0&&layer.OBS_refs.length===0:layer.OBS_refs.length>0&&layer.PH_refs.length===0);for(const ref of[...layer.PH_refs,...layer.OBS_refs])verify(`${layer.layer_id}.${ref}`,allRefs.has(ref));for(const key of['selection','function_and_visible_result','spatial_structure','material_and_optics','motion_and_phase','integration'])verify(`${layer.layer_id}.${key}`,!!layer[key]);}
for(const l of d.VFX.interlayer_links)verify(`layer-link ${l.source_layer}->${l.target_layer}`,layerIds.has(l.source_layer)&&layerIds.has(l.target_layer)&&l.source_layer!==l.target_layer&&['physical_influence','observation_dependency','visual_relation'].includes(l.relation_type));
for(const[id,c]of Object.entries(d.CharacterPolicy.characters)){verify(`character key ${id}`,c.GeneralCharacter.character_id===id);verify(`pose for ${id}`,!!d.BeautifulPoseCapsule.characters[id]);}
for(const[id,p]of Object.entries(d.BeautifulPoseCapsule.characters)){for(const field of['PhysicalModel','ScaleRegime','StateDynamics']){const ref=p.Common.PH_mechanics_refs[field];const [pid,k]=ref.split('.');verify(`pose ${id}.${field}`,!!phs[pid]?.[k]&&k===field);}}
verify('Video duration equals event default',d.VideoGenerationPolicy.Duration.seconds*1000===C.defaultDurationMs);verify('duration minimum',C.minimumDurationMs===900);verify('reference radius',C.referenceRadius===82);
for(const[track,entries]of Object.entries(d.VideoGenerationPolicy.timeline.tracks))for(const e of entries)verify(`timeline ${track}.${e.id??'camera'}`,e.start>=0&&e.end<=d.VideoGenerationPolicy.Duration.seconds&&e.state_before&&e.state_during&&e.state_after);
const ga=d.GlobalAcceptanceTemplate;verify('RenderObservation not fabricated',ga.ValidationResults.RenderObservation.status==='not_run');verify('intent outcome not fabricated',ga.OutcomeEvaluation.intent_alignment.status==='not_run');verify('art outcome not fabricated',ga.OutcomeEvaluation.artistic_effect.status==='not_run');verify('render NotRun',ga.FinalStatus.render_status==='NotRun');verify('quality not approved',ga.ApprovalState.quality_adoption==='not_approved');verify('integration not approved',ga.ApprovalState.game_integration==='not_approved');
const shaderReports=[];
for(const specification of G.passes){const code=await read(`shaders/${specification.shader}`);const report=inspectWGSL(code,{label:specification.shader,specification});shaderReports.push(report);verify(`WGSL static ${specification.name}`,report.status==='pass',report.errors.join('; '));}
const scene=await read('shaders/scene.wgsl');
for(const[name,color]of Object.entries(C.palette)){const values=[...scene.matchAll(/vec3f\(([.\d]+),\s*([.\d]+),\s*([.\d]+)\)/g)].map(m=>m.slice(1).map(Number));verify(`CCM shader palette ${name}`,values.some(v=>v.every((x,i)=>Math.abs(x-color[i])<1e-10)));}
async function list(dir=''){const paths=[];for(const e of await readdir(new URL(dir||'.',root),{withFileTypes:true})){if(e.name==='node_modules'||e.name==='__pycache__')continue;const path=dir?`${dir}/${e.name}`:e.name;if(e.isDirectory())paths.push(...await list(path));else paths.push(path);}return paths;}
const files=await list();verify('no image texture assets',!files.some(p=>/\.(png|jpe?g|webp|gif|ktx2?|dds|basis)$/i.test(p)));verify('no old archives bundled',!files.some(p=>/\.(zip)$/i.test(p)));
for(const file of files.filter(p=>/\.(m?js)$/.test(p))){const result=spawnSync(process.execPath,['--check',fileURLToPath(new URL(file,root))],{encoding:'utf8'});verify(`JS syntax ${file}`,result.status===0,result.stderr.trim());}
const analysis=JSON.parse(await read('verification/audio-analysis.json'));verify('audio real listening not_run',analysis.actualListening==='not_run');
for(const audio of analysis.results){const file=await readFile(new URL(audio.filename,root));verify(`WAV ${audio.filename}`,file.toString('ascii',0,4)==='RIFF'&&file.readUInt32LE(24)===48000&&file.readUInt16LE(22)===2&&file.length===44+audio.frames*4);verify(`WAV hash ${audio.filename}`,createHash('sha256').update(file).digest('hex')===audio.sha256);verify(`WAV bounded/tail ${audio.filename}`,audio.peak<1&&audio.tail10msRMS<1e-8);}
const failures=checks.filter(c=>c.status==='fail');
const report={revision:'0.4.0',scope:'Local static B-instance, host/WGSL descriptor, file and numeric audio checks. Not official B validation, full WGSL type checking, real pipeline execution, render quality or listening.',status:failures.length?'fail':'pass',checkCount:checks.length,failedCount:failures.length,checks,shaderReports,executionBoundaries:{WGSL_actual_compilation:'not_run',createRenderPipelineAsync:'not_run',actual_GPU_render:'not_run',full_lifetime_quality:'not_run',actual_listening:'not_run',CPU_proxy_image_used:false}};
if(process.argv.includes('--write')){
 ga.ValidationResults.StructuralInspection={status:report.status,checks:{required_blocks:`Local static checker: ${checks.length} assertions, ${failures.length} failures; see verification/static-report.json`,rule_contracts:'Normative rules are user-supplied; no external official B validator was supplied.',PH_OBS_separation:'Registered ids, endpoints and OBS DAG checked.',OctaDomain:'All8 domains per PH with applicability and reason checked.',scientific_fields:'Required model/scale/dynamics/causal/perceptual fields inspected; this does not establish real-world scientific truth.',coordinate_gravity_wind:'Coordinate transform, gravity and calm WindCapsule present.',template_consolidation:'One instance block per selected chapter; no PH-minimum branch.'}};
 await writeFile(new URL('design/B-Expression-2.design.json',root),JSON.stringify(d,null,2)+'\n');
 report.boundFileHashes={};for(const file of['design/B-Expression-2.design.json','src/contract.js','src/sampler.js','src/events.js','src/synthesis.js','src/audio-worklet.js',...G.passes.map(p=>`shaders/${p.shader}`)])report.boundFileHashes[file]=createHash('sha256').update(await readFile(new URL(file,root))).digest('hex');
 await writeFile(new URL('verification/static-report.json',root),JSON.stringify(report,null,2)+'\n');
}
console.log(JSON.stringify({status:report.status,checks:checks.length,failures:failures,scope:report.scope,executionBoundaries:report.executionBoundaries},null,2));process.exitCode=failures.length?1:0;
