import test from 'node:test';import assert from 'node:assert/strict';import {FacilityAudio} from '../src/runtime/audio.mjs';
import {synthesizeReactor} from '../src/effects/reactor/sound.mjs';import {synthesizeRecycling} from '../src/effects/recycling/sound.mjs';
function fake(){const calls={nodes:0,starts:[],connections:0};const context={sampleRate:48000,state:'running',currentTime:4,createGain:()=>({gain:{value:1,setValueAtTime:(value,time)=>{calls.mix=value;}},connect:()=>{},disconnect:()=>{}}),
 createBuffer:(n,l,s)=>({duration:l/s,copyToChannel:()=>{}}),createBufferSource:()=>{calls.nodes++;return {connect:()=>calls.connections++,disconnect:()=>{},stop:()=>{},start:(...a)=>calls.starts.push(a)}}};const bus={context};return {calls,context,bus};}
test('verify creates no nodes, buffers or sound',()=>{const forbidden=new Proxy({}, {get:()=>{throw new Error('audio access in verify')}});const a=new FacilityAudio({context:forbidden,outputBus:forbidden,verify:true});assert.equal(a.playOnce({causeKey:'x',targetKey:'A',ageMs:0}),'silent_verify');assert.equal(a.stats.started,0);});
test('one source, one start even for duplicate',()=>{const f=fake(),a=new FacilityAudio({context:f.context,outputBus:f.bus,getMixState:()=>({muted:false,volume:.5})});a.playOnce({causeKey:'x',targetKey:'A',ageMs:0});a.playOnce({causeKey:'x',targetKey:'A',ageMs:0});assert.equal(f.calls.nodes,1);assert.equal(f.calls.starts.length,1);});
test('delayed cue begins at age offset, never from zero',()=>{const f=fake(),a=new FacilityAudio({context:f.context,outputBus:f.bus,getMixState:()=>({muted:false,volume:1})});a.playOnce({causeKey:'x',targetKey:'B',ageMs:1300});assert.deepEqual(f.calls.starts[0],[4,1.3]);});
test('muted and suspended consume without resume replay',()=>{const f=fake();let muted=true;const a=new FacilityAudio({context:f.context,outputBus:f.bus,getMixState:()=>({muted,volume:1})});a.playOnce({causeKey:'x',targetKey:'A',ageMs:0});muted=false;a.playOnce({causeKey:'x',targetKey:'A',ageMs:0});f.context.state='suspended';a.playOnce({causeKey:'y',targetKey:'B',ageMs:0});f.context.state='running';a.playOnce({causeKey:'y',targetKey:'B',ageMs:0});assert.equal(f.calls.starts.length,0);});
test('audio duration exhausted is silent even inside visual lifetime',()=>{const f=fake(),a=new FacilityAudio({context:f.context,outputBus:f.bus,getMixState:()=>({muted:false,volume:1})});a.playOnce({causeKey:'x',targetKey:'A',ageMs:1900});assert.equal(f.calls.starts.length,0);});
for(const rate of [8000,44100,48000,96000])for(const [key,synth] of [['A',synthesizeReactor],['B',synthesizeRecycling]])test(`PCM finite and bounded ${key}/${rate} (not hearing)`,()=>{const x=synth(rate);let max=0,sum=0;for(const s of x.samples){assert.ok(Number.isFinite(s));max=Math.max(max,Math.abs(s));sum+=s*s;}assert.ok(max<.8&&max>.05);assert.ok(Math.sqrt(sum/x.samples.length)>.01);assert.ok(Math.abs(x.samples[0])<.01);assert.ok(Math.abs(x.samples.at(-1))<.01);assert.ok(x.durationMs<2200);});
test('A and B independently constructed signals',()=>{const a=synthesizeReactor(48000).samples,b=synthesizeRecycling(48000).samples;assert.notEqual(a.length,b.length);assert.ok(a.some((x,i)=>i<b.length&&Math.abs(x-b[i])>.1));});

test('simultaneous distinct causes retain both one-shot sources with bounded coherent mix',()=>{const f=fake(),a=new FacilityAudio({context:f.context,outputBus:f.bus,getMixState:()=>({muted:false,volume:1})});a.playOnce({causeKey:'one',targetKey:'A',ageMs:0});a.playOnce({causeKey:'two',targetKey:'B',ageMs:0});assert.equal(f.calls.starts.length,2);assert.equal(f.calls.mix,.5);});
