import test from 'node:test';import assert from 'node:assert/strict';import {rig} from './helpers.mjs';
import {FacilityController,installFacilityPresentation} from '../src/runtime/controller.mjs';
import {causeKey,TARGETS} from '../src/runtime/contracts.mjs';
for(const key of ['A','B'])test(`${key}: exact target one dedicated route`,async()=>{
 const r=rig();const {raw}=r.make(key);assert.equal((await r.controller.receive(raw)).status,'dedicated_once');
 assert.equal(r.calls.audio.length,1);assert.equal(r.calls.generic.length,0);assert.equal(r.controller.sampleFrame()[0].targetKey,key);
});
for(const [field,value] of [['status','failed'],['objectId',''],['type','wrong'],['effectKind','wrong'],['playerId','absent'],['objectCausalId',''],['capturedTime',NaN],['capturedTime','123'],['worldOrigin',{x:3699.001,y:388}],['worldOrigin',{x:3699,y:Infinity}]])
 test(`reject invalid ${field}:${String(value)}`,async()=>{const r=rig();const {raw}=r.make('A',{[field]:value});assert.notEqual((await r.controller.receive(raw)).status,'dedicated_once');assert.equal(r.calls.audio.length,0);assert.equal(r.controller.sampleFrame().length,0);});
test('untrusted success flag rejected',async()=>{const r=rig();await r.controller.receive(r.make().receipt);assert.equal(r.calls.audio.length,0);});
test('100 concurrent duplicates reserve once',async()=>{const r=rig(),x=r.make();const out=await Promise.all(Array.from({length:100},()=>r.controller.receive(x.raw)));assert.equal(out.filter(x=>x.status==='dedicated_once').length,1);assert.equal(r.calls.audio.length,1);assert.equal(r.controller.stats.duplicates,99);});
test('same cause cannot mutate player, timestamp or object to replay',async()=>{const r=rig(),x=r.make();await r.controller.receive(x.raw);for(const patch of [{playerId:'p2'},{capturedTime:x.receipt.capturedTime-1},{...TARGETS['v302-fabrication-recyclingUnit-2'],worldOrigin:{x:4315,y:2102}}]){const y=r.make('A',{...patch,objectCausalId:x.receipt.objectCausalId});assert.equal((await r.controller.receive(y.raw)).status,'causal_conflict');}assert.equal(r.calls.audio.length,1);});
test('controller replacement shares persistent claim (model)',async()=>{const r=rig(),x=r.make();await r.controller.receive(x.raw);const other=new FacilityController(r.args);assert.equal((await other.receive(x.raw)).status,'duplicate');assert.equal(r.calls.audio.length,1);});
test('render, camera and redraw never re-fire',async()=>{const r=rig(),x=r.make();await r.controller.receive(x.raw);for(let n=0;n<500;n++){r.state.now+=2;r.controller.sampleFrame();}assert.equal(r.calls.audio.length,1);assert.equal(r.controller.stats.visualStarted,1);});
test('delayed receipt joins capturedTime phase',async()=>{const r=rig(),x=r.make();r.state.now+=1300;await r.controller.receive(x.raw);assert.equal(r.controller.sampleFrame()[0].ageMs,1300);assert.equal(r.calls.audio[0].ageMs,1300);r.state.now+=900;assert.equal(r.controller.sampleFrame().length,0);});
test('expired event is consumed, no visual and no generic',async()=>{const r=rig(),x=r.make();r.state.now+=2300;assert.equal((await r.controller.receive(x.raw)).status,'expired_consumed');assert.equal(r.calls.audio.length,0);assert.equal(r.calls.generic.length,0);assert.equal((await r.controller.receive(x.raw)).status,'duplicate');});
test('future +51ms rejected; +30ms waits without extra trigger',async()=>{const r=rig();const x=r.make('A',{capturedTime:r.clock.serverNowMs()+51});assert.equal((await r.controller.receive(x.raw)).status,'future_receipt');const y=r.make('A',{capturedTime:r.clock.serverNowMs()+30});await r.controller.receive(y.raw);assert.equal(r.controller.sampleFrame().length,0);r.state.now+=40;assert.equal(r.controller.sampleFrame()[0].ageMs,10);assert.equal(r.calls.audio.length,1);});
test('unbounded clock fails closed',async()=>{const r=rig(),x=r.make();r.state.uncertainty=Infinity;assert.equal((await r.controller.receive(x.raw)).status,'clock_not_bounded');assert.equal(r.calls.audio.length,0);});
test('frame clock cannot rewind live phase',async()=>{const r=rig(),x=r.make();await r.controller.receive(x.raw);r.state.now+=600;const a=r.controller.sampleFrame()[0].ageMs;r.state.now-=300;assert.equal(r.controller.sampleFrame()[0].ageMs,a);});
test('missing anchor is not replaced with source; does not defer lifetime',async()=>{const r=rig(),x=r.make();r.state.missing=true;await r.controller.receive(x.raw);assert.equal(r.controller.sampleFrame()[0].receiver,null);r.state.now+=2300;r.state.missing=false;assert.equal(r.controller.sampleFrame().length,0);assert.equal(r.calls.audio.length,1);});
test('ledger quota failure cannot leak sound or visuals',async()=>{const r=rig({ledger:{claim:async()=>{throw new Error('quota')}}}),x=r.make();assert.equal((await r.controller.receive(x.raw)).status,'ledger_failed');assert.equal(r.calls.audio.length,0);});
test('unknown valid facility uses exactly one generic route',async()=>{const r=rig(),x=r.make('A',{objectId:'other-facility',type:'other',effectKind:'other'});await r.controller.receive(x.raw);await r.controller.receive(x.raw);assert.equal(r.calls.generic.length,1);assert.equal(r.calls.audio.length,0);});
test('atomic presentation replacement does not modify benefit handler',async()=>{const r=rig();let legacy=0,installed;const benefitHandler=()=>{};const host={benefitHandler,replaceFacilityPresentation:cb=>{installed=cb;return ()=>{installed=null;legacy++;}}};const detach=installFacilityPresentation(host,r.controller);assert.equal(typeof installed,'function');assert.equal(host.benefitHandler,benefitHandler);detach();detach();assert.equal(legacy,1);});
test('cause keys are not delimiter-collision prone',()=>assert.notEqual(causeKey('a|b','c'),causeKey('a','b|c')));
test('benefit/cooldown metadata independent of visual lifetime',()=>{const [a,b]=Object.values(TARGETS);assert.equal(a.declaredBenefit.durationMs,20000);assert.equal(a.cooldownMs,38000);assert.equal(b.cooldownMs,34000);assert.equal(b.declaredBenefit.delta,3);});
