import test from 'node:test';import assert from 'node:assert/strict';
import {EventStore} from '../src/events.js';import {sampleStore} from '../src/sampler.js';import {buildGeometry,STRIDE} from '../src/geometry.js';import {SCENARIOS,dispatch,actorsAt} from '../preview/scenarios.js';import {actorOccluders} from '../preview/fixtures.js';
function event(kind,zero=false){const store=new EventStore();store.add(kind,{id:'e',cause:'c',owner:'o',phase:1,pair:kind==='resonance'||kind==='cancellation'?{id:'p'}:null,atMs:0,origin:{x:0,y:0},a:{x:zero?0:-150,y:0},b:{x:zero?0:150,y:0},targets:[{id:'target',position:{x:zero?0:240,y:0}}],authorityDeadlineMs:kind==='suppression'?7000:kind==='charge'?2400:null});return store;}
function inspect(geo){for(const a of[geo.opaque,geo.transparent]){assert.equal(a.length%(STRIDE*3),0);for(const n of a)assert.ok(Number.isFinite(n));for(let i=0;i<a.length;i+=STRIDE){assert.ok(Math.abs(a[i])<2000&&Math.abs(a[i+1])<2000&&Math.abs(a[i+2])<2000);assert.ok(a[i+9]>=0&&a[i+9]<=1);}}assert.equal(geo.triangleCount,(geo.opaque.length+geo.transparent.length)/(STRIDE*3));}
for(const kind of['charge','normal','resonance','cancellation','suppression'])for(const zero of[false,true])test(`${kind}: finite full-lifetime geometry, d=${zero?'0':'nonzero'}, high+low`,()=>{const store=event(kind,zero),end=kind==='charge'?2800:kind==='suppression'?7400:kind==='normal'?650:1800;let seen=0;for(let i=0;i<=80;i++)for(const quality of['high','low']){const geo=buildGeometry(sampleStore(store,end*i/80),{quality});inspect(geo);if(geo.triangleCount)seen++;}assert.ok(seen>20);assert.equal(buildGeometry(sampleStore(store,end)).triangleCount,0);});
test('normal moving packet changes occupied region and vertex count, not only uniform scale',()=>{const s=event('normal'),a=buildGeometry(sampleStore(s,65)),b=buildGeometry(sampleStore(s,210));assert.notEqual(a.transparent.length,b.transparent.length);const center=g=>{let x=0,n=0;for(let i=0;i<g.transparent.length;i+=STRIDE){x+=g.transparent[i];n++;}return x/n;};assert.ok(center(b)>center(a)+60);});
test('cancellation consumes rows rather than uniformly scaling fixed topology',()=>{const s=event('cancellation'),a=buildGeometry(sampleStore(s,550)),b=buildGeometry(sampleStore(s,1160));assert.ok(a.triangleCount>b.triangleCount);assert.notDeepEqual(a.branches,b.branches);});
test('charge geometry is steady during readiness wait',()=>{const s=event('charge');const a=buildGeometry(sampleStore(s,1300)),b=buildGeometry(sampleStore(s,2100));assert.deepEqual(a.transparent,b.transparent);});
test('extension holds identical lock geometry at equal attachment, no latch restart',()=>{const s=event('suppression'),before=buildGeometry(sampleStore(s,3900));s.extendLock({commandId:'ext',eventId:'e',atMs:4000,authorityDeadlineMs:9300,revision:1});const after=buildGeometry(sampleStore(s,8000));assert.deepEqual(before.transparent,after.transparent);});
test('H64 proxy is exactly 64 game px tall, with both depth sides available',()=>{for(const mode of['front','back','mixed']){const shapes=actorOccluders([{id:'t',x:0,y:0}],mode);const ys=shapes.flatMap(s=>s.polygon?s.polygon.map(p=>p.y):[s.y,s.y+s.h]);assert.equal(Math.max(...ys)-Math.min(...ys),64);inspect(buildGeometry([],{occlusion:shapes}));}});
for(const key of Object.keys(SCENARIOS))test(`scenario ${key}: ordered commands, no accidental failure, all visuals eventually clear`,()=>{const s=SCENARIOS[key],store=new EventStore(),fake={emit:(k,x)=>store.add(k,x),resolve:x=>store.resolve(x),extendLock:x=>store.extendLock(x)};let cursor=0;for(let t=0;t<=s.duration;t+=25){while(cursor<s.commands.length&&s.commands[cursor].at<=t){const r=dispatch(fake,s.commands[cursor++]);assert.ok(r.accepted||r.reason==='duplicate',JSON.stringify({key,r}));}if(t%250===0)inspect(buildGeometry(sampleStore(store,t),{occlusion:actorOccluders(actorsAt(s,t))}));}assert.equal(sampleStore(store,s.duration).length,0,`${key} not cleared`);});
test('no draw call requires a nonzero pair/source distance',()=>{for(const kind of['normal','resonance','cancellation']){const s=event(kind,true);assert.ok(buildGeometry(sampleStore(s,100)).triangleCount>0);}});
