import test from 'node:test';import assert from 'node:assert/strict';import {ManaGainLedger} from '../src/events.js';import {bodyFixture} from '../preview/fixture.js';
function setup(extra={}){const clock={timeMs:1000,rate:1},body=bodyFixture(),calls=[];const audio=Object.fromEntries(['start','sync','stop','clear'].map(k=>[k,v=>{calls.push({method:k,value:v});return true;}]));const ledger=new ManaGainLedger({sessionId:'s',getActorClock:()=>clock,getBeneficiary:()=>body,audio,...extra});const e={sessionId:'s',eventId:'gain',beneficiaryPlayerId:'b',actorPlayerId:'a',committed:true,manaDelta:5};return {ledger,e,clock,body,calls};}
test('authority input does not mutate resource, event or body',()=>{const {ledger,e,body}=setup();const b=structuredClone(body),v=structuredClone(e);assert.equal(ledger.commit(e).status,'accepted');assert.deepEqual(e,v);assert.deepEqual(body,b);assert.equal(ledger.snapshot()[0].durationMs,1500);assert.equal(ledger.snapshot()[0].radiusPx,82);});
for(const x of [0,-5,NaN,Infinity,'3',null])test(`invalid gain ${String(x)} rejected before consumption`,()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,manaDelta:x}).status,'rejected');assert.equal(ledger.causes.size,0);});
for(const v of [false,undefined,1,'true'])test(`commit authority ${String(v)} is not true`,()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,committed:v}).status,'rejected');});
test('DESIRE refinement explicitly excluded but other routes share the same contract',()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,route:'desire-refinement'}).reason,'desire-private-route');for(const route of ['item','skill','reward'])assert.equal(ledger.commit({...e,route,eventId:route}).status,'accepted');});
for(const d of [1,899,900,1500,1800])test(`duration ${d} maps to >=900 actor-ms`,()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,durationMs:d}).durationMs,Math.max(900,d));});
for(const d of [0,-1,null,NaN,Infinity])test(`duration ${String(d)} rejected`,()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,durationMs:d}).reason,'invalid-duration');});
test('one cause / recipient is deduplicated for the entire session including after expiry',()=>{const {ledger,e,clock,calls}=setup();ledger.commit(e);assert.equal(ledger.commit(e).status,'duplicate');clock.timeMs=2500;assert.equal(ledger.update().length,0);assert.equal(ledger.commit(e).status,'duplicate');assert.equal(calls.filter(v=>v.method==='start').length,1);});
test('actor ownership distinct from beneficiary and follows authoritative phase without multiplying twice',()=>{const read=[],{ledger,e,clock}=setup({getActorClock:id=>{read.push(id);return {timeMs:clock.timeMs,rate:clock.rate};}});ledger.commit(e);clock.rate=2;clock.timeMs=1750;assert.equal(ledger.update()[0].ageMs,750);assert.deepEqual([...new Set(read)],['a']);});
test('actor rate change retains age; rate zero freezes it',()=>{const {ledger,e,clock}=setup();ledger.commit(e);clock.timeMs=1320;clock.rate=2;assert.equal(ledger.update()[0].ageMs,320);clock.rate=0;assert.equal(ledger.update()[0].ageMs,320);});
test('future and explicit null start rejected',()=>{const {ledger,e}=setup();assert.equal(ledger.commit({...e,startedAtActorMs:1001}).reason,'future-event');assert.equal(ledger.commit({...e,startedAtActorMs:null}).reason,'invalid-start');});
test('late committed cause is consumed without restarting after expiry',()=>{const {ledger,e,clock,calls}=setup();clock.timeMs=5000;assert.equal(ledger.commit({...e,startedAtActorMs:1000}).status,'suppressed');assert.equal(ledger.commit({...e,startedAtActorMs:1000}).status,'duplicate');assert.equal(calls.length,0);});
for(const [k,v,reason] of [['alive',false,'dead'],['present',false,'departed'],['inVent',true,'vent'],['invisible',true,'invisible']]){
 test(`${reason} removes active E and stops its last shared voice`,()=>{const {ledger,e,body,calls}=setup();ledger.commit(e);body[k]=v;assert.equal(ledger.update().length,0);assert.equal(calls.filter(c=>c.method==='stop').length,1);body[k]=!v;assert.equal(ledger.commit(e).status,'duplicate');});
 test(`${reason} at event consumes without sound and cannot reappear`,()=>{const {ledger,e,body,calls}=setup();body[k]=v;assert.equal(ledger.commit(e).reason,reason);body[k]=!v;assert.equal(ledger.commit(e).status,'duplicate');assert.equal(calls.length,0);});
}
test('missing or malformed receiving polygon suppresses rather than drawing a fallback oval',()=>{for(const polygon of [undefined,[],[[0,0],[1,0],[0,0]],[[0,0],[2,0],[1,0.2],[2,2],[0,2]]]){const {ledger,e,body}=setup();body.torsoPolygon=polygon;assert.equal(ledger.commit(e).reason,'invalid-receiving-polygon');}});
test('multiple beneficiaries of one cause share exactly one sound and one sync',()=>{const {ledger,e,calls}=setup();ledger.commit(e);ledger.commit({...e,beneficiaryPlayerId:'b2'});ledger.update();assert.equal(calls.filter(c=>c.method==='start').length,1);assert.equal(calls.filter(c=>c.method==='sync').length,1);ledger.cancelBeneficiary('b');assert.equal(calls.filter(c=>c.method==='stop').length,0);ledger.cancelBeneficiary('b2');assert.equal(calls.filter(c=>c.method==='stop').length,1);});
test('nearby three independent causes are three E and three start dispatches',()=>{const {ledger,e,clock,calls}=setup();for(let i=0;i<3;i++){clock.timeMs=1000+i*160;ledger.commit({...e,eventId:`gain-${i}`});}assert.equal(ledger.snapshot().length,3);assert.equal(calls.filter(c=>c.method==='start').length,3);});
test('locked audio not retried on advance or second beneficiary',()=>{let unlocked=false,attempts=0;const {ledger,e}=setup({audio:{start:()=>{attempts++;return unlocked;}}});ledger.commit(e);unlocked=true;ledger.update();ledger.commit({...e,beneficiaryPlayerId:'b2'});assert.equal(attempts,1);});
for(const patch of [{actorPlayerId:'other'},{durationMs:900},{startedAtActorMs:999}])test(`same cause cannot change ${Object.keys(patch)[0]}`,()=>{const {ledger,e}=setup();ledger.commit(e);assert.equal(ledger.commit({...e,beneficiaryPlayerId:'b2',...patch}).reason,'cause-conflict');});
test('session switch disposes old E and old-session events rejected',()=>{const {ledger,e}=setup();ledger.commit(e);ledger.resetSession('new');assert.equal(ledger.snapshot().length,0);assert.equal(ledger.commit(e).reason,'wrong-session');assert.equal(ledger.commit({...e,sessionId:'new'}).status,'accepted');});
test('clock rewind fails closed and removes dependents',()=>{const {ledger,e,clock}=setup();ledger.commit(e);clock.timeMs=999;assert.equal(ledger.update().length,0);});
test('invalid rate or missing clock removes active E',()=>{for(const rate of [-1,9,NaN]){const {ledger,e,clock}=setup();ledger.commit(e);clock.rate=rate;assert.equal(ledger.update().length,0);}});
test('dedupe capacity fails closed without evicting history',()=>{const {ledger,e}=setup({maxCauses:1});ledger.commit(e);assert.equal(ledger.commit({...e,eventId:'new'}).reason,'dedupe-capacity');assert.equal(ledger.commit(e).status,'duplicate');});
test('instance capacity suppression consumes cause / recipient',()=>{const {ledger,e}=setup({maxInstances:1});ledger.commit(e);const newE={...e,eventId:'other'};assert.equal(ledger.commit(newE).reason,'instance-capacity');ledger.cancelBeneficiary('b');assert.equal(ledger.commit(newE).status,'duplicate');});
test('beneficiary follows movement while cause owns clock',()=>{const {ledger,e,body}=setup();ledger.commit(e);body.x=47;body.angleRad=0.25;const s=ledger.update()[0];assert.equal(s.body.x,47);assert.equal(s.actorPlayerId,'a');s.body.x=200;assert.equal(ledger.snapshot()[0].body.x,47);});
test('tuple identities do not collide at separator characters',()=>{const {ledger,e}=setup();ledger.commit({...e,eventId:'x|y',beneficiaryPlayerId:'z'});ledger.commit({...e,eventId:'x',beneficiaryPlayerId:'y|z'});assert.equal(ledger.snapshot().length,2);});
test('snapshot and audio exceptions contained',()=>{const {ledger,e}=setup({audio:{start:()=>{throw Error('audio');}}});assert.equal(ledger.commit(e).status,'accepted');const b=setup({getBeneficiary:()=>{throw Error('body');}});assert.equal(b.ledger.commit(b.e).status,'suppressed');});
test('disposal idempotent and cannot accept new effects',()=>{const {ledger,e}=setup();ledger.commit(e);ledger.dispose();ledger.dispose();assert.equal(ledger.snapshot().length,0);assert.equal(ledger.commit(e).reason,'disposed');});
