// All device methods below are MOCKS. These tests are not WGSL compilation or GPU execution.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {ManaGainRenderer,loadWGSL} from '../src/gpu.js';import {bodyFixture} from '../preview/fixture.js';
globalThis.GPUShaderStage={VERTEX:1,FRAGMENT:2};globalThis.GPUBufferUsage={UNIFORM:1,COPY_DST:2,VERTEX:4};globalThis.GPUTextureUsage={RENDER_ATTACHMENT:1,TEXTURE_BINDING:2,COPY_SRC:4};
const originalFetch=globalThis.fetch;globalThis.fetch=async url=>({ok:true,text:()=>fs.readFile(url,'utf8')});test.after(()=>globalThis.fetch=originalFetch);
function device(){const log={pipelines:[],samplers:[],textures:[],buffers:[],groups:[],passes:[],writes:[]};const d={log,limits:{maxTextureDimension2D:8192},lost:new Promise(()=>{}),addEventListener(){},removeEventListener(){},pushErrorScope(){},async popErrorScope(){return null;},createShaderModule:x=>({x,async getCompilationInfo(){return {messages:[]};}}),createBindGroupLayout:x=>({x}),createPipelineLayout:x=>({x}),async createRenderPipelineAsync(x){log.pipelines.push(x);return {x};},createSampler:x=>{log.samplers.push(x);return {x};},createBuffer:x=>{const b={x,dead:false,destroy(){this.dead=true;}};log.buffers.push(b);return b;},createTexture:x=>{const t={x,dead:false,createView:()=>({t}),destroy(){this.dead=true;}};log.textures.push(t);return t;},createBindGroup:x=>{log.groups.push(x);return {x};},createCommandEncoder(){return {beginRenderPass(x){const p={x,draws:[],setPipeline(){},setBindGroup(){},setVertexBuffer(){},draw(...a){this.draws.push(a);},end(){}};log.passes.push(p);return p;},finish:()=>({})};},queue:{writeBuffer:(b,o,data)=>log.writes.push({b,o,data:[...data]}),submit(){}}};return d;}
const sample={beneficiaryPlayerId:'b',body:bodyFixture(),ageMs:450,durationMs:1500,radiusPx:82};const view={width:380,height:286,scale:1,dpr:1};
async function fixture(){const d=device(),r=await ManaGainRenderer.create({device:d});return {d,r};}
test('mock MRT distinguishes premultiplied material and additive radiance',async()=>{const {d,r}=await fixture(),t=d.log.pipelines[0].fragment.targets;assert.equal(t.length,2);assert.equal(t[0].format,'rgba16float');assert.equal(t[0].blend.color.dstFactor,'one-minus-src-alpha');assert.equal(t[1].blend.color.dstFactor,'one');r.dispose();});
test('mock explicit sampler linear/clamp/LOD0, no image texture',async()=>{const {d,r}=await fixture(),s=d.log.samplers[0];assert.equal(s.minFilter,'linear');assert.equal(s.addressModeU,'clamp-to-edge');assert.equal(s.maxAnisotropy,1);assert.equal(s.lodMaxClamp,0);r.dispose();});
test('mock 64-byte vertex stride and locations match payload',async()=>{const {d,r}=await fixture(),b=d.log.pipelines[0].vertex.buffers[0];assert.equal(b.arrayStride,64);assert.deepEqual(b.attributes.map(x=>x.offset),[0,8,16,32,48]);r.prepare([sample],view);assert.ok(d.log.writes.filter(w=>w.b.x.usage&4).every(w=>w.data.length%16===0));r.dispose();});
test('mock back/front and each post direction have independent immutable buffer state',async()=>{const {d,r}=await fixture();r.prepare([sample],view);assert.notEqual(r.layers.back.vertexBuffer,r.layers.front.vertexBuffer);assert.notEqual(r.horizontal,r.vertical);assert.equal(d.log.passes.length,6);r.dispose();});
test('mock native CSS H64 independent of DPR storage',async()=>{const {d,r}=await fixture();r.prepare([sample],{...view,dpr:2});assert.deepEqual(r.size,[760,572]);assert.deepEqual(d.log.writes[0].data.slice(0,4),[760,572,1,2]);r.dispose();});
test('mock rejects mixed owners instead of flattening occlusion',async()=>{const {r}=await fixture();assert.throws(()=>r.prepare([sample,{...sample,beneficiaryPlayerId:'other'}],view),/one renderer slot/);r.dispose();});
test('mock empty frame clears; cancellation makes stale frame undrawable',async()=>{const {r}=await fixture();r.prepare([sample],view);let n=0;const pass={setPipeline(){},setBindGroup(){},draw(){n++;}};r.draw(pass,'front');assert.equal(n,2);r.invalidate();r.draw(pass,'front');assert.equal(n,2);r.prepare([],view);assert.equal(r.layers.front.count,0);r.dispose();});
test('mock resize/dispose destroy textures and buffers; dispose is idempotent',async()=>{const {d,r}=await fixture();r.prepare([sample],view);const old=[...d.log.textures];r.prepare([sample],{...view,width:400});assert.ok(old.every(t=>t.dead));r.dispose();r.dispose();assert.ok(d.log.textures.every(t=>t.dead));assert.ok(d.log.buffers.every(b=>b.dead));});
test('mock runtime preflight rejects ternary source BEFORE createShaderModule',async()=>{let used=false;const d=device();d.createShaderModule=()=>{used=true;};const saved=globalThis.fetch;try{globalThis.fetch=async()=>({ok:true,text:async()=> '@fragment fn fs() -> f32 { return true ? 1.0 : 0.0; }'});await assert.rejects(loadWGSL(d,'unused','bad'),/question-mark/);assert.equal(used,false);}finally{globalThis.fetch=saved;}});
test('mock surfaces compilation diagnostics instead of silently adapting source',async()=>{const d=device();d.createShaderModule=()=>({getCompilationInfo:async()=>({messages:[{type:'error',message:'TEST-STUB ERROR',lineNum:1,linePos:4}]})});await assert.rejects(loadWGSL(d,new URL('../shaders/mana.wgsl',import.meta.url),'bad'),/TEST-STUB ERROR/);});
