// GENERATED from barrier-pro-model.mjs. barrier-pro-r0.5
// Source SHA256 0d227b357a690948b59c9d2d41487a5315f72ebd0e9f7c30b0fda5e5ae545694. Run node tools/build-shader.mjs; DO NOT edit this file.
struct Envelope { kind:f32,r:f32,eventOn:f32,visible:f32,load:f32,depthScale:f32,seam:f32,residue:f32,core:f32, };
struct Point { x:f32,y:f32,z:f32, };
struct Field { r:f32,g:f32,b:f32,a:f32,coverage:f32,core:f32,emissionY:f32,normalX:f32,normalY:f32,normalZ:f32,stress:f32,pane:f32, };
fn sat(x:f32)->f32 {
  return clamp(x,0.0,1.0);
}
fn sq(x:f32)->f32 {
  return x*x;
}
fn ramp(a:f32,b:f32,x:f32)->f32 {
  return sat((x-a)/(b-a));
}
fn softBoundary(a:f32,b:f32,x:f32)->f32 {
  let s=ramp(a,b,x);
  return s*s*(3.0-2.0*s);
}
fn gauss(x:f32)->f32 {
  return exp(-x*x);
}
fn angular(theta:f32,center:f32,width:f32)->f32 {
  return gauss(2.0*sin((theta-center)*0.5)/width);
}
fn sgn(x:f32)->f32 {
  return select(-1.0,1.0,x>=0.0);
}
fn duration(kind:f32)->f32 {
  return select(650.0,480.0,kind>=2.0);
}
fn envelope(requested:f32,age:f32,authority:f32)->Envelope {
  let on=select(0.0,1.0,requested>=0.0 && requested<=3.0 && age>=0.0 && age<duration(requested));
  let kind=select(-1.0,requested,on>0.5);
  let r=sat(age/duration(requested));
  let visible=select(0.0,1.0,on>0.5 || authority>0.5);
  let load=0.24+0.76*exp(-3.1*r);
  let depthScale=select(select(1.0,0.58+0.42*r,kind==0.0),1.0-0.46*r,kind==3.0);
  let seam=select(select(0.0,0.88-0.80*r,kind==0.0),0.10+0.24*r,kind==3.0);
  let residue=select(select(1.0,1.0-0.86*r,kind==3.0),1.0-0.78*r,kind==2.0);
  let core=select(select(select(select(0.0,0.20+0.68*sin(3.141592653589793*r),kind==0.0),0.28+0.92*exp(-3.0*r),kind==1.0),0.18+0.48*exp(-3.6*r),kind==2.0),0.18+0.28*sin(3.141592653589793*r),kind==3.0);
  return Envelope(kind,r,on,visible,load,depthScale,seam,residue,core);
}
fn geometry(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32)->Point {
  let e=envelope(requested,age,authority);
  let theta=(sector+u)*0.7853981633974483;
  let lat=(v-0.5)*3.141592653589793;
  let s=sin(lat);
  let c=cos(lat);
  let cap=sin(3.141592653589793*v);
  let cap2=cap*cap;
  let thetaWarp=theta+0.12*s-0.06*sin(2.0*theta)*s;
  let shell=1.0-0.05*gauss((v-0.5)/0.20);
  let x0=1.22*(0.86+0.14*cap2)*shell*cos(thetaWarp)+0.12*sin(2.0*theta)*(0.45+0.55*cap2);
  let y0=1.92*(v-0.5)+0.045*sin(theta)-0.050*sin(2.0*theta)*s;
  let z0=0.88*(0.78+0.22*cap2)*(0.92+0.08*cos(2.0*theta))*sin(thetaWarp)+0.10*s-0.05*cos(theta)*s;
  let front=softBoundary(-0.18,0.56,sin(theta));
  let loadPatch=angular(theta,2.12,0.55)*gauss((v-0.56)/0.22);
  let dent=select(0.0,0.36*e.load*loadPatch,e.kind==1.0);
  let pinch=select(0.0,0.18*e.load*loadPatch,e.kind==1.0);
  let x1=x0+pinch;
  let y1=y0-0.05*dent;
  let z1=z0*e.depthScale-0.32*dent;
  let failure=select(0.0,1.0,e.kind==2.0);
  let crackLine=v-(0.42+0.14*sin(theta-0.55)+0.05*sin(3.0*theta));
  let crackBand=gauss(crackLine/0.14);
  let fractureAmt=failure*(0.04+0.26*e.r)*crackBand;
  let side=select(-1.0,1.0,cos(theta)>0.0);
  let curl=failure*(0.10+0.22*e.r)*crackBand*front;
  let release=select(0.0,0.10+0.30*e.r,e.kind==3.0);
  let relax=select(0.0,0.08*e.r*(1.0-cap2),e.kind==3.0);
  let x=x1+fractureAmt*0.25*side+release*0.48*side*(0.35+0.65*c);
  let y=y1+fractureAmt*0.08*sgn(crackLine)-relax;
  let z=z1-curl+release*0.18*cos(theta-0.25);
  return Point(x,y,z);
}
fn material(u:f32,v:f32,sector:f32,band:f32,requested:f32,age:f32,authority:f32,hPx:f32,coreOn:f32,yaw:f32,pitch:f32)->Field {
  let e=envelope(requested,age,authority);
  let theta=(sector+u)*0.7853981633974483;
  let g=geometry(u,v,sector,band,requested,age,authority);
  let up=geometry(u+0.001,v,sector,band,requested,age,authority);
  let um=geometry(u-0.001,v,sector,band,requested,age,authority);
  let vp=geometry(u,min(0.99999,v+0.001),sector,band,requested,age,authority);
  let vm=geometry(u,max(0.00001,v-0.001),sector,band,requested,age,authority);
  let tx=up.x-um.x;
  let ty=up.y-um.y;
  let tz=up.z-um.z;
  let ux=vp.x-vm.x;
  let uy=vp.y-vm.y;
  let uz=vp.z-vm.z;
  let cx=-(ty*uz-tz*uy);
  let cy=-(tz*ux-tx*uz);
  let cz=-(tx*uy-ty*ux);
  let nn=max(0.000000001,sqrt(cx*cx+cy*cy+cz*cz));
  let nx=cx/nn;
  let ny=cy/nn;
  let nz=cz/nn;
  let faceLight=clamp(0.82-0.14*nx+0.14*ny+0.10*nz,0.56,1.14);
  let cavity=gauss(g.x/0.55)*gauss(g.y/0.95);
  let air=1.0-0.78*cavity;
  let frontSheet=angular(theta,1.74+0.22*(v-0.5),0.68)*(0.55+0.45*gauss((v-0.56)/0.46))*(1.0-0.88*cavity);
  let rearSheet=angular(theta,4.85+0.18*(v-0.5),0.76)*(0.52+0.48*gauss((v-0.44)/0.48))*(1.0-0.78*cavity);
  let bridgeSheet=0.58*(angular(theta,0.18,0.56)+angular(theta,3.16,0.56))*gauss((v-0.50)/0.72)*(1.0-0.45*cavity);
  let cap2=sq(sin(3.141592653589793*v));
  let poleTaper=0.26+0.74*cap2;
  let seamCenter=0.92+1.00*v;
  let formation=select(0.0,angular(theta,seamCenter,0.22)*gauss((v-(0.52+0.28*e.r))/0.11),e.kind==0.0);
  let loadPatch=angular(theta,2.12,0.58)*gauss((v-0.56)/0.24);
  let loadLight=select(0.0,e.load*loadPatch,e.kind==1.0);
  let releaseLight=select(0.0,angular(theta,0.22+0.16*v,0.34)*gauss((v-0.54)/0.34)*(0.45+0.55*e.r),e.kind==3.0);
  let aa=0.58/hPx;
  let createDist=abs(2.0*sin((theta-seamCenter)*0.5));
  let createMask=softBoundary(e.seam-aa*2.5,e.seam+aa*2.5,createDist);
  let crackLine=v-(0.42+0.14*sin(theta-0.55)+0.05*sin(3.0*theta));
  let fork=theta-(2.08+0.26*sin(11.0*v));
  let gap=0.016+0.050*e.r;
  let fractureMask=softBoundary(gap-aa*0.5,gap+aa*0.5,abs(crackLine))*(1.0-softBoundary(0.48,0.60,v)*(1.0-softBoundary(gap*1.5-aa,gap*1.5+aa,abs(fork))));
  let bustMask=softBoundary(e.seam-aa,e.seam+aa,abs(cos(theta-0.18)));
  let coverage=e.visible*select(select(select(1.0,createMask,e.kind==0.0),fractureMask,e.kind==2.0),bustMask,e.kind==3.0);
  let fractureEdge=select(0.0,gauss((abs(crackLine)-gap-0.012)/0.032)*angular(theta,2.12,0.74)*(0.40+0.60*exp(-2.8*e.r)),e.kind==2.0);
  let opticalResidue=select(select(1.0,1.0-0.72*e.r,e.kind==3.0),1.0-0.58*e.r,e.kind==2.0);
  let tau=air*(0.006+0.56*frontSheet+0.54*rearSheet+0.24*bridgeSheet+0.07*loadLight+0.12*formation)*opticalResidue;
  let alpha=coverage*(1.0-exp(-tau));
  let baseR=0.010+0.010*rearSheet;
  let baseG=0.055+0.020*frontSheet+0.010*bridgeSheet;
  let baseB=0.16+0.030*rearSheet;
  let gain=faceLight*e.residue*poleTaper;
  let er0=0.0012+0.030*frontSheet+0.040*rearSheet+0.022*bridgeSheet+0.030*formation+0.19*loadLight+0.16*fractureEdge+0.14*releaseLight;
  let eg0=0.0050+0.52*frontSheet+0.30*rearSheet+0.12*bridgeSheet+0.26*formation+0.30*loadLight+0.14*fractureEdge+0.19*releaseLight;
  let eb0=0.0090+0.40*frontSheet+0.66*rearSheet+0.18*bridgeSheet+0.18*formation+0.09*loadLight+0.05*fractureEdge+0.28*releaseLight;
  let coreTheta=select(select(select(0.92+1.00*(0.52+0.28*e.r),2.12,e.kind==1.0),2.08,e.kind==2.0),0.22+0.16*0.54,e.kind==3.0);
  let coreV=select(select(select(0.52+0.28*e.r,0.56,e.kind==1.0),0.42+0.14*sin(2.08-0.55)+0.05*sin(3.0*2.08)+gap+0.014,e.kind==2.0),0.54,e.kind==3.0);
  let halo=coreOn*e.core*angular(theta,coreTheta,0.10)*gauss((v-coreV)/0.05);
  let core=coreOn*e.core*angular(theta,coreTheta,0.032)*gauss((v-coreV)/0.016);
  let er=coverage*air*(er0*gain+0.14*halo+0.72*core);
  let eg=coverage*air*(eg0*gain+0.32*halo+0.98*core);
  let eb=coverage*air*(eb0*gain+0.40*halo+0.78*core);
  return Field(alpha*baseR+er,alpha*baseG+eg,alpha*baseB+eb,alpha,coverage,core*coverage,0.2126*er+0.7152*eg+0.0722*eb,nx,ny,nz,loadLight,frontSheet+rearSheet+bridgeSheet);
}
// 64-byte ABI. No background, caster, character UV, or baked vertex color; four peels and one overflow probe in field model.
struct Params { viewport:vec4f,event:vec4f,pose:vec4f,options:vec4f };
@group(0) @binding(0) var<uniform> p:Params;
@group(1) @binding(0) var previousDepth:texture_depth_2d;
@group(1) @binding(1) var<uniform> peel:vec4u;
struct RV { @builtin(position) position:vec4f,@location(0) uv:vec2f,
 @location(1) @interpolate(flat) sector:f32,@location(2) @interpolate(flat) band:f32 };
fn rotatePoint(g:Point)->vec3f{
 let cy=cos(p.pose.z);let sy=sin(p.pose.z);let cp=cos(p.pose.w);let sp=sin(p.pose.w);
 let x=cy*g.x+sy*g.z;let z=-sy*g.x+cy*g.z;return vec3f(x,cp*g.y-sp*z,sp*g.y+cp*z);
}
@vertex fn vs(@location(0) a:vec4f)->RV{
 let g=geometry(a.x,a.y,a.z,a.w,p.event.x,p.viewport.w,p.event.y);let pos=rotatePoint(g);
 let pix=p.pose.xy+vec2f(pos.x,-pos.y)*p.viewport.z;
 var o:RV;o.position=vec4f(2.0*pix.x/p.viewport.x-1.0,1.0-2.0*pix.y/p.viewport.y,0.5-0.15*pos.z,1.0);
 o.uv=a.xy;o.sector=a.z;o.band=a.w;return o;
}
struct Out { @location(0) rgba:vec4f,@location(1) depth:f32 };
@fragment fn fs(a:RV)->Out{
 if((u32(p.options.z)&(1u<<u32(a.band)))==0u){discard;}
 if(peel.x>0u){let old=textureLoad(previousDepth,vec2i(a.position.xy),0);if(a.position.z<=old+0.000002){discard;}}
 let f=material(a.uv.x,a.uv.y,a.sector,a.band,p.event.x,p.viewport.w,p.event.y,p.viewport.z,p.options.x,p.pose.z,p.pose.w);
 if(f.coverage<=0.00001){discard;}
 let rotatedNormal=rotatePoint(Point(f.normalX,f.normalY,f.normalZ));
 if(p.options.w==1.0 && rotatedNormal.z<=0.0){discard;}
 if(p.options.w==2.0 && rotatedNormal.z>0.0){discard;}
 var c=vec4f(f.r,f.g,f.b,f.a);
 if(p.options.y==1.0){c=vec4f(vec3f(f.a),f.a);}
 if(p.options.y==2.0){c=vec4f(vec3f(f.emissionY),f.a);}
 if(p.options.y==3.0){c=vec4f((vec3f(f.normalX,f.normalY,f.normalZ)*0.5+0.5)*0.85,1.0);}
 if(p.options.y==4.0){c=vec4f(vec3f(0.08+0.15*a.band,0.7-0.11*a.band,0.18+0.09*a.sector)*0.75,0.75);}
 return Out(c,a.position.z);
}
// Compute parity is separate from visibility, peeling, and rasterization quality.
struct Probe { config:vec4f,parametric:vec4f,settings:vec4f };
struct ProbeOut { point:vec4f,rgba:vec4f,diagnosis:vec4f };
@group(2) @binding(0) var<storage,read> probes:array<Probe>;
@group(2) @binding(1) var<storage,read_write> outputs:array<ProbeOut>;
@compute @workgroup_size(64) fn parity(@builtin(global_invocation_id) id:vec3u){
 if(id.x>=arrayLength(&probes)){return;}
 let a=probes[id.x];let g=geometry(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z);
 let f=material(a.parametric.x,a.parametric.y,a.parametric.z,a.parametric.w,a.config.x,a.config.y,a.config.z,a.config.w,a.settings.x,a.settings.y,a.settings.z);
 outputs[id.x]=ProbeOut(vec4f(g.x,g.y,g.z,f.coverage),vec4f(f.r,f.g,f.b,f.a),vec4f(f.core,f.emissionY,f.normalX,f.normalY));
}
