import test from 'node:test';import assert from 'node:assert/strict';import {OwnerClock} from '../src/owner-clock.mjs';import {DURATION} from '../src/contract.mjs';
const active={moving:true,acc2State:'active',acc2Effective:true};
test('pendingは積分しない',()=>{const c=new OwnerClock();assert.equal(c.advance(999),0);assert.equal(c.started,false);});
test('等速の完了',()=>{const c=new OwnerClock();c.start(100);c.advance(1700);assert.equal(c.age,DURATION);assert.equal(c.done,true);});
test('実効ACC2のみ800msで完了',()=>{const c=new OwnerClock(active);c.start(100);c.advance(900);assert.equal(c.done,true);});
test('途中の1→2→1の区分積分',()=>{const c=new OwnerClock();c.start(0);c.motion(active,400);assert.equal(c.age,.4);c.motion({...active,acc2State:'waiting'},800);assert.ok(Math.abs(c.age-1.2)<1e-12);c.advance(1200);assert.equal(c.age,DURATION);});
test('setMotionは位相を巻き戻さない',()=>{const c=new OwnerClock();c.start(0);c.advance(150);const p=c.phase;c.motion(active,150);assert.equal(c.phase,p);});
test('再startはoffsetを変えない',()=>{const c=new OwnerClock();c.start(0);c.advance(200);c.start(900);assert.equal(c.age,.2);assert.equal(c.wall,200);});
test('巻き戻し/非有限時間を拒否',()=>{const c=new OwnerClock();c.start(100);assert.throws(()=>c.advance(99));assert.throws(()=>c.advance(NaN));assert.throws(()=>c.start(Infinity));});
test('過大ステップを唯一のdurationで打ち切る',()=>{const c=new OwnerClock();c.start(0);c.advance(100000);assert.equal(c.age,DURATION);});
