import test from 'node:test';import assert from 'node:assert/strict';
import {stateAt,domainsAt,sampleField,composePixel} from '../src/field.mjs';import {SHAPE,TIME} from '../src/shape-data.mjs';
test('源・輸送中・受領済みの表示量が保存される',()=>{for(let i=0;i<=1000;i++){const s=stateAt(i/1000);assert.ok(Math.abs(s.source+s.transit+s.received-1)<1e-12);assert.ok(s.source>=0&&s.transit>=0&&s.received>=0);}});
test('到達より前に受領量を増やさない',()=>{for(let p=0;p<=TIME.emitStart+TIME.transitDelay;p+=.001)assert.equal(stateAt(p).received,0);});
test('受領済み量が全区間で非減少',()=>{let last=0;for(let i=0;i<=1000;i++){const s=stateAt(i/1000);assert.ok(s.received>=last);last=s.received;}assert.equal(last,1);});
test('全active位相で源・輸送・受領の支持形が残る',()=>{for(let i=0;i<161;i++){const p=i/161;for(const[x,y]of [[0,-3],[0,-33],[0,-92]]){const f=sampleField(x,y,p,{layers:7});assert.ok(f.primary>.99);assert.ok(f.alpha>.70);}}});
test('3区画の接合が幾何学的に重なる',()=>{assert.ok(domainsAt(0,-12).source>.9&&domainsAt(0,-12).transport>.9);assert.ok(domainsAt(0,-58).receiver>.9&&domainsAt(0,-58).transport>.9);});
test('搬送の幅をH64の細線へ縮めない',()=>{for(let y=-50;y<=-20;y+=1){let width=0;for(let x=-30;x<=30;x++)if(domainsAt(x,y).transport>.5)width++;assert.ok(width*.5>=12);}});
test('終端は全層が同時にゼロ。glowだけ残らない',()=>{for(const p of [-.001,1,1.001])for(let y=-127;y<=13;y+=7)for(let x=-66;x<=66;x+=11){const f=sampleField(x,y,p);assert.equal(f.alpha,0);assert.deepEqual(f.bloom,[0,0,0]);assert.deepEqual(f.light,[0,0,0]);}});
test('指定包絡の外に本体/観測効果を漏らさない',()=>{for(const p of [0,.25,.5,.75,.999])for(const[x,y]of [[-67,0],[67,0],[0,-128],[0,14]]){const f=sampleField(x,y,p);assert.equal(f.alpha,0);assert.equal(f.bloom.reduce((a,b)=>a+b,0),0);}});
test('低減モーションでも因果形と受領面積は変えない',()=>{for(const p of [.10,.25,.50,.75,.95])for(const[x,y]of [[0,-5],[0,-35],[0,-85],[25,-95]]){const a=sampleField(x,y,p),b=sampleField(x,y,p,{reducedMotion:true});assert.equal(a.primary,b.primary);assert.equal(a.fill,b.fill);assert.equal(a.alpha,b.alpha);}});
test('OBSを外しても有色本体を保持',()=>{for(const p of [0,.25,.5,.75,.99])for(const[x,y]of [[0,-5],[0,-35],[0,-85]]){const f=sampleField(x,y,p,{layers:7});assert.ok(f.alpha>.7);assert.ok(Math.max(...f.rgb)-Math.min(...f.rgb)>.07);assert.deepEqual(f.bloom,[0,0,0]);}});
test('暗明の出力は有限0..1',()=>{for(const bg of ['dark','light'])for(const p of [0,.25,.50,.75,.999,1])for(let y=-120;y<13;y+=5)for(let x=-66;x<67;x+=5)for(const v of composePixel(x,y,p,{background:bg}))assert.ok(Number.isFinite(v)&&v>=0&&v<=1);});
test('受領面積が空→中間→満量で増える',()=>{const area=p=>{let a=0;for(let y=-109;y<-53;y++)for(let x=-47;x<47;x++)a+=sampleField(x,y,p).fill;return a;};assert.ok(area(.50)>area(.25)+200);assert.ok(area(.81)>area(.50)+500);});
