"""採用済み設計のB-Expression-2記録。画像生成命令ではない。"""
from pathlib import Path
import json, copy
ROOT=Path(__file__).resolve().parents[1]
DOMAINS=['Thermo','Fluid','Optics','Materials','Electromagnetics','Rheology','WaveOptics','SurfaceScience']
PIN={'commit':'8ad8e9b07ab8dc8737dd9b4022a775bce61d16e1','base_blob':'4e10a53310be5b9d0aa3a6c881cf4f39d6590bd4','extension_blob':'0eda016558e426ff4142d850d26200b40fafd834'}
A={'event':'action-rational-free','radius':145,'peak':156,'name':'支払い拘束の解除場','main':'角を面取りした二つの開放ラメラが左右へ開き、中央の通路を残す。閉鎖の継ぎ目だけが早い白色極値を持つ。','state':'0–72 msで拘束を提示、72–290 msで左右へ開放、290–820 msで開口を保持、820–1200 msでその場で消灯。','source':'上左／下右の解除継ぎ目','color':'銅色の厚み、琥珀色の内部放射、継ぎ目の象牙白色芯','optics':'横長0.125R×0.025Rと局所0.061R×0.073Rの解析PSF。source powerの0.34/0.12係数。','forbid':'MP獲得・MP回復・資源吸収・対象射出・硬貨・数値・上昇粒子を描かない。','sfx':'32 ms付近の乾いた解除音と155 ms付近の短い明るい解放共鳴。同一PCM声内で合成し、上昇アルペジオや獲得音を避ける。','phase':'action_peak'}
B={'event':'action-ninjutsu-focus','radius':115,'peak':610,'name':'術者局所の張力収束場','main':'左右で長さの異なる非閉鎖の曲面が内側へ寄り、術者の脇で稜線が張る。上下を閉じず、標的を囲わない。','state':'0–120 msで場を成立、120–640 msで内向きに収束、640–900 msで張った準備状態を保持、900–1200 msで局所消灯。','source':'曲率拘束が強い左右の縦稜線','color':'濃藍の面内部、紫の張力稜線、局所の淡紫白色芯','optics':'縦長0.047R×0.153Rと局所0.093R×0.052Rの解析PSF。source powerの0.16/0.052係数。','forbid':'命中・キル・刃の射出・標的への線・対象位置の推測・4秒カウントダウンを描かない。targetIdは空でも同じ形と音。','sfx':'開始時から徐々に立ち上がる帯域制限された摩擦と低い弦状成分。610 ms近辺で張力感が最大となり、打撃音を入れず減衰する。','phase':'anticipation'}
def domain(app,role,items,evidence):return {'applicability':app,'role':role,'items':items,'evidence_or_constraint':evidence}
def domains(c,receiver):
 out={}
 reasons={'Thermo':'非現実の能力Eであり、発光色から温度・燃焼・化学反応を推定しない。','Fluid':'静穏空気を媒体条件とするが、場を流体として輸送しない。煙・風・粒子を新設しない。','Electromagnetics':'ゲーム能力の入力を電荷や電流の実測値と同一視しない。','Rheology':'時間包絡は宣言場の制御であり、実在粘弾性・機械的緩和と偽らない。','WaveOptics':'干渉・回折を世界PHへ追加しない。解析PSFはOBS1の観測設計でありPHの波動現象ではない。','SurfaceScience':'濡れ・汚れ・付着・液体界面を使用しない。'}
 for d in DOMAINS:
  if d=='Optics':
   out[d]=domain('applicable','primary',(['PH1からPH2へ方向と距離に依存する照度を渡す。','拡散応答と粗いGGX反射を分け、光源色を受光面の反射色へ写像する。'] if receiver else [c['source']+'が自己放射し、白色芯の位置と強度をsourcePoint/sourcePowerで共有する。','面の被覆率と放射量を分離し、外縁を弱く、稜線・継ぎ目を局所極値にする。']),('PH2受光法線により左右明度が変わる。ReflectionClosureBlock.PH2。' if receiver else c['color']+'。PH2とOBS1が同じ入力源を参照する。'))
  elif d=='Materials':
   out[d]=domain('applicable','primary',(['既存actorの材質をプレビューでは粗い不透明誘電体として校正する。','法線場と粗さ分布を独立に持ち、全域を一様発光の縁にしない。'] if receiver else [c['main'],'declared_fantasyの表面・断面状態として厚みと不透明度を定め、実在物質の測定値とはしない。']),('PH2の面法線、roughness=0.78+0.08*normal.y、F0=0.04は検査体の設計仮定。' if receiver else '色本体はbody、放射はemission、被覆はcoverageとして別量を実装。'))
  elif d=='Thermo' and receiver:out[d]=domain('applicable','latent',['入射光の非反射分は表面の吸収へ入り、短い検査時間では温度変形を描かない。'],'PH1からの入力に対し放射・吸収の収支を定性的に置く。温度・熱容量の実測はない。')
  else:out[d]=domain('not_applicable','latent',[reasons[d]],('PH2の固定表面条件。' if receiver else 'PH1のdeclared_fantasy条件。')+reasons[d])
 return {'conform_to':'OctaDomainTemplate','all_8_domains_required':True,'Domains':out}
def physical_link(c):return {'source':'PH1','target':'PH2','mechanism':'既存actor受光面へ、sourcePoint/sourcePowerから幾何減衰と法線依存の照明を与える。','consequence':c['color']+'に対応する局所受光。MP・姿勢・対象判定は変えない。'}
def ph(c,receiver=False):
 pid='PH2' if receiver else 'PH1'
 name='既存actor受光表面の校正代理' if receiver else c['name']
 partition='既存actor表面は場とは別の法線・被覆・受光境界を持つ。校正体をEの追加人物として扱わない。' if receiver else '一つの場の主形・内部・継ぎ目／稜線は同じ入力と時間状態を持つため一PHに統合する。'
 evidence=['局所光が当たる側と反対側の明度差','粗い法線依存反射と、光源色を受ける拡散色の差'] if receiver else [c['main'],c['source']+'の白色芯と外縁の減衰差']
 identity={'id':pid,'name':name,'origin':'attribute_resolved' if receiver else 'declared','anchor':'object','visibility':'visible','local_state_difference':'法線・受光量・粗さに応じて面応答が異なる。' if receiver else c['state'],'partition_reason':partition}
 model={'model_kind':'rigid_or_articulated' if receiver else 'declared_fantasy','system_boundary':'PH2の既存actor受光領域。プレビューの形は非人物の26×64 game-unit校正体。製品人物の造形や動作を変更しない。' if receiver else f'actor位置x/yを中心とする半径{c["radius"]} game-unitの有限場。0≤age<1200 actor-ms。','state_variables':'位置x/y・面法線・粗さ・拡散色・反射放射輝度（相対値）。' if receiver else 'age actor-ms、開放／収束パラメータ、被覆率、色本体、source power、放射輝度（相対値）。','inputs':'PH1のsource位置・power・色。測定体の形状は固定された検査境界条件。' if receiver else '上流で成立した正規eventId/causeId/playerId/actorStartMsとx/y。条件の成立を描画側で再判定しない。','balance_conditions':{},'constitutive_response':'Lambert拡散と粗いGGX反射。Schlick Fresnel、GGX NDF、Smith型masking/shadowingを用いる。' if receiver else 'declared_fantasyの有限場。入力をsampleEffectの包絡へ写像し、fieldのbody/coverage/emissionを別に評価する。','initial_condition':'既存actor姿勢入力が未提供のプレビューでは固定校正体。' if receiver else 'event開始前は不在。開始後は指定立ち上がりを一回だけ辿る。','boundary_conditions':'校正体は外部で固定された剛体境界。床や地面反力を描画目的で追加しない。' if receiver else '半径0.90Rから0.985Rへ外縁を収束。1200 msで消滅。場外へ移動体を放出しない。','approximation_scope':'actorの人体・衣装・材質を推定しない。校正体のF0やroughnessは仮定。主ゲームのマスク／材質との一致は未検査。' if receiver else '宣言されたゲーム能力を実在物理の実証としない。2.5D固定直交視点の解析場であり、任意視点の3D体積ソルバーではない。'}
 for key in ['mass','momentum','energy','charge']:
  if key=='energy':status='applicable';desc='PH1の外部駆動による放射はPH2の反射・吸収および観測境界へ流出する。絶対J/W値は測定しておらず、相対放射として閉じる。'
  elif receiver and key=='mass':status='applicable';desc='校正面の質量生成・粒子放出はない。受光によって質量を変更しない。'
  elif receiver and key=='momentum':status='applicable';desc='固定校正境界が位置を維持する。光圧・姿勢変化は表示尺度で解かない近似であり、ノックバックを生成しない。'
  else:status='not_applicable';desc={'mass':'場を物質流やMP実体としないため独立した物体質量を与えない。','momentum':'宣言場の形状制御であり力学的投射・対象への運動量輸送を行わない。','charge':'電荷輸送、電流、導電経路を宣言していない。'}[key]
  model['balance_conditions'][key]={'status':status,'balance_or_reason':desc}
 cue_roles=[{'cue':e,'supports':'既存actorへの局所受光' if receiver else c['name']+'の現在相','reliability_and_overlap':'白色芯と局所明度は共通sourceに依存し統計的独立とは主張しない。'+('法線差は源位置を固定した比較で判別する。' if receiver else '主形の開口／曲率は光量だけとは異なる手掛かり。')} for e in evidence]
 p={'identity':identity,'DeepStructure':{'Core':'PH1の最大源に近い面で法線と照度の組合せが極値となる。' if receiver else c['source']+f'が{c["peak"]} actor-ms近辺で極値。','Structure':'法線が面上で連続し、中心と左右で反射軸を分ける。' if receiver else c['main'],'Surface':'不透明境界で後方の場を遮蔽し、粗さにより反射を広げる。' if receiver else '色本体の厚い外縁、鋭い内稜線、局所芯の境界幅を区別する。'},'PhysicalModel':model,
 'ScaleRegime':{'characteristic_length':'校正体高64 game-unit。1 game-unit=0.01mは設計用尺度仮定。' if receiver else f'R={c["radius"]} game-unit。1 game-unit=0.01mと仮置きしたときR={c["radius"]/100}m。ゲーム実測尺度とは主張しない。','characteristic_time':'源に対する光学的応答。機械的遅延を導入せず、観測基準時点で評価。' if receiver else c['state']+'時刻はactor-clockでありwall-clock秒へ固定しない。','dominant_balance':'入射幾何と表面反射が支配。熱変形、光圧、運動は無視する。' if receiver else '宣言場の有限境界と指定包絡が支配。自然流体の慣性・表面張力で形を説明しない。','dimensionless_reasoning':'粗さ・Fresnel値は無次元の校正仮定。Re/Weは非該当。' if receiver else '位置はR、時刻は1200 actor-msで正規化。Re/Weは流体・液体界面でないため非該当。','detail_cutoff':'H64 actor基準とE全包絡H64を分ける。最低線幅は出力画素の1/scaleへ接続し、微細稜線だけを意味の唯一の証拠にしない。'},
 'OctaDomain':domains(c,receiver),'PerceptualReadability':{'direct_evidence':evidence,'indirect_evidence':'PH1とPH2の位置対応、OBS無効時でも主形が残ること。','figure_ground_separation':'medium','edge_legibility':'明背景では色本体と暗い面、暗背景では彩色放射と局所芯を使う。','perceptual_failure_risk':'抽象的な校正体では実ゲームの人物マスクとの干渉を判定できない。' if receiver else c['forbid']+'単一静止画だけでは能力の意味を一意に識別できない。','cue_roles':cue_roles,'confusable_alternative':'自己発光するactorと誤認し得る。' if receiver else ('資源獲得や静的HUDの枠との誤認。' if c is A else '攻撃の斬撃／防御膜との誤認。'),'disambiguating_evidence':'PH1光源の位相と方向に一致する受光。源OFF比較で受光差が消える。' if receiver else '開放後に停止して局所消滅すること。' if c is A else '非閉鎖曲面が内側へ寄るだけで、対象方向に伸びず、命中相を持たないこと。','viewing_conditions':'CSS1×・actor H64校正体、またはE包絡直径64 CSS px。明暗背景。実表示距離・環境光・実GPUは未確定。'},
 'GeometryConstraint':{'surface_orientation':'カメラ前方を向く曲面校正体。' if receiver else 'actor周囲の2.5D層。カメラは固定直交。','normal_field_coherence':'normal=normalize(x/14,y/130,0.75)。連続する面法線を使用。' if receiver else '厚みのbevelと稜線を同じ主形の距離場に従属させる。','curvature_behavior':'校正面はなだらか。' if receiver else ('面取りされた角形経路。' if c is A else '左右で長さの異なる二つの放物線状断面。'),'silhouette_logic':'高さ64の非人物基準体。人体・関節の代用品として品質承認しない。' if receiver else c['main'],'contact_relation':'固定境界。床・着弾対象・衝突面の追加なし。','spatial_relation':'PH1の受光源位置と同じx/y変換を使う。' if receiver else 'x/yのみのcaster-local。targetの位置・向きを取得しない。'},
 'StateDynamics':{'state_space_extent':'源強度に従う反射状態。姿勢は固定。' if receiver else c['state'],'transition_path_character':'equilibrium-maintained' if receiver else 'monotonic','local_stability_type':'stable','convergence_behavior':'源の消滅とともに追加受光はゼロ。' if receiver else '開放／収束の後に所定の保持区間へ入り、1200 msでゼロ。','damping_profile':'機械的減衰ではなく源に対する即時反射。' if receiver else '末尾のsmoothstepによる単調な局所消灯。運動エネルギーの消失とは呼ばない。','oscillation_pattern':'none','equilibrium_recovery':'源OFF後は基準照明だけへ戻る。' if receiver else '場は消滅し、MPや対象状態を変更しない。','transition_failure_risk':'光を慣性で遅らせること。' if receiver else '遅着／再送によってピークを再生し直すこと。','driving_input':model['inputs'],'response_timescale':'PH1のactor-timeサンプルと同時。' if receiver else 'ScaleRegime.characteristic_timeとsampleEffectの区間を一致させる。','phase_relation':'PH1と同じ時点。光学応答へ遅延を追加しない。' if receiver else '主形・局所芯・受光・OBS・SFXは同一原因の時刻を読む。別Eとは時計を共有せずplayerごとに解決する。','stability_condition':'固定校正境界と有限source power。' if receiver else '0≤age<1200。場の定義域外と終了後は出力ゼロ。'},
 'Couplings':{'DominantCouplings':['PH1.Optics -> PH2.Optics: 発光源の位置・強度から受光を計算。','PH2.Materials -> PH2.Optics: 法線・roughnessがGGXと拡散を拘束。'] if receiver else ['PH1.Materials -> PH1.Optics: 主形の厚みと稜線位置が放射分布を拘束。','PH1.Optics -> PH2.Optics: 局所sourceから既存actor表面へ照明。'],'SecondaryCouplings':[],'CausalAssessment':{'intervention':'時刻・主形を固定してlocalLightをOFF。' if receiver else 'sourceを固定してOBSをOFF。別比較でageのみを掃引。','predicted_response':'actor表面の方向性を持つ明度差だけが消える。' if receiver else '主形と色本体は残り、光学的に広がった裾だけが消える。','competing_explanation':'背景明度やtone mapでも見え方は変わるため、比較背景を固定する。','uncertainty':'実材質・実GPU・実視認条件は未照合。CPU参照比較はWGSL画素の実測ではない。','check_status':'tested','evidence_refs':['evidence/cpu-pixel-tests-all-all.json','tests/cpu_reference.py']}},
 'CausalityLinks':{'physical_influence':[physical_link(c)],'observation_dependency':[{'source':'OBS1','target':pid,'basis':'PH1は源入力、PH2は遮蔽と保護マスクの入力。'},{'source':'OBS2','target':pid,'basis':'線形world合成結果を表示色へ変換するため。'}],'gaze_path':[{'source':'PH1','target':'PH2','reason':'場の開口／張力から術者の局所受光へ読む。'}]},
 'Evidence':{'direct':evidence,'indirect':['源と受光が同じactor-time相にあること。'],'candidates':[]},'SurroundingChanges':{'entries':[{'target':'PH1' if receiver else 'PH2','change':'遮蔽される場の後方領域を拘束。' if receiver else '位置と法線に依存する局所光。対象への力・リンクを生じない。'}],'latent_reference_target':'none'},
 'VisualProjection':{'role':'supporting' if receiver else 'essential','world_state_ref':pid+'.StateDynamics','retained_cues':evidence,'simplification':'2Dアニメ志向の明瞭な輪郭。微細な材質をH64へ整理し、主形と接続関係を保持。reduced motionはUIで明示選択された別検査条件で、基準状態はfalse。','omission_scope':[],'exaggeration_scope':[],'ambiguity_scope':[],'intent_ref':'InferenceExpansionPolicy.ExpressionIntent'},
 'BeautyStructureApplication':{'conform_to':'PlatonicGoodTemplate.BeautyStructuring','target_policy':'standard','adjustment_reason':'not_applicable（標準の二軸を既存証拠から採用）','axes':({'material_response':['方向性のある局所拡散光','粗い面の視線依存反射'],'contrast':['既存面の中立色と光源反射色の差','受光側と反対側の明度差']} if receiver else {'whitespace_density':['中心のactor可読域を空ける','場の外側には新規粒子を置かない'],'temporal_phase':['主形の変位と源極値のずれ','保持区間と末尾消灯の区別']})},
 'GTBConnections':{'Good':'正規イベントの意味とcaster-local関係を保つ。','Truth':'入力座標、相対時刻、源と受光を同じ解析値へ束縛する。','Beauty':'主形の開口／曲率と色本体を光学的裾から分離する。'},
 'AcceptanceCriteria':{k:True for k in ['full_structure_present','all_8_domains_present','visibility_specific_evidence_present','physical_and_observation_links_not_mixed','physical_model_scale_and_response_consistent','perceptual_cues_and_identifiability_limits_explained','causal_assessment_status_matches_evidence']},'FailurePatterns':['label_only','uniform_response','source_independent_glow','authority_reinterpretation','target_link_inference','causal_hypothesis_reported_as_measured_result']}
 return p

def build(c):
 ps={'PH1':ph(c),'PH2':ph(c,True)}
 intent={'source':'user_declared','purpose':'二つの独立した世界内Eをゼロから実装し、H64で原因と状態を識別できる試作として検証する。','must_communicate':[('今回のオペ能力だけMP支払いが不要になった瞬間。' if c is A else '忍殺の準備開始。攻撃・命中・キルではない。'),'1200 actor-msのE寿命とcaster-localの範囲。'],'preserve_ambiguity':[],'allowed_omission':[],'allowed_exaggeration':[],'protected_relations':['正規eventId/playerId/targetId/actorStartMsを保持','権威判定を再解釈しない','一原因一声','既存E造形・画像texture・Canvas2Dを流用しない',c['forbid']]}
 obs={}
 obs['OBS1']={'operation_type':'posteffect','input_references':['PH1','PH2','optical_condition'],'target_mask':'PH1のsource束縛領域。0.985R以内。既存actorマスクでは裾を0.18倍とする。','stage':'world_render_observation','composite_method':'add','intensity':c['optics']+'基底IntensityBudgetを唯一の全体上限とする。','protected_regions':['actor中央の形状','半径外の背景','PH1の色本体'],'output_consequence':'白い芯自体はPH1。ここでは同じsourceに従う異方性の光学的裾を加える。物理レンズゴーストを捏造しない。','dependencies':['PH1','PH2','optical_condition'],'sampling_consequence':'画素AAとR比例PSFを別に計算。E全包絡H64ではサブピクセルの芯が失われ得る。時間積分は行わない。'}
 obs['OBS2']={'operation_type':'tone','input_references':['PH1','PH2','OBS1','display_condition'],'target_mask':'world/observationの合成画面全体。ただし形状マスクを生成しない。','stage':'display','composite_method':'replace_with_constraint','intensity':'露出1.0の既定表示。ACES近似の有理式とsRGB変換。IntensityBudgetを参照。','protected_regions':['主形の輪郭','actor形状','既存色本体'],'output_consequence':'相対線形HDRを有限の表示範囲へ写像。強いsourceでは小面積の白色を許容し、色本体まで一律に白くしない。','dependencies':['OBS1','PH1','PH2','display_condition'],'sampling_consequence':'RGBA8への量子化。出力解像度とCSS倍率を分け、CPU参照とGPUの精度差は実機比較が必要。'}
 budget={'global_observation_budget':'源局所だけへ解析PSFを加算。背景全体の明度持ち上げ・一律白芯抑制をしない。','para':'none（未選択）','flare_gradient':'none（未選択）','glow':c['optics'],'diffusion':'none（輪郭を全面ぼかししない）','grain':'none（未選択）','chromatic_aberration':'none（未選択）','protected_region_priority':'highest','intentional_departures':[]}
 d={'FoundationOperationTemplate':{'OutputContract':{'schema_version':'B-Expression-2','mode':'Image','operation':'design_only'},'TemplateConsolidation':{'per_chapter_template_count':1,'template_position':'chapter_end','inter_template_duplication_forbidden':True,'cross_chapter_reference_preferred':True},'RuleContract':{'fields':['rule_id','owner','priority','applies_when','requirement','exception_to','validation_id'],'same_priority_resolution':'explicit_exception_or_compatible_union','unresolved_conflict_result':'spec_conflict','source':'provenance/source-revision.json'},'GlobalInterpretation':{'world_registry':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registry':'ObservationIntegrationTemplate.ObservationRegistry','full_PH_structure_required_for_all_visibilities':True,'WindCapsule_required':True},'UniversalNoLabelOnly':{'label_only_declaration_forbidden':True,'indirect_evidence_for_implicit_latent':True},'Acceptance':{'unique_rule_ids_and_resolvable_references':True}},
 'InferenceExpansionPolicy':{'DeclaredIntent':{'character_count':'not_specified（actorの人間性・外見を推定しない。プレビューは非人物校正体）','character_attributes':{},'main_action':intent['must_communicate'][0],'main_objects':{'E':1,'existing_actor_receiver':1},'background':'プレビュー用の明暗display fixtureだけ。ゲーム世界の床・背景物を追加しない。','style':'2Dアニメ志向の輪郭と材質分離。実装は手続き型WebGPU。','text_logo_policy':'世界内に文字・ロゴを描かない。ギャラリーUIと検査ラベルは表示資料。'},'ExpressionIntent':intent,'SelectionLifecycle':{'stages':['candidate','accepted','registered_world','registered_observation'],'candidate_catalog_in_final_code':False,'world_registry':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registry':'ObservationIntegrationTemplate.ObservationRegistry','adoption_checks':['DeclaredIntent_consistency','contribution','readability','activation_condition']},'inferred_support_elements':{'default_permission':'denied','explicit_user_permission_required':True,'allowed_domains':[],'allowed_scope':'user_explicitly_authorized_targets_and_domains_only','support_declared_elements_without_overriding_them':True,'latent_visualization_object_not_required':True},'Acceptance':{'declared_intent_preserved':True,'inference_without_explicit_user_permission_absent':True,'candidate_accepted_registered_distinguished':True,'unselected_candidates_absent_from_final':True}},
 'PlatonicGoodTemplate':{'Good':{'evidence':'上流イベントと術者局所性を維持し、対象・MP・キルを再解釈しない。'},'Truth':{'coordinate_continuity':'受信x/y→world→camera→screenを同じ変換で使用。','physical_causality':'PH1源→PH2反射、OBS1はその源を参照。','state_transition_readability':c['state']},'Beauty':{'boundary_readability':'色本体・稜線・白芯・光学的裾を分離。','gaze_circulation':'主形→術者受光と、開口→反対側境界の二系統。','structural_separation':'個数・主形をglowで代用しない。'},'BeautyStructuring':{'axes':['ratio_proportion','balance_symmetry','contrast','rhythm_repetition','whitespace_density','hierarchy_gaze_flow','material_response','temporal_phase'],'standard_minimum_axes_per_PH':2,'standard_minimum_evidence_per_applied_axis':2,'intent_adjustment_ref':'InferenceExpansionPolicy.ExpressionIntent'},'Acceptance':{'each_PH_connected_to_at_least_two_GTB_layers':True,'single_formula_does_not_dominate_beauty':True}},
 'PhenomenonSystemTemplate':{'PartitionPolicy':{'criterion':'PH1は一つの宣言場。PH2は既存actorの独立した受光面。学問名や描画層数で分割しない。','shared_condition_policy':'x/yとactor-time、固定直交視点は共有するが局所の法線・源強度は保持する。','no_discipline_based_split':True},'SharedConditions':{},'PhenomenonRegistry':{k:copy.deepcopy(v['identity']) for k,v in ps.items()},'PhenomenonBlock':ps,'Acceptance':{'all_PH_have_required_full_structure':True,'visible_implicit_latent_have_same_field_set':True,'OBS_not_in_PH_registry':True,'PIA_resolved_as_identification_lifecycle':True}},
 'PEMTemplate':{'Mode':{'phenomenon_equality':True,'focus_phenomenon':'none'},'CausalMesh':{'physical_mesh_required':True,'gaze_target_policy':'standard','adjustment_reason':'not_applicable（既存形状の二経路を利用）','gaze_path_A':'PH1の開口／張力源→PH2の局所受光。','gaze_path_B':'PH1の一方の端→中央の余白→反対側の端。','local_extrema_connected_to_gaze_paths':True},'AttentionControl':{'attention_focus':'hierarchical','single_requires_explicit_request':True},'Acceptance':{'no_unexplained_isolation':True,'gaze_paths_match_selected_policy_and_explicit_intent':True,'local_peak_returns_to_mesh':True}},
 'CoordinateGravityWindTemplate':{'WorldApplicability':{'status':'applicable','reason':'PH1の宣言場とPH2の既存actor受光面がある。'},'Units':{'length':'m','time':'s','temperature':'K','pressure':'Pa','angle':'rad'},'WorldCoordinates':{'handedness':'right_handed','X':'right_positive','Y':'up_positive','Z':'backward_positive','camera_forward':'negative_Z','origin':'declared_anchor_origin'},'CameraCoordinates':{'X':'right_positive','Y':'up_positive','forward':'negative_Z','projection':'orthographic','FOV_or_scale':'1 game-unit=0.01mの設計用換算。基準は1 game-unit/CSS px。'},'ScreenCoordinates':{'domain':'[0,1]x[0,1]','x':'0_left_to_1_right','y':'0_top_to_1_bottom'},'TransformChain':{'order':['world','camera','screen'],'world_to_camera':'game(x,y)→world(0.01x,-0.01y,z)。actor原点を共有。カメラは+Z側から-Zへ。','camera_to_screen':'pixel=(game-cameraCenter)*CSSscale*DPR+physicalViewport/2。screen yは下正。'},'ContactCoordinates':{'contact_patch':'none（床・衝突面を要求しない）','contact_normal':'none','support_relation':'not_applicable','no_penetration':True},'VectorField':{'dominant_vector':{'direction':'左右外向き' if c is A else '左右から内向き','magnitude':'sampleEffect.shapeでRに対する変位を定義。','falloff':'有限半径0.90R..0.985R','fluctuation':'none（ランダムな揺れを追加しない）'},'secondary_vector':{'direction':'source→既存actor面','magnitude':'sourcePowerと幾何減衰','falloff':'距離二乗を含む放射近似','fluctuation':'none'}},'Gravity':{'condition':'normal','vector':[0,-9.81,0],'strength':'設計上の通常重力仮定。宣言場は重力で落下しない。','affected_responses':'PH2の位置は上流または校正用固定境界が維持。PH1に落下粒子や風を追加しない。','evidence':'校正面の鉛直と位置維持を拘束として保持。重力自体の可視測定証拠とはしない。床なしの検査で接地影を要求しない。'},'WindCapsule':{'required':True,'medium_state':'air','medium_properties':{'density':'非ゼロの静穏空気。数値物性は未測定。','viscosity':'空気の粘性をEの形状制御へ結合しない。'},'Field':{'direction':'zero','speed':'0 m/s（設計条件）','gust':'none','shear':'none','turbulence':'none'},'ApplicableResponses':{'body':'not_applicable（人体運動を生成しない）','cloth':'not_applicable（衣服を生成しない）','hair':'not_applicable（髪を生成しない）','loose_elements':'not_applicable（粒子を追加しない）','environment':'静穏媒体のみ。風の可視証拠を追加しない。'},'non_applicable_responses_explicit':True},'Acceptance':{'world_camera_screen_transform_defined':True,'screen_axis_convention_defined':True,'Gravity_present':True,'WindCapsule_present':True,'medium_state_present':True,'no_inapplicable_wind_evidence_required':True}},
 'OctaDomainTemplate':{'Domains':{n:{'definition_ref':'基底.md OctaDomain Definition','per_PH_resolution':['PH1.OctaDomain.Domains.'+n,'PH2.OctaDomain.Domains.'+n]} for n in DOMAINS},'Acceptance':{'all_8_domains_present':True,'role_classification_present':True,'latent_does_not_require_direct_visualization':True,'non_applicable_domains_retained_with_reason_and_latent_role':True}},
 'AnimeStudiesTemplate':{'KeyframeSnapshot':{'phase':c['phase'],'state_t_minus_1_evidence':'源極値より前の開放／収束途中の主形。','state_t_evidence':f'{c["peak"]} actor-msの源極値と主形。','state_t_plus_1_evidence':'保持相を経て局所消灯する。'},'Layout':{'staging':'中心の術者可読域と、左右の場の前後関係を分ける。','projection_consistency_ref':'CoordinateGravityWindTemplate','whitespace_role':'射出先ではなく術者の可読域。'},'PoseActing_or_SceneActing':{'character_ref':'not_applicable（人物身体を描画せず校正体のみ）','object_balance':'PH2は固定校正境界。','contact_logic':'床・対象・着弾接点は追加しない。'},'MotionReadability':{'motion_blur_smear_speed_line_policy':'explicit_user_request_only','primary_causality_replacement_by_motion_effects':False},'CompositeIntegration':{'observation_ref':'ObservationIntegrationTemplate','contact_shadow_used_for_integration':'not_applicable（床・支持面なし）'},'Acceptance':{'previous_and_next_time_or_explicit_ambiguity_accounted_for':True,'projection_consistent':True,'posteffects_do_not_replace_primary_causality':True}},
 'ObservationIntegrationTemplate':{'ObservationRegistry':obs,'SamplingContract':{'output_resolution':'実行時canvasのCSS寸法×DPR（上限2）を実デバイスmaxTextureDimension2D以内に設定。CPU参照は別記録。','intended_display_scale':'actor H64 CSS pxでscale=1。E全包絡H64はscale=64/(2R)。2×は観察用で実寸合格の代用にしない。','spatial_detail_policy':'距離場の画素AAで細稜線を扱う。主形を最小単位とし、芯や微細溝の消失・モアレはGPU再検査対象。','temporal_sampling':'Image設計の基準時点にはframe cadence非該当。E実装はactor-clockをrAFごとにサンプルし、時間積分・残像を追加しない。','filter_and_resample_policy':'WGSL内の解析AA。画像textureのresampleはない。実GPU帯域制限や多重標本化を実行済みとは主張しない。'},'ImageIntegration':{'ToneColor':['OBS2'],'LightIntegration':['OBS1'],'ShadowDensity':[],'DepthAir':[],'EdgeLine':[],'TextureOutput':[]},'LensFlareField':{'registry_id':'none','artifact_type':'optical_observation_artifact','world_anchor':'none','SourceMapping':{'source_state':'none','source_id':'none','source_screen_position':'none','source_luminance_rank':'none'},'ResponseVisibility':{'level':'none','reason':'内部反射ghostを選択していない。source束縛の解析PSFはOBS1として別に記述する。'},'LensModel':{'flare_mode':'latent','coating_strength':'high','aperture_state':'mid','anamorphic':False},'SpatialBinding':{'image_center_relation':'not_applicable（ghostなし）','optical_axis_offset':'none','chain_axis':'none'},'Responses':{'Ghost':'none','Veil':'none','Streak':'none（OBS1のsource PSFとレンズゴーストを混同しない）','Spectral':'none'}},'IntensityBudget':budget,'CompositeValidation':{k:'not_tested' for k in ['contour_preserved','highlight_clipping','shadow_crushing','chroma_displacement','fine_detail_retention','protected_background_preserved']},'Acceptance':{'OBS_separate_from_PH':True,'physical_lensflare_source_binding_preserved':True,'display_artifact_does_not_fake_physical_source':True,'intensity_budget_is_single_source_of_truth':True,'sampling_conditions_and_actual_execution_distinguished':True}},
 'ExtremumDesignColorTemplate':{'PEV':{'candidate_state_set':[f'採用済みS1: {c["peak"]} actor-ms。'+c['main']],'selected_physics_extremum':'S1','reason':'主形の移行とsource極値が同時に読める基準点。'},'AES':{'selected_from_PEV_only':True,'visual_circulation':'二つの端と中心可読域を結ぶ。','asymmetric_balance':'左右で異なるsource位置を用い、人物を追加せず明度重心を分ける。','tension_release':'解除と収束を別の単調変位と保持相で区別。','body_environment_consonance':'受光色をPH1源へ結ぶ。実人物との調和は未検査。','selected_aesthetic_extremum':'S1'},'DesignScience':{'VisualHierarchy':'主形→局所source→既存actor受光→OBSの裾。','DensityPlan':'主形境界に情報を置き、中心と外周を空ける。','ShapeOrder':c['main'],'OrnamentFunction':'追加装飾なし。内部線は状態・厚みを読むためだけに使う。'},'CCM':{'Palette':{'base':'銅色' if c is A else '濃藍','secondary':'琥珀' if c is A else '紫','accent':'象牙白' if c is A else '淡紫白','neutral':'校正actorの低彩度灰色'},'ColorDynamics':{'temp':'warm' if c is A else 'cool','value_range':'暗い色本体から局所白色芯まで。全域を同じ明度にしない。','saturation':'色本体は有彩色を残し、sourceの中心だけが白へ近づく。'},'Lighting':{'key_K':'not_applicable（非黒体の能力源。実温度を色から推定しない）','fill_tint':'中立の校正用環境光'},'BackgroundBinding':{'bg_dominant':'明暗の比較用display condition','bg_accent':'none（追加背景装飾なし）'},'PerceptualControl':{'attention_focus':'hierarchical','figure_ground_stability':'medium','arousal_level':'mid','perceptual_noise_tolerance':'low'}},'Acceptance':{'PEV_applied_before_AES_when_world_candidates_exist':True,'AES_does_not_override_world_validity':True,'legacy_FDS_resolved_to_DesignScience':True,'CCM_fields_fixed':True}},
 'ReflectionClosureTemplate':{'Applicability':{'applies_when':['reflection','highlight'],'otherwise':'latent_optics_condition'},'ReflectionClosureBlock':{'PH2':{'reflection_PH':'PH2','surface_type':'hard_surface','MicrofacetField':{'view_dependence':'固定正面V=(0,0,1)、連続法線とsource rayで反射軸を決定。','fresnel':'Schlick F0=0.04。校正誘電体の設計仮定であってactor材質の実測ではない。','microfacet':'GGX NDF、roughness=clamp(0.78+0.08*normal.y,0.65,0.9)、Smith型masking/shadowing。','surface_state_modulation':'濡れ・汚れなし。roughnessとnormal fieldを連続に保つ。','energy_consistency':'拡散項は非鏡面分0.96を適用。GGX項と相対入射powerを分ける。絶対放射校正は未実施。','occlusion_consistency':True},'ReflectionLinks':{'physical_influence_out':'not_applicable（反射光の再照射先PHを追加しない。出射は観測境界へ）','physical_feedback_in':'not_applicable（反射が源を変える帰還はない）'},'Evidence':['法線に依存する反射極値','同じsource色が粗い拡散と弱い鏡面成分へ分かれる']}},'Acceptance':{'reflection_integrated_into_PH_mesh':True,'lensflare_registered_as_OBS_not_reflection':True}},
 'PhenomenonProfileTemplate':{'ApplicabilityGuide':{'selections':[],'reason':'流体・火炎・金属・皮膚・布などのプリセットを追加しない。PH1は宣言場、PH2は汎用校正面。'},'ProfilePolicy':{'secondary_boost_only':True,'full_PH_structure_still_required':True,'only_selected_profiles_in_design':True},'Profiles':{},'Acceptance':{'profile_does_not_replace_PH_schema':True,'reactive_profile_only_when_applicable':True}},
 'TermsTemplate':{'PH':'世界内現象','OBS':'観測・表示変換','PIA':'PH識別・採用・登録の手順','PEM':'現象等価運用','PEV':'成立する世界状態の基準点選択','AES':'成立候補からの美的選択','CCM':'色と照明の拘束','FDS':'旧名はDesignScienceとAESへ解決','DeclaredIntent':'ユーザー明示意図','ValidationResults':'要求値ではなく実際の検査結果','Acceptance':{'undefined_legacy_terms_absent':True}}}
 # 起動した拡張のみ。
 active=['VFX','ECodeImplementation','PostEffects','LuminanceDynamicsModule','GradientAnchorPolicy']
 d['ExtensionActivationTable']={'entries':{('LDM' if n=='LuminanceDynamicsModule' else n):{'trigger':'explicit' if n in ['VFX','ECodeImplementation','LuminanceDynamicsModule'] else 'attribute_resolved','output_blocks':[n],'disabled_behavior':'omit'} for n in active},'expression_intent_ref':'InferenceExpansionPolicy.ExpressionIntent','output_contract_ref':'FoundationOperationTemplate.OutputContract','Acceptance':{'one_activation_source_of_truth':True,'disabled_modules_omitted':True}}
 layers=[]
 for lid,role,domain_,phrefs,obsrefs,logic in [('L1','primary_form','world',['PH1'],[],c['main']),('L2','internal_structure','world',['PH1'],[],c['source']+'の発光と色本体の厚みを分離。'),('L3','environment_response','world',['PH2'],[],'sourceから既存actor表面への局所反射。'),('L4','observation_support','observation',[],['OBS1'],c['optics']),('L5','observation_support','observation',[],['OBS2'],'全体を線形合成後に表示色へ写像。')]:
  layers.append({'layer_id':lid,'role':role,'domain':domain_,'selection':{'basis':'explicit' if lid=='L1' else 'attribute_resolved','scope_and_reason':'ユーザー指定のEを成立させる既存形状・材質・光学経路の具体化。独立した新規内容は追加しない。'},'PH_refs':phrefs,'OBS_refs':obsrefs,'function_and_visible_result':logic,'spatial_structure':{'anchor_and_transform':'actor x/yから共通world-camera-screen変換。' if domain_=='world' else '登録済みOBSのsource mask／画面マスク。','extent_orientation_depth':'R内の固定2.5D。主形後方部は既存actorマスクで遮蔽。sourceの局所光は+Z側成分を持つ。' if domain_=='world' else 'screenのみ。架空の物体厚みを与えない。','macro':logic,'meso':'内部稜線・継ぎ目と色本体を独立応答として分ける。' if lid in ['L1','L2'] else '登録した受光面またはマスクの連続を維持。','micro':'pixel AAを使うがnoiseや粒子で密度を増やさない。','edge_and_occlusion':'色本体と鋭い内稜線、光学的裾を同じぼかし幅にしない。'},'material_and_optics':{'carrier_and_mechanism':'PHの宣言場または既存actor表面。' if domain_=='world' else 'OBSの解析PSF／display transform。','emission_opacity_density':'coverageとbodyとemissionを別変数にする。OBSは物質密度を持たない。','color_and_light_response':c['color']+'。CCMへ束縛。','model_refs':'PH1.PhysicalModel / PH2.PhysicalModel' if domain_=='world' else 'ObservationIntegrationTemplate.ObservationRegistry'},'motion_and_phase':{'driver_and_transport':'正規eventのactor-time。target方向の輸送なし。','distribution_and_correlation':'not_applicable（粒子集合を選択していない）','onset_peak_decay':c['state'],'state_and_sampling_refs':'PH1.StateDynamics / ObservationIntegrationTemplate.SamplingContract'},'integration':{'composite_and_mask':'world可視性→actor受光→OBS1→OBS2。','protected_cues':'主形・中央actor・有限半径・1200 actor-ms。','failure_to_avoid':c['forbid']}})
 d['VFX']={'trigger':'explicit','world_registration':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_registration':'ObservationIntegrationTemplate.ObservationRegistry','design_intent':{'subject_and_action':intent['must_communicate'][0],'expression_intent_ref':'InferenceExpansionPolicy.ExpressionIntent','primary_read':c['main'],'layering_basis':'色本体、source、既存面応答、観測裾、表示変換を別機能として扱い、同色違いの同形重ねで層数を稼がない。'},'layers':layers,'interlayer_links':[{'source_layer':'L2','target_layer':'L1','relation_type':'visual_relation','mechanism_and_consequence':'同一PHの厚みと源位置を対応させる内部関係。別の物理PHを作らない。','foundation_binding':'PH1.DeepStructure / PH1.OctaDomain'},{'source_layer':'L2','target_layer':'L3','relation_type':'physical_influence','mechanism_and_consequence':physical_link(c)['mechanism'],'foundation_binding':'PH1.CausalityLinks.physical_influence'},{'source_layer':'L4','target_layer':'L2','relation_type':'observation_dependency','mechanism_and_consequence':'OBS1はPH1 sourceを参照。','foundation_binding':'OBS1.dependencies'},{'source_layer':'L5','target_layer':'L4','relation_type':'observation_dependency','mechanism_and_consequence':'OBS2はOBS1を含む合成を入力とする。','foundation_binding':'OBS2.dependencies'}],'causal_path':{'input':'上流の正規event','carrier_PH':'PH1','receiver':'PH2（既存actor受光面）','ScaleRegime_ref':'PH1.ScaleRegime','StateDynamics_ref':'PH1.StateDynamics','ReactivePhaseChange_ref':'not_applicable（反応・相変化を追加しない）'},'orchestration':{'common_time_basis':f'B基準画像はage={c["peak"]} actor-ms。E実装は同じStateDynamicsを0..1200へ展開。映像モデルや別Durationは作らない。','layer_phase_relations':c['state']+'光学応答は同時、音は同じactor時刻を参照。','environment_response':'PH1源とPH2法線が局所光の位置・方向を拘束。','visual_hierarchy':'色本体と主形を先に、局所白芯と受光を次に、OBSを補助に置く。','bullet_time':'not_applicable（未指定）'},'output_integration':{'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','LDM_ref':'LuminanceDynamicsModule','composite_order':['world_body','world_emission','actor_receiver','OBS1','OBS2'],'color_alpha_contract':'線形RGBでbody*coverageを合成し、emissionを別加算。最終canvas alphaMode=opaque。サンプル画像なし。','scale_adaptation':'actorH64とE全包絡H64を区別し、AAは1/scale画素に対応。'},'validation_plan':{'layer_checks':'OBS OFF、局所光OFFの比較。sourceの位置とpowerはsampler全寿命で照合。','composite_checks':'明暗・全寿命・3原因重複・範囲外漏れ。','temporal_checks':'純粋samplerの1ms検査とactor-time音声cursor検査。実GPU連続性は未実施。','actual_results_ref':'GlobalAcceptanceTemplate.ValidationResults'},'Acceptance':{k:True for k in ['world_VFX_registered_as_PH','observation_only_effects_not_misregistered_as_VFX_PH','layer_roles_scales_and_relations_explicit','layer_count_does_not_force_new_content_or_PH_partition','material_motion_environment_and_composite_consistent','shared_intensity_and_sampling_contracts_preserved','structural_requirements_not_reported_as_render_evidence']}}
 d['PostEffects']={'trigger':{'ordinary_posteffects':False,'beta_targets':[]},'selection':{'mode':'exact_selected_operations','scope_resolution':'attribute_resolved_target_and_scope','exact_selected_operations':['source_bound_anisotropic_PSF'],'basis':'PH1の強い源を固定観測経路へ入力する応答だけを具体化。'},'autonomous_activation':{'physical_causality_input_required':False,'registry':'ObservationIntegrationTemplate.ObservationRegistry','budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract'},'SPCA':{'applies_if':'world_internal_PH_local_peak_selected','evidence_types_standard_two_of':['gradient','decay','occlusion'],'explicit_intent_adjustment':'not_applicable','PostEffects_alone_does_not_require_new_PH':True},'global_posteffects':{'applies':False,'exact_OBS_operations':[],'OBS_refs':[]},'local_posteffects':{'applies':True,'targets':['PH1の源'],'exact_OBS_operations':['source_bound_anisotropic_PSF'],'OBS_refs':['OBS1']},'operation_contract':{'required_fields':['input_references','target_mask','stage','composite_method','intensity','protected_regions','sampling_consequence'],'sampling_consequence':'基底SamplingContractを参照。別の全体sampling予算は作らない。'},'Acceptance':{'exact_selected_operation_does_not_infer_layers':True,'global_local_scope_unambiguous':True,'legacy_five_domain_reference_absent':True}}
 d['LuminanceDynamicsModule']={'trigger':{'explicit_VFX':True,'explicit_PostEffects':False,'inferred_requires_luminance_dynamics':False},'omitted_if_not_enabled':True,'target_metrics':{'target_size':f'R={c["radius"]}','camera_distance':'固定直交。距離を透視倍率と混同しない。','screen_occupancy':min(1,2*c['radius']/384),'readability_priority':'high'},'Image':{'spatial_envelope':c['source']+'の局所極値と有限外縁。','local_contrast_budget':c['optics']},'Video':{'temporal_envelope':'not_applicable（映像生成ではない。E時刻はStateDynamicsへ）','micro_variation':'none（未指定の揺らぎを追加しない）','anti_flicker':'実行時の意図しないちらつきはGPU再検査対象。'},'budget_ref':'ObservationIntegrationTemplate.IntensityBudget','sampling_contract_ref':'ObservationIntegrationTemplate.SamplingContract','sampling_consequence':'強い白い芯は局所に保持。H64での量子化を別に評価。','AlphaBackground':{'enabled':False,'required_background_if_enabled':'#000000'},'alpha_ref':'LuminanceDynamicsModule.AlphaBackground','ActivationExclusions':{'non_emissive_particles_only':'no_auto_activation','grain_only':'no_auto_activation'},'Acceptance':{'mode_specific_envelope':True,'numeric_defaults_subordinate_to_target_metrics':True,'no_unwanted_global_luma_lift':True,'screen_processing_stays_in_observation_layer':True}}
 d['GradientAnchorPolicy']={'trigger':'hue_gradient_attribute_resolved','gradient_type':'world_VFX_gradient','anchor':'PH1','anchors':[{'position':'色本体の厚い側','role':'主形を読む','color':'銅色' if c is A else '濃藍'},{'position':'内部の稜線','role':'状態の局所差','color':'琥珀' if c is A else '紫'},{'position':c['source'],'role':'源の極値','color':'象牙白' if c is A else '淡紫白'}],'registration':{'world_surface_gradient':'PhenomenonSystemTemplate.PhenomenonRegistry','world_VFX_gradient':'PhenomenonSystemTemplate.PhenomenonRegistry','observation_gradient':'ObservationIntegrationTemplate.ObservationRegistry'},'Acceptance':{'physical_and_observation_gradients_distinguished':True,'unanchored_world_gradient_absent':True}}
 d['ECodeImplementation']={'trigger':'executable_runtime_E_code_explicit','output_kind':'executable_effect_source_not_image_generation','source_revision':PIN,'target_runtime':'WebGPU + WebAudio AudioWorklet','source_and_time_contract':'eventId/causeId/playerId/targetId/x/y/actorStartMsは不変。半開区間0≤age<1200。player別actor時計を使用。B画像基準点は設計のみ。','world_PH_refs':['PH1','PH2'],'observation_OBS_refs':['OBS1','OBS2'],'implementation_artifacts':['src/contract.mjs','src/actor-clock.mjs','src/sampler.mjs','src/e-player.mjs','src/gpu.mjs','shaders/effects.wgsl','src/sfx-synth.mjs','src/voice-kernel.mjs','src/sfx-worklet.mjs','src/audio.mjs',f'sfx/{c["event"]}.wav'],'applicable_rule_evidence':'design/rule-implementation-map.json','validation':{'syntax_and_shader':'not_run','actual_GPU_pixels_and_timing':'not_run','game_event_and_SFX':'not_run'},'SFX_contract':{'cause_binding':'eventId/causeId/playerId/actorStartMsをPH1と共有。対象方向のpan、別cause生成、遅着の頭出しを行わない。','voice':'一原因に一つのPCM cursor。左右channelや合成部分音を独立voiceとして起動しない。','sample_rate_Hz':48000,'channels':2,'lifetime_actor_ms':1200,'phase_design':c['sfx'],'runtime_time':'AudioWorkletはplayer別clockから各出力sampleのactor時刻を求める。rate=0で無音停止、rate変更は同じPCMの読取速度を変更する。','limitations':'rate変更時のpitch変化、音響出力latency、workletメッセージ遅延は実機検査前。既提出GPU frameの提示時刻は遡及修正できない。'},'validation_detail':'JS構文とNode契約検査、PCM/CPU参照は別途実施。WGSLコンパイル、実GPU、実聴、本編接続は未実施。','Acceptance':{'baseline_and_selected_extensions_preserved':True,'image_generation_not_implied':True,'runtime_code_and_visual_acceptance_distinguished':True}}
 d['GlobalAcceptanceTemplate']={'Requirements':{k:True for k in ['PhenomenonRegistry_required','full_PH_structure_required','all_8_domains_required','ObservationRegistry_required_when_OBS_exist','WindCapsule_required','Gravity_required','world_camera_screen_transform_required']},'ValidationResults':{'StructuralInspection':{'status':'not_run','checks':{}},'SemanticReconciliation':{'status':'warning','checks':{'DeclaredIntent_preserved':'受信値とgeometry不変条件はNode検査。主ゲームの実イベント形式は未照合。','trigger_resolution':'VFX、E実装、源束縛PostEffects、LDM、色アンカーだけを起動。','exception_resolution':'新しい例外を作らない。reduced motionは明示UI選択の別検査条件。','source_binding':'sourcePoint/sourcePowerをPH1・局所光・OBSで共有。','scope_and_dependencies':'caster-local、OBS依存は非循環。','scientific_consistency':'宣言場と校正近似を実測物性と区別。実照度・レンズPSF・実actor材質は未測定。'}},'RenderObservation':{'status':'not_run','evidence_source':'none（実GPU画像なし。CPU参照は別記録）','checks':{k:'not_run' for k in ['visual_causality','contour_preservation','clipping_crushing','chroma_detail','contact_projection','temporal_continuity','cue_discrimination_and_sampling']}}},'OutcomeEvaluation':{'intent_alignment':{'status':'not_run','evidence_refs':[],'rationale':'正式WGSL出力を観察していない。'},'artistic_effect':{'status':'not_run','evidence_refs':[],'evaluator_basis':'not_run','strengths':'not_run','limitations':'実人物マスク、実GPU、実表示・実聴未実施。'}},'ComparativeEvaluation':{'status':'completed','question':'源とOBS、局所受光の役割がCPU参照式で分かれるか。','changed_factor':'OBSまたはlocalLightの有無、明暗、尺度、3原因重複。','controlled_conditions':'純粋sampler値とCPU数式。GPU精度・device差は制御していない。','scene_set':['独立する合理オペE','独立する忍殺準備E'],'repetitions_and_order':'決定的CPU比較、一条件一実行。無作為化や盲検化は未実施。','criteria':'範囲外漏れゼロ、寿命端の基準像一致、OBS OFFでも主形が残る、localLight OFFで受光差が消える。','evidence':['evidence/node-tests.tap','evidence/cpu-pixel-tests-all-all.json'],'result_and_limitations':'CPU比較だけの成立。画質優越・実GPU合格・普遍的な芸術性を主張しない。'},'FinalStatus':{'specification_status':'Warning','render_status':'NotRun','failure_reasons':[],'warning_reasons':['正本同梱検証器は未実行。ローカル構造検査を別途記録。','実GPU・実聴・本編イベント接続は未実施。']}}
 return d
for c in [A,B]:
 (ROOT/'design'/f'{c["event"]}.B-Expression-2.json').write_text(json.dumps(build(c),ensure_ascii=False,indent=2))
print('two B design instances written')
