"""適用規則を正本参照・実装・期待帰結・検査の四者へ対応付ける。"""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
# 正本のrequirementは本文を参照する。ここでは規則名を再定義しない。
groups=[
('InferenceExpansionPolicy','InferenceExpansionPolicy AttributeAndActionResolutionRule DeclaredIntentRule ExpressionIntentRule','design/*.B-Expression-2.json; src/contract.mjs:validateEvent; src/sampler.mjs:sampleEffect','指定された二現象・寿命・IDを保持し、回復・射出・対象位置・勝手な効果を増やさない。','contract'),
('FoundationOperationTemplate','FoundationOperationRule RuleContractRule PriorityRule ConflictResolutionRule UniversalNoLabelOnlyRule OutputAndReferenceResolutionRule','tools/build_designs.py; tools/validate_local.py; design/design-contract.md','Image/design_onlyのB設計と実行Eを分け、実画像生成を起動しない。参照と構造を監査する。','structure'),
('PlatonicGoodTemplate','PlatonicGoodFoundation BeautyStructuringRule NoSingleBeautyStructureDominance GTBImplementationMapping','design/*.B-Expression-2.json:PH.BeautyStructureApplication; shaders/effects.wgsl:rational/ninjutsu','開口／収束、明暗での色本体、sourceと受光の関係を別の手掛かりにする。','pixel'),
('PhenomenonSystemTemplate','UniversalPhenomenonRule PIA VisibilityDefinition LinkTypeRule DeepStructureRule StateTransformerRule VisualCausalityRule UniversalMaterialResponseRule HubPhenomenonRule PhysicalModelClosureRule ScaleAndSimilarityRule DynamicResponseAndStabilityRule PerceptualEvidenceDiscriminationRule CausalAssessmentAndUncertaintyRule CommonPHFailurePatterns PartitionAndSharedConditionsRule VisualProjectionRule','design/*.B-Expression-2.json:PhenomenonSystemTemplate; src/sampler.mjs; shaders/effects.wgsl:Field/rational/ninjutsu/receiverLight/receiverGloss','場PH1と既存受光面PH2を分離。八領域を保持し、非該当機構は生成しない。PH1は宣言場、PH2は校正代理であり実測物性と偽らない。','structure_pixel'),
('PEMTemplate','PhenomenonEqualityMode AttentionRuleWithCCM','design/*.B-Expression-2.json:PEMTemplate; shaders/effects.wgsl:sourcePoint/receiverLight','主形とsource、局所受光を接続する。目立つ白芯を孤立した装飾にしない。','pixel'),
('CoordinateGravityWindTemplate','CoordinateSystemDefinition RelationPriorityRule GlobalVectorFieldRule StateTransitionRule GravityConditionDefinition WindCapsuleOperationRule VisibleTranslationRule','src/sampler.mjs:sourcePositions/packedSamples; shaders/effects.wgsl:fs; design/*.B-Expression-2.json:CoordinateGravityWindTemplate','同一x/yとradiusから画面座標へ写像。風・床を追加せず、校正尺度を仮定として明示する。','contract_pixel'),
('OctaDomainTemplate','OctaDomainDefinition','tools/build_designs.py:domains; design/*.B-Expression-2.json:PH.OctaDomain','適用しない流体・電荷・濡れ・波動等も理由付きlatentとして保持。','structure'),
('AnimeStudiesTemplate','ImageOrientedAnimeStudiesLayer AnimeLayoutRule KeyframeSnapshotRule SilhouetteDesignRule AnticipationAftermathRule LimitedAnimationStillnessRule SakugaDensityRule AnimeCompositeRule ImageOriented12PrinciplesSubset','src/sampler.mjs:sampleEffect; shaders/effects.wgsl:rational/ninjutsu; design/*.B-Expression-2.json:AnimeStudiesTemplate','前後位相は既存主形の変位と局所消灯で示す。残像・スピード線・人体動作を追加しない。','pixel'),
('ObservationIntegrationTemplate','ObservationRegistrySeparationRule OperationClasses PostEffectsCommonRule ObservationIntensityBudgetRule CompositeValidationRule SamplingAndReconstructionRule StrictTermDefinitions','shaders/effects.wgsl:Field.observation/fs/aces/toSRGB; src/gpu.mjs:resize/draw; design/*.B-Expression-2.json:ObservationIntegrationTemplate','OBS1のsource-bound解析PSFとOBS2表示変換をPHから分離。背景や主形へ一律の白飛びを広げない。','pixel'),
('ExtremumDesignColorTemplate','PEVRule AESRule DesignScienceRule CCMScope AESEvaluationAxes ColorScienceInAES ArtisticBeautyDefinitions','tools/build_designs.py; src/sampler.mjs:sampleEffect; shaders/effects.wgsl:rational/ninjutsu','解除156msと収束610msを別の基準点にし、銅琥珀／濃藍紫と白芯の役割を分ける。','pixel'),
('ReflectionClosureTemplate','ReflectionVsLensFlareSeparation ReflectionClosureRule MicrofacetFieldMinimumSet ReflectionLinkRule','shaders/effects.wgsl:receiverGloss/receiverLight; design/*.B-Expression-2.json:ReflectionClosureTemplate','粗い校正面の反射を世界内の受光として計算。PSFをレンズゴーストと偽らず、反射帰還を捏造しない。','pixel'),
('TermsTemplate','Terms','design/*.B-Expression-2.json:TermsTemplate','PH/OBS/E/actor-timeを別責務として記録。','structure'),
('GlobalAcceptanceTemplate','GlobalAcceptanceCriteria ComparativeEvaluationRule PassWarningFailEvaluation IntentAndArtisticOutcomeRule','tools/validate_local.py; tools/build_report.py; evidence/validation-report.json','CPU参照・JS検査と実GPU・実聴・芸術評価を区別し、未実施をnot_runで残す。','structure'),
('ExtensionActivationTable','ExtensionActivationRule ExpressionIntegrationRule','tools/build_designs.py:ExtensionActivationTable','VFX、ECodeImplementation、PostEffects、LDM、Gradientだけを起動。キーワード・魔法プリセット・人体姿勢・Videoは未起動。','structure'),
('VFX','VFXActivationRule MultilayerArchitectureRule SpatialMorphologyRule MaterialOpticalResponseRule TransportTemporalRule EnvironmentCompositionRule CompositingReadabilityRule','shaders/effects.wgsl:rational/ninjutsu/receiverLight/fs; src/sampler.mjs; design/*.B-Expression-2.json:VFX','色本体、局所source、受光面、観測裾、toneを異なる役割として実装。層数のために部品やPHを増やさない。','pixel'),
('ECodeImplementation','ExecutableECodeBranchRule','src/e-player.mjs; src/gpu.mjs; src/audio.mjs; src/voice-kernel.mjs; tests/contracts.test.mjs; tests/gpu-harness.mjs','正規原因とplayer別actor時刻を保持。遅い提出前に時刻を再採取し、一原因一声。主ゲームへ接続しない。','contract'),
('PostEffects','PostEffectsAutonomousActivationRule SPCARule GlobalLocalRule','shaders/effects.wgsl:rational/ninjutsu/fs; design/*.B-Expression-2.json:PostEffects','属性具体化による選択操作だけを局所適用。ordinary_posteffects=false。世界内ピークは主形と源で成立。','pixel'),
('LuminanceDynamicsModule','LDMActivationRule LDMModeRule','src/sampler.mjs:sampleEffect; shaders/effects.wgsl:sourcePower; design/*.B-Expression-2.json:LuminanceDynamicsModule','明示VFXで起動。源の異なるピークと空間包絡を保持し、粒子・点滅・黒背景を自動追加しない。','contract_pixel'),
('GradientAnchorPolicy','GradientAnchorRule','shaders/effects.wgsl:rational/ninjutsu; design/*.B-Expression-2.json:GradientAnchorPolicy','色本体・稜線・白芯の三つの役割にアンカー。均等な虹帯や背景の抽象グラデーションを作らない。','pixel')]
rows=[]
for owner,names,locations,expected,kind in groups:
 for name in names.split():
  rows.append({'rule_id':f'{owner}.{name}','requirement_ref':{'spec_file':'拡張.md' if owner in ['ExtensionActivationTable','VFX','ECodeImplementation','PostEffects','LuminanceDynamicsModule','GradientAnchorPolicy'] else '基底.md','section_rule':f'{owner}.{name}','revision':'provenance/source-revision.json'},'source_locations':locations.split('; '),'observable_consequence':expected,'verification':{'local_static':'evidence/local-structure.json','Node':'evidence/node-tests.tap' if 'contract' in kind else 'not_applicable_to_this_rule','CPU_reference':'evidence/cpu-pixel-tests-all-all.json' if 'pixel' in kind else 'not_applicable_to_this_rule','actual_GPU':'not_run','human_visual_or_listening':'not_run'},'result_scope':'参照と実装箇所の対応。構造項目の存在だけで画素・科学・芸術の合格にしない。'})
excluded=[{'scope':'CharacterPolicy / BeautifulPoseCapsule / Body-Floor-Camera / FloorHub / PoseActing','reason':'人間・キャラクター身体・床形状は入力されていない。既存actorの校正面は非人物の受光体。人体・支持を推測しない。'}, {'scope':'KeywordExpansion / MagicArchitecture / VideoGenerationPolicy','reason':'当該の明示選択なし。Eの実行時間をVideo生成Durationに転用しない。'}, {'scope':'physical_lensflare_* / MaterialReflectionMinimums skin/cloth/wet / ReactivePhaseChange','reason':'実レンズゴースト、skin/cloth/wetの表面、反応・相変化は採用していない。'}, {'scope':'VFX.ScreenSignalSurfaceRule','reason':'走査線、信号ノイズ、色ずれ等は未選択。'}, {'scope':'NaturalVarianceRule / ProjectionSafetyRule / selected profiles','reason':'自然流体の変動、俯瞰・煽り、適用profileは本設計にない。'}]
(ROOT/'design/rule-implementation-map.json').write_text(json.dumps({'status':'traceability_map_not_render_acceptance','rules':rows,'conditional_non_applicability':excluded,'limitations':'ローカルの対応監査。正本の全規則の形式証明や同梱検証器の結果ではない。'},ensure_ascii=False,indent=2)+'\n')
print(len(rows),'rule mappings written')
